### ISSUE TITLE
Client starts, can sign in, nothing else 

### ISSUE THREAD

**Issue by GNUGradyn** [Soundnode/soundnode-app#1001]
I can sign into the client, and the client starts successfully, but thats as far as the use of this client goes. Nothing will appear in the big main pane in the middle. Clicking on buttons will navigate thru menus and such, but searching and doing anything in the big box in the middle is impossible. I am on arch linux, let me know if you need any info about my OS stack
![image](https://user-images.githubusercontent.com/20762604/28198618-b99f2a0a-681c-11e7-923c-377ff3e0dae5.png)

**Comment by weblancaster** [comment]
@GNUGradyn unfortunately there is a bug in the current Linux release the fix is in master but I haven't released yet.
