### ISSUE TITLE
not hearing any sounds on Linux (Mint) although it appears like the song is playing

### ISSUE THREAD

**Issue by Sinan81** [Soundnode/soundnode-app#1005]
* not hearing any sounds on Linux (Mint) although it appears like the song is playing
* system:
  Linux Mint 18 Sarah, Mate desktop, 64 bit

**Comment by weblancaster** [comment]
@Sinan81 sorry but the last release for linux distro contain a bug. I'm testing the new release and will be available end of this week or so.
