### ISSUE TITLE
Doesnt install on Ubuntu 17.04

### ISSUE THREAD

**Issue by a9e78rauijasdf** [Soundnode/soundnode-app#1012]
Hi,

Doesnt work using official installer:

etched 332 kB in 17s (19,3 kB/s)
Reading package lists... Done
W: The repository 'https://packagecloud.io/JonasGroeger/soundnode/ubuntu zesty Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.

# apt-get install soundnode

# apt-get install soundnode
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package soundnode

**Comment by wb9688** [comment]
In /etc/apt/sources.list.d/soundnode.list (or something like that), change
'zesty' to 'yakkety'.

**Comment by a9e78rauijasdf** [comment]
Hm, it works, thanks wb9688 :-) Ill open a new issue for playback..."Oh no, something went wrong. I can't play this track :("

**Comment by wb9688** [comment]
See #802 for that, I've also posted a temporary solution there.

**Comment by a9e78rauijasdf** [comment]
Yeah I just found it - but as Im not using username/password - I cant use the workaround. No option for google auth unfortunately - and I dont see solutions in  #998 as well :(

**Comment by bzhr** [comment]
There's no `soundnode.list` file in `/etc/apt/sources.list.d/`

**Comment by augustopaula** [comment]
@bzhr  Try to find this one `JonasGroeger_soundnode.list`
