### ISSUE TITLE
7.0.0 darwin build is actually windows build

### ISSUE THREAD

**Issue by farfromrefug** [Soundnode/soundnode-app#1035]
If you extract the darwin build, you end with the windows archive ;)

**Comment by nicolasbrugneaux** [comment]
Same issue, the darwin build from the release page is actually win32, and the one on the website isn't updated (still the previous version).

**Comment by jakejarrett** [comment]
Oops my bad. I guess the archiving program i ran broke the output, will update this shortly.

Regarding the website, there is a PR to update the download link on the website.

**Comment by jakejarrett** [comment]
This now contains the correct builds in each archive, Thanks for reporting that :smile:
