### ISSUE TITLE
Mac app: Show "Update available" for latest version app

### ISSUE THREAD

**Issue by vedhavyas** [Soundnode/soundnode-app#1041]
The version installed: 0.6.5(latest)

**Comment by samakshjain** [comment]
If I understand correctly, (for me)the `Update Available` message is shown even though I have the latest version(0.6.5) installed.

**Comment by jakejarrett** [comment]
The latest version is `7.0.0` on github, but the website hasn't been updated to reflect this

**Comment by spellxthie** [comment]
how do i upgrade to 7.0.0? electron-builder/electron-packager?

**Comment by jakejarrett** [comment]
It's currently only available here

https://github.com/Soundnode/soundnode-app/releases/tag/7.0.0

**Comment by vedhavyas** [comment]
Closing this since the current version(7.0.0) is working as expected

**Comment by keishawnf** [comment]
I can't seem to find the Mac version of 7.0.0

**Comment by jakejarrett** [comment]
Mac OS is under `darwin`
