### ISSUE TITLE
Ubuntu 18.04 bionic missing deb

### ISSUE THREAD

**Issue by petrleocompel** [Soundnode/soundnode-app#1075]
On https://packagecloud.io/JonasGroeger/soundnode is not a package for bionic.
So script for adding repo works, but no package found for installation.

**Comment by jakejarrett** [comment]
Just tagging @JonasGroeger as he runs this portion.

**Comment by AlexDunmow** [comment]
If you replace bionic with xenial in the list file, you can install it (after running apt-get update).

**Comment by fabotic** [comment]
So how would one go about replacing bionic with xenial in the list file?

**Comment by kenzdozz** [comment]
> So how would one go about replacing bionic with xenial in the list file?

sudo nano /etc/apt/sources.list.d/JonasGroeger_soundnode.list

**Comment by gvmohzibat** [comment]
I use Ubuntu 18.04 and I'm not able to install soundnode. I get this error:
```
E: Unable to locate package soundnode
```

I ran this command:
`curl -s https://packagecloud.io/install/repositories/JonasGroeger/soundnode/script.deb.sh | sudo bash
`
Then I changed bionic to xenial in this file:
```sudo nano /etc/apt/sources.list.d/JonasGroeger_soundnode.list```
And the I ran `sudo apt install soundnode` and I got the error.
Please help

**Comment by jakejarrett** [comment]
This is expected atm as the ubuntu ppa is no longer maintained, there is ongoing work with electron-builder to add support for `snap` and rolling builds of deb/rpm etc.

**Comment by simoniz0r** [comment]
Please actually update your repositories.  It is not sane to recommend users do what's happening here.
Also, I'd suggest looking into AppImage instead of providing a universal package in a tar archive.

**Comment by V3rB0se** [comment]
if you want to install the package in unsupported distros just download the script 
https://packagecloud.io/install/repositories/JonasGroeger/soundnode/script.deb.sh
and from terminal 
`os=ubuntu distro=trusty ./script.deb.sh`
after setting it up execute `sudo apt-get install soundnode`>

**Comment by bjwest** [comment]
Script doesn't work in Focal.  os=ubuntu distro=focal script.deb.sh returns: 
```
Unfortunately, your operating system distribution and version are not supported by this script.

You can override the OS detection by setting os= and dist= prior to running this script.
You can find a list of supported OSes and distributions on our website: https://packagecloud.io/docs#os_distro_version

For example, to force Ubuntu Trusty: os=ubuntu dist=trusty ./script.sh

Please email support@packagecloud.io and let us know if you run into any issues.
```

How about instructions on how to compile the source?  You seem to do everything in your power to not allow people to install your program, and using a script like you do triggers security issues in may people, as it should.  I'm with @simoniz0r up there as well, AppImage is much better than snap.

I've already spent over an hour trying to get this thing installed and I'm do for a while.  Maybe I'll check back in a few weeks.

**Comment by petrleocompel** [comment]
I guess there is no need for bionic deb which this issue was about. If you really want anything else create other issue.
