### ISSUE TITLE
Install instructions when not using a package manager

### ISSUE THREAD

**Issue by gaining** [Soundnode/soundnode-app#1082]
Hello,

I'm just wondering how I can install it without a package manager. `npm install` doesn't seem to do the trick for me.

**Comment by jakejarrett** [comment]
As in, you don't have npm installed or `npm install` just simply didn't work?

Are you able to paste the error output?

**Comment by gaining** [comment]
ah... yes it did not work. But that's because i had an old version of npm installed in my package manager on jessie. Now I installed it via nvm (the latest stable) it seems to be installing right now. Thanks for getting back so quick

**Comment by jakejarrett** [comment]
Ah thanks, good to note that, I'll see if i can update some notes later tonight so a specific min version can be locked down for getting soundnode running
