### ISSUE TITLE
Can't log with Google

### ISSUE THREAD

**Issue by RavengamerSpace** [Soundnode/soundnode-app#1087]
Hi,

I can't use my Google Account to connect. It just say to me to wait but nothings appear

![Screenchot](https://user-images.githubusercontent.com/28545669/45920038-300c7380-be9f-11e8-9db9-5e0611e33ebf.png)

**Comment by RavengamerSpace** [comment]
PS: I use the 7.0 version, and the 6.4 was working

**Comment by RavengamerSpace** [comment]
PS: I use the 7.0 version, and the 6.4 was working

**Comment by jakejarrett** [comment]
Are you able to post any logs/error? (Either by launching from the cli or by opening devtools w/

**Comment by RavengamerSpace** [comment]
@jakejarrett I'm sorry but how I can open the devtools ?

**Comment by jakejarrett** [comment]
oh sorry, mobile killed the markdown i write. it should be `control + /`

**Comment by RavengamerSpace** [comment]
@jakejarrett Euh... Nothing happened

**Comment by RavengamerSpace** [comment]
Nothing

![capture d ecran de 2018-09-26 17-21-46](https://user-images.githubusercontent.com/28545669/46108894-75061200-c1df-11e8-8728-fdfa7640e4d5.png)

**Comment by jakejarrett** [comment]
Hm not too sure, i'll have to check into this further this weekend to double check what's wrong with 7.0

**Comment by patricelynde** [comment]
@RavengamerSpace You can open the devtools with `Control+Shift+I`

**Comment by bulletfever409** [comment]
Getting the same issue on windows

**Comment by cberez** [comment]
Issue still valid on linux...

**Comment by RavengamerSpace** [comment]
Well, it feels like the project is discontinued...
The last modification was in October 2018
So, I think the project is dead but maybe we can save it !

**Comment by cberez** [comment]
Yep your right, shame it's a good project ^^
