### ISSUE TITLE
macOS does not support 'xz' by default

### ISSUE THREAD

**Issue by tjluoma** [Soundnode/soundnode-app#1132]
I noticed that (starting with version 7.0.0) the macOS/darwin builds are `Soundnode-darwin-x64.tar.xz`

I just thought it was worth mentioning that `xz` is not included in macOS by default. `.zip` would be a safer choice. Even `tar.bz2` would be more preferable than `.tar.xz`.

FWIW, I un-archived the `.tar.xz` version and then re-compressed it with `.tar.bz2` and `.zip`. Here are the file sizes (in bytes):

```
62044259 Soundnode-darwin-x64.zip
51076892 Soundnode-darwin-x64.tar.bz2
39194300 Soundnode-darwin-x64.tar.xz
```

So while `.tar.xz` is a more efficient compression, it's only a difference of ~12 MB compared to `.tar.bz2`

**Comment by tjluoma** [comment]
Upon closer examination, macOS does lack a separate `xz` command, however, the default **"Archive Utility.app"** _can_ open these files, as can the `tar` command with a simple `tar vxf Soundnode-darwin-x64.tar.xz`

So I'm going to close this issue as being a non-issue.

**Comment by jakejarrett** [comment]
Ah thanks for that. Yeah, went with `tar.xz` as from what I remember, any unix-like system should support the format out of the box.
