### ISSUE TITLE
npm ERR! missing script: package

### ISSUE THREAD

**Issue by AlexandrParkhomenko** [Soundnode/soundnode-app#1146]
https://aur.archlinux.org/packages/soundnode/  # This is package
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=soundnode  # This is make script
yay -S soundnode   # this is make command

# this is log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'package' ]
2 info using npm@6.14.4
3 info using node@v13.12.0
4 verbose stack Error: missing script: package
4 verbose stack     at run (/usr/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /usr/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:116:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:436:5
4 verbose stack     at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:391:45)
4 verbose stack     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:434:3)
4 verbose stack     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:161:5)
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:281:12
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:115:16
4 verbose stack     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
5 verbose cwd /p/AUR/soundnode/src/soundnode-app-7.0.0
6 verbose Linux 5.5.13-arch1-1
7 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "package"
8 verbose node v13.12.0
9 verbose npm  v6.14.4
10 error missing script: package
11 verbose exit [ 1, true ]

**Comment by acxz** [comment]
The soundnode-app is currently broken on the AUR: See: https://github.com/Soundnode/soundnode-app/issues/1131

In the meanwhile you can use `soundnode-git` from the AUR

**Comment by AlexandrParkhomenko** [comment]
Excuse me. It was an incorrect PKGBUILD script
[https://github.com/acxz/pkgbuilds/issues/35](https://github.com/acxz/pkgbuilds/issues/35)
