### ISSUE TITLE
Update Electron packager version. Arch Linux fails with "missing error package" 

### ISSUE THREAD

**Issue by orzklv** [Soundnode/soundnode-app#1148]
When I manually updated electron packager version, package building finished successfully. Please update the version of electron packager)

**Comment by acxz** [comment]
can you explain how you reproduced this issue, I have been able to use soundnode just fine on ArchLinux. (not the latest release, but the latest commit. It is also on the AUR, see: https://aur.archlinux.org/packages/soundnode-git)

**Comment by acxz** [comment]
I guess u figured it out ;)

**Comment by orzklv** [comment]
Yes)
