### ISSUE TITLE
[Improvement] Add I10n and/or I18n (Localization and Internationalization)

### ISSUE THREAD

**Issue by weblancaster** [Soundnode/soundnode-app#134]
The translation should leave on a json file under the country "flag" e.g en_us, pt_br.

**Comment by psyclip-r** [comment]
node-gettext / gnu-gettext ?

**Comment by wb9688** [comment]
Or [i18next-node](http://i18next.com/node/)? I will look into it when I have time...

**Comment by weblancaster** [comment]
@wb9688 i18next-node looks pretty good.

**Comment by wb9688** [comment]
@weblancaster I tried implementing localization using [l20n](http://l20n.org), but the console gives the error `l20n.min.js:1 Uncaught (in promise) TypeError: undefined is not a function ` :disappointed_relieved:
