### ISSUE TITLE
[Feature] auto download and install new versions.

### ISSUE THREAD

**Issue by weblancaster** [Soundnode/soundnode-app#192]

**Comment by xbenjii** [comment]
Very interested on how you're going to implement this.

Will it be something along the lines of

1. Check github version to app version
2. If github > app download zip release from github
3. Unzip and overwrite current files?

**Comment by weblancaster** [comment]
@xbenjii Yep.. that's kinda what I'm thinking to do. I haven't stop to think much about it yet.

But the user will need to click on `update available` which instead of redirect the user to the website will download the new version rename the old version folder as `old_soundnode-app` delete the old and open the new.

Also. I might use this module https://github.com/kevva/download

**Comment by xbenjii** [comment]
@weblancaster I've just finished writing an updater for one of my apps. It's very messy, but it works. And since the files are read into memory when node-webkit is launched, you can overwrite files as it's running then restart the app with:
```
require("child_process").spawn(process.execPath, [], {detached: true}).unref();
require('nw.gui').Window.get().close();
```

Also there's a lot of dependencies on that module, don't forget that you will have to distribute those too.

**Comment by weblancaster** [comment]
@xbenjii where is the code? can I see it.

**Comment by xbenjii** [comment]
@weblancaster https://gist.github.com/xbenjii/349c5961aa0085da94b9

**Comment by weblancaster** [comment]
Nice @xbenjii thanks for sharing.

Yeah I want to use something similar.. that feels smooth for the use but I also want to keep it simple for future contributions.

**Comment by xbenjii** [comment]
@weblancaster If you packed the app using a `package.nw` file, this could be hugely simplified. (Download package.nw, overwrite, restart)

**Comment by xbenjii** [comment]
@weblancaster If you go ahead with this, you'll probably have to re-think how you distribute your main releases, since you won't be able to update the exe file.

**Comment by weblancaster** [comment]
@xbenjii I will keep it simple.. download the new version (extract and open) remove/delete the old one.

**Comment by psyclip-r** [comment]
Popcorn Time is a nw app, they have implemented auto update feature.

**Comment by weblancaster** [comment]
Thanks @psyclip-r I'm aware of that I also saw some other Apps using auto update.. but each does the way they feel like/ suits the App.

This is also another chance for me to code something cool from scratch ;)

**Comment by xbenjii** [comment]
I guess you didn't like my implementation :(

**Comment by weblancaster** [comment]
@xbenjii your PR had way too much files in the commit.

**Comment by xbenjii** [comment]
@weblancaster They were just dependencies, and were the only way to unzip the file. Unless you implemented a back-end download service from which the app would download the update files from. 

The only other way I can think of is to proc the native zip application from the OS and setup a file watcher to check if the files had been unzipped.

**Comment by jakehh** [comment]
You could do a method that during Minor/Patch Updates, You provide a .nw, On major updates you provide an entire Node-webkit stack?

This would follow the Semantic Versioning & Would probably be the easiest to implement (unless windows supports node's glib & you can use glib to extract all the archives)

**Comment by MichielDeMey** [comment]
I partially implemented the auto-updater feature for the Popcorn-Time app back when it was still on GitHub, it was pretty well implemented an even had a basic hash check to make sure malicious users couldn't distribute spyware versions in case the servers got hacked.

Feel free to reply in this thread if you need some help or if you're unsure of your implementation.

**Comment by Chriz007** [comment]
I'm not complaining for manually having to download/redownload soundnode again everytime it updates, but still, it would be a great feature that I look forward to. Page subscribed.

**Comment by weblancaster** [comment]
Yesterday I worked on it https://github.com/Soundnode/soundnode-app/commits/auto-update

I have the code working but I'm indecisive on rather use the node module download or not.

any feedback on that @jakejarrett @Pitros @Chriz007

**Comment by Pitros** [comment]
To update whole app in most times we just need to replace `nw.pak` file (which is protected while nw.js is running) leaving nw.js runtime files untouched. Only next releases with nw.js updated will require full download. So that would bring down update filesize by ~40MB (current nw.pak is 7MB but with updater files that would change)
While I was reading about auto-updater I remember that someone has used node to create new node/nw.js (one of those) process to update files, when main process was killed so `nw.pak` wasn't protected anymore.
That option would be great but It would require more work.

Meanwhile with your idea app will not able to unpack new files in the same directory.

**Comment by weblancaster** [comment]
Let's work to improve that.. for now I will release this way.

**Comment by Chriz007** [comment]
I'm a very visual person, so I would have to see a mockup version of this.

**Comment by jakejarrett** [comment]
@weblancaster would Node's inbuilt Zlib be good enough for unzipping the downloaded files? 

[Reference](https://nodejs.org/api/zlib.html#zlib_class_zlib_unzip)
