### ISSUE TITLE
[Feature] Hotkeys to jump to different location within a track (like number buttons on soundcloud website)

### ISSUE THREAD

**Issue by PEPZ** [Soundnode/soundnode-app#205]
It is only a request that I would love to have, as I am not a developer. Really loving this app. Great work and big thanks to Weblancaster and others developing!

**Comment by weblancaster** [comment]
thanks @PEPZ it will be implemented in the next version

**Comment by PEPZ** [comment]
@weblancaster @jakejarrett How does the feature work now? Numbers do not seem to work.The app is amazing, guys! Using it all the time! :))

**Comment by weblancaster** [comment]
@PEPZ this was not implemented or added to the roadmap.. we will need to wait to see.

**Comment by Pitros** [comment]
As far as I know it's not implemented.
