### ISSUE TITLE
[FEATURE] Minor UI change

### ISSUE THREAD

**Issue by nofont** [Soundnode/soundnode-app#207]
I've been using Soundnode for a while now and I love it. One suggestion that I have is to provide a track-listiong with smaller covers for better overview. 

![track_listing](https://cloud.githubusercontent.com/assets/164717/6017513/c79f992a-ab8e-11e4-8615-fcc775ea53fd.jpg)

**Comment by xbenjii** [comment]
Possibly in the form of a slider in the top right, which allows you to change the size?

**Comment by nofont** [comment]
Yes, that would be lovely. Or simpler; toggle between two versions "Large"/"Small"

**Comment by weblancaster** [comment]
thanks for the feedback @nofont @xbenjii 

And yeah I think a toggle button to change between the versions is a good idea.. I will work on this as soon I get q chance.

**Comment by gerardvcruz** [comment]
I'm going to try and take this on over the weekend. I'm thinking of having a large album art, small album art and list view buttons for displaying tracks. This is my first time working with an NW.js project and I'm loving it so far.

**Comment by weblancaster** [comment]
Cool.. feel free @gerardvcruz 

Thanks
