### ISSUE TITLE
[FEATURE REQUEST] - Mini Player

### ISSUE THREAD

**Issue by GetKoolaid** [Soundnode/soundnode-app#209]
I would LOVE a mini-player released. For example the Zune player goes from this

http://i.imgur.com/TYPDVBC.jpg

to this

http://i.imgur.com/sot6dp6.jpg

with it's mini player. 

I'd love to have this function because not only is it nice to just not have it take up all of my monitor, but I can also screengrab it to show music playing information to my stream.

It's actually pretty close to having a mini-player already, just make an option to hide all the information to the right of the controls, and maybe shrink it down a bit more. Like this http://i.imgur.com/RGsultq.jpg

**Comment by weblancaster** [comment]
@GetKoolaid this is a great idea/feedback.. it will be done for sure.

But since this is a relatively big timing effort.. this will take a while to be released.

Thanks.

**Comment by jakejarrett** [comment]
You could do this by making a design for when it's smaller than 768px?

EG/

```css
@media (max-width: 768px) {
    .content-that-would-not-be-displayed {
        display: none;
    }
}
```

This would allow it to be done in less time.

**Comment by weblancaster** [comment]
Yes I can do that @jakejarrett but we don't want to hide things but adapt and make responsive for smaller view.

**Comment by RainbowDashDC** [comment]
I can see where you coming from from a responsive view @weblancaster but it seems like it would make more sense to use @media in this scenario as your targeting a specific size in a specific case.

**Comment by weblancaster** [comment]
That's the idea @RainbowDashDC I'm going to try start work on this in the next days and I might have something by next week.

**Comment by weblancaster** [comment]
As per initial goals of Soundnode in supporting desktop with major features.. that being said mini player won't be supported.
