### ISSUE TITLE
Uncaught node.js error when switching through tracks

### ISSUE THREAD

**Issue by davidcornu** [Soundnode/soundnode-app#210]
While switching through a few tracks using the next/previous buttons on the bottom left, I was presented with the following error message:

![screen shot 2015-02-04 at 1 31 07 pm](https://cloud.githubusercontent.com/assets/325821/6046646/15b2ab00-ac72-11e4-991b-541c0ce57bba.png)

**Comment by weblancaster** [comment]
@davidcornu I'm going to take a look on that.
