### ISSUE TITLE
Window can't be moved or resized when in SoundCloud OAuth flow

### ISSUE THREAD

**Issue by davidcornu** [Soundnode/soundnode-app#211]
When launching the app, it opens SoundCloud's OAuth page so the user can log in. However, in that state the window can't be moved or resized.

**Comment by weblancaster** [comment]
I'm aware on that "issue" but no solution yet..

**Comment by davidcornu** [comment]
Are you open to pull-requests? I believe node-webkit's [`gui.Window.open`](https://github.com/nwjs/nw.js/wiki/Window#openurl-options) will let you give the new window a native top bar and set it's size.

**Comment by weblancaster** [comment]
Of course @davidcornu :) 

Just take a look at https://github.com/Soundnode/soundnode-app/blob/master/CONTRIBUTING.md you don't need to follow everything but just make sure to test and follow a good software design

**Comment by weblancaster** [comment]
Hey @davidcornu I have a quick idea I can work on.. if you are not working on this I can try fix it this weekend.

**Comment by davidcornu** [comment]
@weblancaster I've started messing around with it but haven't quite figured out how to do the [verification ](https://github.com/Soundnode/soundnode-app/blob/master/app/public/js/system/core.js#L336-L367).

**Comment by weblancaster** [comment]
@davidcornu can you let me know how you are doing this? you could clone and push to your clone repo the fix and then I would take a look to see if I can help you with anything.
