### ISSUE TITLE
Minimum window size is too big

### ISSUE THREAD

**Issue by davidcornu** [Soundnode/soundnode-app#212]
I'd love the ability to make the window smaller than the current minimum size of [1152&times;755px](https://github.com/Soundnode/soundnode-app/blob/16cc3ebc155f5b50005f7c151b7f0de7e336ba21/app/package.json#L18-L19) (which is quite large on a laptop).

**Comment by weblancaster** [comment]
I agree. This will be addressed @davidcornu

**Comment by weblancaster** [comment]
Hey @davidcornu enable to make the window smaller although I'm working on a feature to actually support a very small view of the App. thanks.

**Comment by davidcornu** [comment]
:tada:
