### ISSUE TITLE
Remove binaries and catched version of nw from git

### ISSUE THREAD

**Issue by RainbowDashDC** [Soundnode/soundnode-app#224]
I love the project, and the use of nw.js (my favourite to ever exist), but I'm not a huge fan of having nw binaries and ffmpeg be included statically in the repo. Then again binaries in a source repo have always bugged me, might I suggest you use a grunt task to fetch nw.js much like what atom-editor does with their nw like system. NW.js ships the ffmpeg version so it would be feasible to have a grunt hook to do so.

Then you could use github releases for the "final" versions.

Once again, great work.

**Comment by weblancaster** [comment]
Thanks for the feedback @RainbowDashDC I appreciate that.

I might work on that soon to clean up the binaries from the repo.
