### ISSUE TITLE
Mac - Window goes white/blank and nothing loads once signed into Google

### ISSUE THREAD

**Issue by niftylettuce** [Soundnode/soundnode-app#225]

**Comment by jakejarrett** [comment]
What version of OSX are you using?

If you can open the console (CMD+/ i think?), are there any errors?

Also, it could be that the window didn't disappear, After logging in Try pressing Control + Down Arrow and you might see 2 open windows, Go to the dark window.

**Comment by weblancaster** [comment]
I have seen this before and it looks like is something related to the user account and Soundcloud not being able to authenticate.

Can you try again @niftylettuce or even with Facebook please.

thanks

**Comment by MichielDeMey** [comment]
I had the same issue.

Tried logging in through Google, gave me a white screen.
Then restarted and logged in through Facebook, that worked for me.

**Comment by weblancaster** [comment]
So yeah this is probably a issue with Soundcloud connecting with Google accounts.

**Comment by anubiann00b** [comment]
I'm having the same issue on Windows.

**Comment by RampageJack21** [comment]
also having this issue on windows.  Soundcloud has no problem signing into my google account while using Chrome or Firefox.  Any plans to get this working?  I created my soundcloud account via google and i dont have facebook...is there any work-a-round given my situation?

**Comment by anubiann00b** [comment]
Also, you don't need an account to listen to music on the site. I don't know if the APIs allow for unregistered music access (I'm guessing they don't), but if they do, login probably shouldn't be mandatory.

**Comment by RampageJack21** [comment]
got around it by changing my password on soundcloud.com while I was signed in with my google account.  Now I use my gmail address explicitly (before it was a click of a button) and the new unique password to login via browser and the soundnode app.  Works fine and no awful facebook needed :)

**Comment by weblancaster** [comment]
Great thanks for posting your workaround @RampageJack21
