### ISSUE TITLE
[FEATURE SUGGESTION] Shuffle

### ISSUE THREAD

**Issue by MrProtagonist** [Soundnode/soundnode-app#226]
Title says it all. This app would be PERFECT if you could shuffle a playlist.

Great work by the way guys!

**Comment by jakejarrett** [comment]
I'll look into how to implement shuffle. I would personally use this feature. (Playlist, Stream & Profile)

**Comment by weblancaster** [comment]
Hey @jakejarrett I'm changing how Soundnode play songs/works and this is going to be implemented with that change.

**Comment by jakejarrett** [comment]
@weblancaster Haha no worries, i had concerns it would require changes to how the playback is handled.
