### ISSUE TITLE
Adding new core team members

### ISSUE THREAD

**Issue by weblancaster** [Soundnode/soundnode-app#230]
@MichielDeMey and @jakejarrett I invited you guys to be part of Soundnode app core team..

This will be valid until you guys continue to contribute to the project (no need to work on everyday/crazy stuff)

I started the project with two very clear goals.

**1. Soundnode app must be simple to use (as a user standpoint)**
**2. Soundnode app must be easy to understand and contribute (as a developer/contributor standpoint)**

Therefore I ask you guys to always ask the questions

*Is this feature/fix/whatever improve user experience? or improvement code base and keep simple?*

Thanks and congrats!

**Comment by MichielDeMey** [comment]
Thanks @weblancaster, I'll do my best to continue to contribute to this fine project.
I'll be eagerly awaiting the invitation.

**Comment by MichielDeMey** [comment]
Don't forget to add the Core Team group to the relevant repos as well, otherwise we won't be able to contribute to the repos. ;)

**Comment by jakejarrett** [comment]
Thank you @weblancaster!

I will contribute as much as possible.

**Comment by weblancaster** [comment]
Guys @MichielDeMey @jakejarrett no need to spend all day working on this.. just when you feel like.
