### ISSUE TITLE
Album Art Doesn't Display in Notification Window

### ISSUE THREAD

**Issue by ianstrasser** [Soundnode/soundnode-app#233]
Instead, the icon for the app I downloaded before this appears.

**Comment by jakejarrett** [comment]
Which OS are you using?

**Comment by ianstrasser** [comment]
OSX 10.10.2

**Comment by jakejarrett** [comment]
From my testing (10.10.3) I can see the notifications fine.

Can you see any errors in the console log (In the Application menu, Go to ```Help -> Developer Tools ``` then There should be a Console tab on the far right. Paste any errors)

**Comment by ianstrasser** [comment]
No error's related to the notifications. I deleted, and then downloaded the latest stable build (I probably should have tried that first).

It's working now. Thanks for confirming that it was working with you.
