### ISSUE TITLE
[Feature] Add Support for Gamepads

### ISSUE THREAD

**Issue by jakejarrett** [Soundnode/soundnode-app#235]
With an updated version of nwjs, We should be able to support gamepads pretty easily.

The feature is still a draft, But Simple support (Bumper to skip Song, trigger to skip forward/back in the song?) should be fairly easy.

From my testing, It seems to work good enough for what we could do with it (I can't say non-xbox 360 controllers are well supported.)

# References
* [W3C Draft](https://w3c.github.io/gamepad/gamepad.html)
* [Mozilla Developer Network](https://developer.mozilla.org/en-US/docs/Web/Guide/API/Gamepad)
* [Internet Explorer Dev Center](https://msdn.microsoft.com/en-us/library/ie/dn753843%28v=vs.85%29.aspx)

**Comment by weblancaster** [comment]
@jakejarrett not sure if this is going to be useful/helpful for the users.

**Comment by jakejarrett** [comment]
@weblancaster The main benefit would be where someone would be using their controller primarily (EG/ Sitting in the lounge with the laptop plugged in?) for interaction.

Although, I agree it may not be very useful/helpful in most circumstances, It is a fairly niche use case.
