### ISSUE TITLE
Copy & Paste not working?

### ISSUE THREAD

**Issue by anselmh** [Soundnode/soundnode-app#238]
Hey, I tested the app yesterday but figured that copy & paste is not possible (at least during login)? This is essential to me as I’m not going to type my password manually when characters are hidden as well, usually using my password manager to handle all that.
Would it be possible to enable this? I’m on OS X 10.10 (latest).

**Comment by jakejarrett** [comment]
I noticed this on OS X along with some other bugs with the menu bar, I should be able to have a fix by this weekend.

**Comment by anselmh** [comment]
Ah, cool! :)

**Comment by weblancaster** [comment]
#239 closes this issue.

Thanks @jakejarrett for fixing and thanks @anselmh for reporting.
