### ISSUE TITLE
Media Keyboard support

### ISSUE THREAD

**Issue by veridicis** [Soundnode/soundnode-app#241]
Hi,
I see that media keys are supported but they do not work with my Logitech K520.
Any idea?

PS: love the app

**Comment by jakejarrett** [comment]
Which OS are you using & do the keys work normally on all other apps?

**Comment by veridicis** [comment]
Running on 8.1, media keys work with Media Player, Spotify...

Sent from Outlook

    _____________________________

**Comment by weblancaster** [comment]
Yeah Windows are having issues with the NW.js on media keys.. I'm waiting for an update so I can update the core and hopefully fix the issue @veridicis @jakejarrett

**Comment by Scarwolf** [comment]
SoundNode Media-Keys are working perfectly fine on both, my Logitech G15 Keyboard aswell as my Logitech G700S Mouse. Are you sure you had no other application running which could block the media keys for other applications?

**Comment by weblancaster** [comment]
@Scarwolf good catch.. I forgot to mention that :/ @veridicis

**Comment by veridicis** [comment]
Just tested, nothing hidden in the background that might capture the keys.

**Comment by ninjaonsafari** [comment]
Im running in the same issue... 
When the focus is set to chrome it works perfectly but not when i focused visual studio or internet explorer. 
It works with spotify and i dont think someone else is catching the events...
Do you need more info?

thanks for the app!!
