### ISSUE TITLE
What about Soundnode in Material Design?

### ISSUE THREAD

**Issue by Scarwolf** [Soundnode/soundnode-app#242]
Hi folks!

I am very interested in SoundNode and as I am currently working on some projects using www.materializecss.com Framework, I would like to know your opinion on whether Soundnode would look good in Material Design.

I am interested in contributing this, but since I have not worked with Node.JS etc pp. yet I need to look this up first.

**Comment by weblancaster** [comment]
Hey @Scarwolf feel free to change something and send as a new branch and send something so we can check how it's starting to look.. take a look at  #160

**Comment by weblancaster** [comment]
I'm up for to see a new face for Soundnode app.

**Comment by Scarwolf** [comment]
I am not familiar with Node.js and so on, I tried compiling the actual source of soundnode to an exe using Web2Exe, but It seems like there aren't any stylesheets included in the Exe, aswell as the file is up to 240MB big, do you have a tutorial for compiling this how it should be compiled?

**Comment by weblancaster** [comment]
@Scarwolf https://github.com/Soundnode/soundnode-app/wiki/Development

To build the executables you just need to run `grunt build` everything will be generated automatically and saved inside the dist folder

**Comment by jakejarrett** [comment]
@Scarwolf If you have nodejs installed, cd into the soundnode-app folder & run this command
``` npm install ``` *and (i think)* ```npm install -g grunt```

**Comment by Scarwolf** [comment]
Sorry guys, but have some problems, can anyone help me? http://i.imgur.com/hN5Pk1C.png

**Comment by weblancaster** [comment]
Hey @Scarwolf 

Now you have `node` and `grunt` installed

You won't need to run node. Ever.. just `grunt watch` to watch your changes in the SASS files.

In your case though you will need to run in development mode.. so take a look at this page https://github.com/nwjs/nw.js/wiki/Debugging-with-Sublime-Text-2-and-3 

You will add the command for windows on your sublime text.. then after added the command to your ST you just need to open index.html and build with ST

**Comment by Scarwolf** [comment]
Uhm, do I need ST for this in general? I am using JetBrains PHPStorm as my main IDE.

**Comment by jakejarrett** [comment]
You don't need st for it, but it's an easier overall flow.

You should be fine using any IDE, I use atom & simply ran ```npm install nw``` along with appending this to the package.json (after main, but it should be fine anywhere)
```
"scripts": {
  "start": "nw"
},
```

and that allows me to run it from terminal/command prompt with ```npm start```

<b>NOTE: Don't use this if you have low bandwidth, The nw package is 123MB on linux</b>

**Comment by weblancaster** [comment]
@Scarwolf since you are using PHPStorm.. check if you have node or NW.js (Node-Webkit) support.. 
I use IntelliJ and has support for NW.js (Node-webkit)
