### ISSUE TITLE
UI redesign

### ISSUE THREAD

**Issue by Pitros** [Soundnode/soundnode-app#246]
I'm currently playing with Soundnode design, change list is getting longer and longer. 
It contains many UI changes as well as couple fixes.

* Changed font to Open Sans;
* Link color made a bit lighter for better contrast;
* Changed size of aside elements;
* Aside links have now 5px padding instead of 10px margin (easier to click);
* All font awesome icons have the same color as links;
* Font awesome icons are changing colors with text;
* Removed transition on <a> elements;
* Cleaned window action buttons css;
* Vertical slider for content moved to main view;
* Changed all header font-weight to 600;
* Main h1 font-weight is now 300;
* Changed "Following:" to "Following" to fit other titles;
* Updated infinite-scroll to latest version (required to track offset position in container, there seems to be some kind of bug with infinite-scroll-disabled but loadMore checks if it's "busy" so I just simply removed it for now);
* Fixed not visible avatar in profile view;
* Redesigned player view;

Still on my TODO is to make window action buttons on Windows look in proper style and align them to right.

Here's actual screenshot:
![image](https://cloud.githubusercontent.com/assets/6910670/7818263/e3f153c6-03da-11e5-8710-19268f2e3e46.png)

Any critique or suggestion are appreciated.

**Comment by jakejarrett** [comment]
The Control buttons for close/min/max could have some improvements to stand out more (EG/ the OS X Traffic Lights.)
![screen shot 2015-05-27 at 10 59 52 am](https://cloud.githubusercontent.com/assets/5661105/7826590/8a442b70-045f-11e5-9dbb-06daabdcd456.png)

**Comment by weblancaster** [comment]
@Pitros Awesome! I really appreciate this work.

Just some points to go through.

- Why did you remove transitions in the elements?
- Can you split the work between your `re-design` and the `Updated infinite-scroll` please?

Thanks a lot.

**Comment by Pitros** [comment]
Transitions on <a> tags looked really "heavy" for me, faster transition probably will be good as well but I haven't tried that yet.

I've splitted changes into two branches in my fork.

[soundnode-app/redesign](https://github.com/Pitros/soundnode-app/tree/redesign)
[soundnode-app/updated-infinite-scroll](https://github.com/Pitros/soundnode-app/tree/updated-infinite-scroll)

**Comment by weblancaster** [comment]
That's great thanks @Pitros 

Looks good to me.. let just keep the transitions though.. you can speed up the transition delay to look lighter.

**Comment by weblancaster** [comment]
Hey @Pitros any chance to know when we can get this improvements? I'm going to release a new version soon and would be nice to have your changes on it.

**Comment by Pitros** [comment]
I had some other things to do this week, and I'm going to work on it right now. Some other small improvements and I will make pull request today/tommorow (depends on changes and timezone)

**Comment by weblancaster** [comment]
No problems @Pitros I thought you were done but no PR.. No rush then.

**Comment by Pitros** [comment]
Two pull requests are ready to review.

About that window buttons for windows... I came up with new directive and got weird problem.
```javascript
<action-buttons class="windowsActionButtons" ng-if="process.platform != 'win32'" os="Windows"></action-buttons>
```
Angular ng-if doesn't work as it should - `process.platform == 'win32` returns true however it doesn't work. I dont know what would happen on Mac, so I'll be glad if you would check which buttons will be displayed.

https://github.com/Pitros/soundnode-app/tree/actionButtons
There's bug which occurs only without redesign branch - left and right chevron disappears.

**Comment by rafaell-lycan** [comment]
@Pitros if you want some help in this new UI, I could help without problem. =)

**Comment by weblancaster** [comment]
@rafaell-lycan this work was separated in PR which some was merged in master already..

Now I just need to get some time to review #254 on Windows (which is a bit more work for me since I use Mac)
