### ISSUE TITLE
Soundtracks UI improvement

### ISSUE THREAD

**Issue by weblancaster** [Soundnode/soundnode-app#249]
As per #248 we do need to find a better way for users to go through the soundtracks, need to keep in mind how player works for any change in the UI.

Ideas:
- Reduce soundtracks thumbnails/info
- Add pagination (this would need work on the player to update)

**Comment by dntrkv** [comment]
(assuming I should continue discussion in this issue)

I just tried the playlist functionality and the way you have the track list display there is much better in my opinion. I think it would be useful to add a button that switched from the tile view that we currently see in the likes to a list view like in the playlists, kind of how the Soundcloud web app does it.
