### ISSUE TITLE
Add forum platform

### ISSUE THREAD

**Issue by weblancaster** [Soundnode/soundnode-app#250]
Add forum platform to make easier to users to contribute with ideas, suggestions and questions.

Options:
- https://www.nodebb.org/
- http://www.discourse.org/

**Comment by rafaell-lycan** [comment]
I think Discourse it's much better in this case. We need to review other possibilities but, I've used this platform in my last job and for my is really good.

**Comment by weblancaster** [comment]
Yeah Discourse seem the go to choice.. but I'm leaning towards nodebb to keep the whole Soundnode "eco-system" in Javascript.

**Comment by Pitros** [comment]
Any of these will be ok, but nodebb looks really nice for me.

Anyway something like trello.com would be good as well. Currently there's no TODO list and there are many open issues. It seems to be a good way to organise whole thing, and let people know if someone is fixing something or trying to add another feature.

**Comment by weblancaster** [comment]
@Pitros the issues are used as TODO's although the core team can add labels to find easier to organize.

**Comment by jakejarrett** [comment]
+1 for NodeBB.

Also, with TODO/FIXME's we could look at using something like [grunt-todo](https://www.npmjs.com/package/grunt-todo) script during the dev process to find a todo/fixme comment?

**Comment by weblancaster** [comment]
looks like this won't happen.
