### ISSUE TITLE
Some Ideas + 1 Bug

### ISSUE THREAD

**Issue by Scarwolf** [Soundnode/soundnode-app#255]
1. Double Click Navigation Bar to maximize
2. Double click playlist or "Likes" to automatically play the first song
3. Instead of the Node-logo, generate a picture containing the artist and the name of a song if a track doesn't have a custom cover
4. Ability tho chose whether the player itself should be shown in the sidebar or in the footer. (like this: http://i.pottii.de/4c9l50i.png)

-----
Bug:
1. When starting soundnode, the remaining time of a song is shown as "0" when no track has been selected yet.

**Comment by jakejarrett** [comment]
I've messed around with the idea of double clicking to maximize, it's fairly easy to implement. Some example code below if you wanted to implement it.

```js
document.getElementsByTagName('header').addEventListener('dblclick', function(){
  require('nw.gui').Window.get.maximize();
}, false);
```
