### ISSUE TITLE
On start Soundnode window resize (keep in cache)

### ISSUE THREAD

**Issue by Chriz007** [Soundnode/soundnode-app#256]
I have been a long time user of soundnode and I love it. One minor annoyance everytime I open it up is that it looks like this:

![screen shot 2015-06-21 at 12 20 04 pm](https://cloud.githubusercontent.com/assets/12990919/8273037/b5b53014-1810-11e5-90d5-ec2e782aa612.png)

As you can see the dock is covering up the sound controls, which happens happens everytime I open the app, regardless whether I have resized it or not. It always reverts back to its original position.

![screen shot 2015-06-21 at 12 20 52 pm](https://cloud.githubusercontent.com/assets/12990919/8273039/dd7dccb4-1810-11e5-85b9-74fae1cb19d0.png)

If someone could fix this minor annoyance, that would be fantastic! I'm not good at coding whatsoever, but if I could, I would definitely help you out. Thanks for version 5.5. Amazing new interface

**Comment by Pitros** [comment]
There are two possible solutions: resize it for everyone (pakage.json file) or use localStorage to store user width and height of resized window. At [nw.js wiki](https://github.com/nwjs/nw.js/wiki/Preserve-window-state-between-sessions) there is already a worth looking solution.

I'm glad you like changed interface :)

**Comment by Chriz007** [comment]
I'm sorry haha, but I'd rather leave it up to someone with more knowledge on how to do this. I definitely would though! Trust me. But I'm an absolute noob when it comes to this.

**Comment by jakejarrett** [comment]
:+1: for saving to localStorage. Maybe use sessionStorage instead of variables and then save sessionStorage to localStorage on exit?

**Comment by weblancaster** [comment]
Thanks for the feedback @Chriz007 we appreciate that.

I like the idea @jakejarrett let's implement that as new enhancement.

**Comment by Pitros** [comment]
@jakejarrett saving on exit will not work when app crashes or system shuts down as well it requires more work (both sessionStorage and localStorage while there's no difference in performance).
