### ISSUE TITLE
[FEATURE] View Queue / What's playing next

### ISSUE THREAD

**Issue by jakejarrett** [Soundnode/soundnode-app#257]
Personally, I'd like the ability to click the current Song/Artwork in the bottom and have a Menu show up with what songs are currently Queued.

So if I were to navigate away from the current page, I could see what's queued & skip forward in the queue without navigating back to that page.

iTunes & Gnome Music have this feature & would be a great addition to Soundnode.
![iTunes](https://support.apple.com/library/APPLE/APPLECARE_ALLGEOS/Product_Help/en_US/PUBLIC_USERS/PP203/S0027_UpNext.png) ![Gnome Music](http://www.omgubuntu.co.uk/wp-content/uploads/2015/06/gnome-music-3-18-750x415.jpg)

**Comment by weblancaster** [comment]
Hey @jakejarrett yeah this would be much better.

We can work on this after I start/finish how the new queue will work.. I'm planing to work on this in the next days.
