### ISSUE TITLE
Add ability to like track from Player controls bar

### ISSUE THREAD

**Issue by weblancaster** [Soundnode/soundnode-app#259]

**Comment by Chriz007** [comment]
Cool, but where exactly would you put it?

**Comment by weblancaster** [comment]
@Chriz007  This will work the same way when clicked in the `heart` icon.. will add the song to your `likes` view that way if you don't need to know nor find where the song is playing in the current view.

**Comment by Pitros** [comment]
I'll probably make that in next days. Two days of using Soundnode (I'm still mostly SC web for playing songs ;D) and that really annoys me.

**Comment by eigenstil** [comment]
@Chriz007 I would suggest to put it beneath the artist name to make it consistent with the stream view, as mentioned in issue #417 (this is just a mockup):
![mockup-icon-bar](https://cloud.githubusercontent.com/assets/13272281/10690199/74af2d46-7980-11e5-9b68-fed4bc6c7cf1.jpg)

**Comment by Pitros** [comment]
Three icons? That's too much, like button only will be enough. Other buttons are visible in playlist view or on track page.

**Comment by eigenstil** [comment]
Well, if I want to perform an action on the currently playing song, there is no reason to pull the UI into pieces and make it incosistent with what the user is already used to from the stream view.

From a UX/UI design persepective I would highly recommend to re-use the appearence of these buttons.

**Comment by weblancaster** [comment]
For now I have added just the like button as per this issue.

**Comment by weblancaster** [comment]
This is now released.
