### ISSUE TITLE
Seems to be no support for speaker fill / surround

### ISSUE THREAD

**Issue by Collussus** [Soundnode/soundnode-app#261]
Hey there,

Running soundnode with a 5.1 surround set, I'm getting 0 sound from my rear speakers.

I know this is likely a html5 issue, as with chrome i had to specifically add "--disable-audio-output-resampler --try-supported-channel-layouts" to the target of the application to disable upfiltering.

I suspect the same issue is the case here, is there any way to fix this?

Edit: Noticed that creating a shortcut and doing the same for soundnode fixes it for soundnode too, might be an idea to add a configuration option to do this automatically?

**Comment by Pitros** [comment]
It's probably some kind of chromium (nw.js) bug and we probably won't be able do anything with it. Only way to fix it can be adding [chromium arguments](https://github.com/nwjs/nw.js/wiki/Manifest-format#chromium-args) to package.json. 

Anyway, right solution for you might be turning on `speaker fill` in speaker settings, which should fix this problem in every application.

**Comment by Collussus** [comment]
That's the thing. Speaker fill IS on. As i stated above, the only way for me to fix it currently is by adding the launch arguments.
