### ISSUE TITLE
Change Sound Device Output

### ISSUE THREAD

**Issue by QlimaXia** [Soundnode/soundnode-app#262]
Is there a way to change Sound Device Output?
If not then just delete or tell me why

**Comment by weblancaster** [comment]
So far there no way yet @QlimaXia 

Any suggestion?

**Comment by Pitros** [comment]
There's an API in development, current status: https://www.chromestatus.com/feature/4621603249848320. 
Meanwhile latest version of chromium in nw.js is 43.

**Comment by Pitros** [comment]
Quick update: On latest NW.js (0.13-beta2) and Electron.js it could be done - I've tested demo page and it works fine, but still it's hidden behind flag.

**Comment by Bluscream** [comment]
Any news on this?
I would like to route it into VirtualDJ through VAC.

**Comment by Pitros** [comment]
We're still on old nw.js, so nothing changed. 

I tried updating nw.js to latest version which would allow that, but there's some kind of minor `window` bug and authentication won't work.

**Comment by Gurkengewuerz** [comment]
Still working on this feature?

**Comment by Pitros** [comment]
@Gurkengewuerz I still cant get authentication working so no progress at this point (cant upgrade to newer version of nw.js), but I also want that feature, so someday it will be avaliable.
