### ISSUE TITLE
Tooltip for long song titles

### ISSUE THREAD

**Issue by Chriz007** [Soundnode/soundnode-app#263]
The song titles you see in this picture are longer than what the app shows/allows, so I'm suggesting an implementation of a tooltip or something so we can see the entire title when we hover over it.

![soundnode](https://cloud.githubusercontent.com/assets/12990919/8402338/abed22d2-1def-11e5-8f11-5d804ca2d062.png)

**Comment by weblancaster** [comment]
@Chriz007 this is done. thanks for the feedback
