### ISSUE TITLE
I got this error. Help?

### ISSUE THREAD

**Issue by Chriz007** [Soundnode/soundnode-app#266]
Um.. what does this error mean? The app wouldn't let me play my music so when I tried to click  anywhere on the track, this popped up
![screen shot 2015-07-01 at 10 22 14 pm](https://cloud.githubusercontent.com/assets/12990919/8470412/bafb9db0-203f-11e5-864d-bd93a14839d9.png)

**Comment by corvus** [comment]
same here :/

**Comment by Pitros** [comment]
We've hit daily limit. 
```json
{
  "errors":[
    {
      "meta":{
        "rate_limit":{
          "bucket":"by-client",
          "max_nr_of_requests":450000,
          "time_window":"PT24H",
          "group":"plays"
        },
        "remaining_requests":0,
        "reset_time":"2015/07/02 13:33:58 +0000"
      }
    }
  ]
}
```

SoundCloud devs implemented [Rate Limits](https://developers.soundcloud.com/docs/api/rate-limits) on June 16th, and it affects Soundnode directly. Currently there's no way to increase this limit, and many 3rd party SC apps are literally dying. 
https://developers.soundcloud.com/blog/limits

**Comment by corvus** [comment]
i think the best would be to be able to use own api credentials. so a user can have his own limit and new users can use the app directly with "included" one. the php script for authentication is not that complicated to install and free hosters are everywhere :)

**Comment by weblancaster** [comment]
Thanks for reporting that @Chriz007 and thanks for answering why that happen @Pitros 

For now we pretty much depend on Soundcloud so we need to figure out a way or just leave it be.

**Comment by Chriz007** [comment]
Ah.. makes sense. I tried logging into soundcloud and playing one of the song and it worked. Hopefully it doesn't happen again soon. So does that mean all the users combined using this app have a collective limit (15K) before the app basically shuts off on them until the reset? ..Do you have any statistics on how many people downloaded this app and how many songs are being played?

**Comment by weblancaster** [comment]
@Chriz007 more than 13k downloaded the app.. not everybody use though.

The rate limit is due in 24hs.. so if Soundnode users (combined) hit 15k plays.. the App is disable to play songs until 24hs later.

**Comment by Pitros** [comment]
We can bypass it in two ways:
One, we might give user an option to enter their own app client ID to play songs - that would be really easy and all problems will be gone for now.
Two - do something like a database with couple client IDs (10 accs gives us ability to play 150k songs per day which is enough).
IMHO the best way to do it would be implementing both options - new users will use client IDs from database, and after trying app/listening to XX songs, a popup will appear with details, how to get their own client ID (it takes less than minute) to not use all limit on public ones..

**Comment by weblancaster** [comment]
I like the second idea a lot @Pitros let sit on it for while

**Comment by weblancaster** [comment]
This should be fixed with #275

**Comment by Pitros** [comment]
@weblancaster meanwhile app still works, but there's a form for higher API usage.

Source: https://twitter.com/SoundCloudDev/status/628582517889728512
https://docs.google.com/forms/d/16Vs0Ikv2HqH8UJPGmX5kF2Wy4Rx_qMpgDrL39ACJKyE/viewform

You might want to look at this one.

**Comment by Chriz007** [comment]
Wow, this should be useful.
