### ISSUE TITLE
[FEATURE] Typeahead / Autocomplete Search

### ISSUE THREAD

**Issue by jakejarrett** [Soundnode/soundnode-app#268]
Basic support for a Autocomplete/Typeahead system when searching could be beneficial.

It could have a system where it shows an artist you're following as the first listing, Similar to Soundcloud's website?

![screenshot from 2015-07-03 16-19-11](https://cloud.githubusercontent.com/assets/5661105/8493562/521418e8-219f-11e5-97c4-c4a8388f3b17.png)

**Comment by weblancaster** [comment]
@jakejarrett that would be very cool
