### ISSUE TITLE
Uncaught node.js Error when playing specific song

### ISSUE THREAD

**Issue by sumyunggui** [Soundnode/soundnode-app#269]
App crashes when playing specific song

App Version: 0.5.5
downloaded from website:  "http://www.soundnodeapp.com"  (downloaded 7/3/2015)
OS: Windows 7 64-bit

To reproduce:
- Open app
- Click to play song titled "Yellow Claw - #8"
- App appears to be loading for about 10 seconds,  then crashes with the error displayed below.

Possibly helpful items:
- song permanent link:  https://soundcloud.com/yellowclaw/yellow-claw-mixtape-8?client_id=342b8a7af638944906dcdb46f9d56d98
- This song was one of my 'Liked' songs.  
- The song plays as expected from a web browser

Text displayed in main window when error occurs:
Error: Failed to set the 'currentTime' property on 'HTMLMediaElement': The element's readyState is HAVE_NOTHING.
    at Error (native)
    at HTMLDivElement.<anonymous> (file:///C:/Users/XXXXX/AppData/Local/Temp/nw3432_28934/public/js/common/playerService.js:263:41)
    at HTMLDivElement.n.event.dispatch (file:///C:/Users/XXXXX/AppData/Local/Temp/nw3432_28934/public/js/vendor/jquery.min.js:3:6404)
    at HTMLDivElement.r.handle (file:///C:/Users/XXXXX/AppData/Local/Temp/nw3432_28934/public/js/vendor/jquery.min.js:3:3179)

**Comment by jakejarrett** [comment]
I can confirm this error does occur (Along with a few other tracks), Not sure why it responds with a 404
```
https://api.soundcloud.com/tracks/158876991/stream?client_id=342b8a7af638944906dcdb46f9d56d98
Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by weblancaster** [comment]
@sumyunggui @jakejarrett  This is related to Soundcloud rate limit

**Comment by weblancaster** [comment]
@sumyunggui @jakejarrett this was actually a bug when the can't play the track for some reason..

Should be fixed now. thanks.
