### ISSUE TITLE
[FEATURE] Allow users to choose between displaying time elapsed and time remaining; also display track duration

### ISSUE THREAD

**Issue by robertcapasso** [Soundnode/soundnode-app#273]
Currently the player only displays the time remaining for the playing track.  This is not very informative when you are listening to a long track and don't know the total duration offhand.  Either an option to flip the time display to time elapsed or a simple fixed display of total duration somewhere in the player area would be a really nice improvement on the current display.

**Comment by Chriz007** [comment]
Well, the track *does* show the duration of the song when you click on the track beneath the title..

**Comment by robertcapasso** [comment]
Sorry, I think I'm missing this..  Clicking on the track name in the player bar doesn't do anything for me.  I see duration in the grid of tracks but not on the player bar.  If I scroll away from the current track in the grid, there's no way to know how long the track is without scrolling back.  I've attached a screenshot. 

![image](https://cloud.githubusercontent.com/assets/4967386/8579899/50170afc-2585-11e5-9612-6e1e895d4cc8.png)

**Comment by Chriz007** [comment]
Oh ok. I see. You have a fair point

**Comment by weblancaster** [comment]
Latest update added improvements fixing this.
