### ISSUE TITLE
[FEATURE] Recommended tracks page

### ISSUE THREAD

**Issue by Chriz007** [Soundnode/soundnode-app#274]
Categories like "Hot", "Trending", "New".. 
And Genres such as:
<img width="186" alt="screen shot 2015-07-06 at 2 47 23 pm" src="https://cloud.githubusercontent.com/assets/12990919/8534066/fa0e0be4-23ed-11e5-90ea-b6bec0aaaa38.png"><img width="187" alt="screen shot 2015-07-06 at 2 48 38 pm" src="https://cloud.githubusercontent.com/assets/12990919/8534098/22d658ce-23ee-11e5-8dde-ccdb9c803508.png">

Although of course you don't have to put all of them in. Its just an example.

**Comment by jakejarrett** [comment]
Recommended tracks is available, but undocumented. [Which would not be in line with the terms of use](http://stackoverflow.com/questions/26388089/retrieving-the-recommended-playlist-via-api-call#comment41450304_26390142)

**Comment by Chriz007** [comment]
Hold up, what exactly are you talking about @jakejarrett ? 
["which would not be in line with the terms of use"] <-- What exactly does this mean?

**Comment by Pitros** [comment]
As one of SoundCloud alumnus (profile desc) said it might somehow violate terms of use of soundcloud API.
Anyway I haven't found anything about using not documented api calls, as well it's working for nearly a year so I think we can use it. 
BTW those api calls are probably for official mobile apps - recommended tracks were added recently, at least for Android so that's probably why it's not public.

**Comment by jakejarrett** [comment]
@Pitros @Chriz007 I'm not a lawyer, but i assume this snippet from xii. would prohibit us from using undocumented code.
`You must not, and must not permit any third party to, copy or adapt the object code, or reverse engineer, reverse assemble, decompile, modify or attempt to discover any source or object code of the SoundCloud® API`

**Comment by L3ice** [comment]
Now we have the "Top 50" Tab but still not the "New & hot" Tab 
I would really like to have this Tab too.

**Comment by weblancaster** [comment]
We have added a new version of top 50 @L3ice

**Comment by L3ice** [comment]
You mean that we can now change genre? @weblancaster

**Comment by weblancaster** [comment]
Yep @L3ice
