### ISSUE TITLE
Improve build process to make dist lighter

### ISSUE THREAD

**Issue by weblancaster** [Soundnode/soundnode-app#277]

**Comment by jakejarrett** [comment]
We could integrate grunt-uncss into the build process to remove any unused CSS when we build the app?

[addyosmani/grunt-uncss](https://github.com/addyosmani/grunt-uncss)

**Comment by weblancaster** [comment]
@jakejarrett I will work on some build improvements which will help.. I don't think uncss will help that much..

what I'm planning to do is to bundle things in 1 file because at the moment the built contains event the sass files.
