### ISSUE TITLE
[FEATURE] Switch for disabling/enabling auto play (continous play)

### ISSUE THREAD

**Issue by eigenstil** [Soundnode/soundnode-app#278]
I really would like to see a button which disables the auto play of the next song. Or can anyone tell me, where I can edit this in the code?

**Comment by weblancaster** [comment]
@eigenstil I'm working on some improvements on the Queue list when that's done.. your request will also be added.

**Comment by eigenstil** [comment]
Great – thanks for your feedback! really looking forward

**Comment by weblancaster** [comment]
Hey @eigenstil can you explain a bit better what do you want please.. Isn't this just a repeat track feature? if so it's added #292

**Comment by Chriz007** [comment]
@weblancaster I made a video explaining that http://sendvid.com/r6uqd9dd

**Comment by Chriz007** [comment]
This video is ALSO a perfect example. Pretend the link I sent you for the video is a track being played. Once its over, there is an option to have a repeat button on the bottom left corner. But in this case, we want it to be played automatically. Just like on another music player like iTunes.
<img width="75" alt="screen shot 2015-09-09 at 3 51 48 pm" src="https://cloud.githubusercontent.com/assets/12990919/9776204/dd6c4a6e-570a-11e5-8d87-6b83401317bc.png">

![itunes-12-shuffle-and-repeat](https://cloud.githubusercontent.com/assets/12990919/9776236/3bcbf5d2-570b-11e5-97e7-726f9e81f941.png)

**Comment by weblancaster** [comment]
Let's see what @eigenstil has to say @Chriz007

**Comment by Pitros** [comment]
He doesn't want repeat function, the option he wants looks like that:
He clicks on track A, track is being played and when it's finished next one let's say B is not being played automatically. As well track A is not being repeated, no sound is being played at all. 
Obviously he want to have an ability to enable or disable that option. 
There's no hidden magic. Really.

**Comment by eigenstil** [comment]
Yes, @Pitros and @Chriz007 this is exactly what I mean! If a track has played to the und, I dont want anything to happen: neither repeat nor the next track. Actually this is the standard behaviour of ALL music playing apps (iTunes, windows media player, VLC player, winamp etc. etc.).

SoundCloud built this feature into their site and I find this very annoying. Thus, I was searching for an alternative.

**Comment by weblancaster** [comment]
Ok @eigenstil we will implement that and release soon.

**Comment by weblancaster** [comment]
This was added. Will be available in the next release. thanks @eigenstil

**Comment by eigenstil** [comment]
Great, thanks! Really looking forward for the release
+4915771895665
von unterwegs gesendet
Am 10.09.2015 7:15 nachm. schrieb Michael Lancaster <notifications@github.com>:This was added. Will be available in the next release. thanks @eigenstil

**Comment by weblancaster** [comment]
Published the new version containing this issue

**Comment by eigenstil** [comment]
I just downloaded the newest windows-Version from the homepage via this link: http://goo.gl/Y46Hn8

But I'm not able to find the switch for disabling "auto-play of the next track". Where do I find this option? I clicked on the settings icon in the upper right, but this shows me only the "About" information.

Am I missing something or do I have to download something else?

**Comment by weblancaster** [comment]
it's the same repeat button.. one click for `repeat` then another click to `lock` (you will see the number 1) when enabled to not play next or prev

**Comment by eigenstil** [comment]
But then, this track is played over and over again - this is not what I was asking for.

I want the player to *STOP playing*, when the song is over! This is what @Pitros already stated in his comment: https://github.com/Soundnode/soundnode-app/issues/278#issuecomment-139076923

**Comment by weblancaster** [comment]
Yes, that's what is happening.. the song stop playing.

take a look at the screenshot.. look the icons with number 1 ( which says that it's going to play one time)..also look that the song is done.. no song is played or over again.

I said one click on the icon for `repeat` then if you click again you enter in the `lock` mode which doesn't play next or over.

<img width="1252" alt="screen shot 2015-09-17 at 2 04 32 pm" src="https://cloud.githubusercontent.com/assets/549394/9943162/5fb87962-5d45-11e5-983b-b6ad295a9abc.png">

**Comment by eigenstil** [comment]
Well – you are totally right. It stopps playing when the "1" is activated - I'm sorry.

*BUT:* I did not try this because the UI is totally confusing. In all other players that I know (VLC, winamp, itunes, windows media player), the small "1" next to the button means, that repeat is activated, and only one song (e.g. the already playing song) is repeating.

The better solution for the UI would be to have a switch/checkbox/etc. in the options in the upper right, to just toggle "continous play" (or whatever one may call it), which is the standard behaviour in the app. This way probably 90% of the users who are not like me (who wants only one single track to play), won't get confused by the UI ;-)

**Comment by Pitros** [comment]
@weblancaster Yep that's true, that small 1 from UI/UX side is totally bad. I only know what it mean because I'm checking all issues and PRs. But in most players it would mean 
a) track is going to repeated once then playback continues
b) every track is being repeated before next track will be played
IMHO that needs to be changed.

**Comment by weblancaster** [comment]
I opened a issue #374
