### ISSUE TITLE
[FEATURE] Option to repost tracks & show other reposted tracks from artists

### ISSUE THREAD

**Issue by Chriz007** [Soundnode/soundnode-app#291]
Just a little icon to distinguish between reposted tracks, and tracks from artists you have followed.

Also, an option to repost a track that you like, so you can share with others

**Comment by theaccordance** [comment]
Looks like the call is a PUT to endpoint /me/track_reposts/{{songId}}

Header URL from the repost event I triggered in their web app:
```
https://api.soundcloud.com/e1/me/track_reposts/224059861?client_id=<redacted>&app_version=f3cc0b3
```

hopefully soundcloud has exposed the endpoint to external apps?

**Comment by weblancaster** [comment]
@Chriz007 and @theaccordance I'm going to take a look on it this weekend.. thanks.

**Comment by Skkiz** [comment]
This is such a good idea @Chriz007! I hope either @weblancaster or @jakejarrett or can look into getting this implementing soon! I hate not knowing who reposted what, and it often annoys the living hell out of me when I see a whole buttload of reposts by many of the artists I follow. But that's a different issue! 

Oh and do you guys think its possible to detect duplicate reposts on the stream and "disable" them from reappearing on the stream again? I think some people would appreciate this feature. This could also probably be added as an option on the settings page.

**Comment by mradionov** [comment]
@weblancaster , are you working on this issue or I could take it?

@Skkiz , fix for duplicate tracks in stream has been merged in master recently, but without an options on the settings page for now. See related issue: https://github.com/Soundnode/soundnode-app/issues/364

**Comment by weblancaster** [comment]
@mradionov you can take it... I haven't look at this one yet. thanks

**Comment by mradionov** [comment]
After a bit of research seems that reposts are not supported by public API yet. Issue https://github.com/Soundnode/soundnode-app/pull/340 has some discussion about it. I guess it is not desirable to use undocumented API for Soundnode app and it actually makes sense.

**Comment by Pitros** [comment]
@mradionov we can use API V2 for that (after few tries got short answer - `Yes

**Comment by mradionov** [comment]
@Pitros , cool, I'm gonna make a try then. Thanks!

**Comment by Pitros** [comment]
@mradionov just updated my answer.
