### ISSUE TITLE
[FEATURE] Repeat button for tracks

### ISSUE THREAD

**Issue by Chriz007** [Soundnode/soundnode-app#292]

**Comment by RampageJack21** [comment]
Mr. Lancaster,

will this feature (much like shuffle feature https://github.com/Soundnode/soundnode-app/issues/226) also depend on https://github.com/Soundnode/soundnode-app/issues/138 being finished first?

P.S. I've told every single one of my friends who use soundcloud about this app.  Everyone loves it! Keep up the great work!!  :+1:

**Comment by weblancaster** [comment]
@RampageJack21 I started to work on this while ago but I haven't had long hours to work on it so I have a working progress (https://github.com/Soundnode/soundnode-app/commits/queue-rework) on #138 which will make easier and better for some planned features like this one and #226 and #257

**Comment by weblancaster** [comment]
#278 is a duplicated of this issue

**Comment by Chriz007** [comment]
@weblancaster A repeat button for tracks and a switch for disabling/enabling autoplay isn't the same thing..

**Comment by weblancaster** [comment]
@Chriz007 I think he is actually referring to a repeat button.. same thing because in both cases you won't be able to play next automatically.

**Comment by Pitros** [comment]
@weblancaster but it's still something much different - like disable autoplay for youtube - you just want to play one video not whole list or repeat one infinitely.
