### ISSUE TITLE
Sign in with Google Account doesn't work

### ISSUE THREAD

**Issue by verpixelt** [Soundnode/soundnode-app#294]
After hitting the "Sign in with Google" button the app keeps stuck with a white screen. If I tab out of it and back in I get the login screen like nothing ever happened. This basically makes the app unusable.

**Comment by Chriz007** [comment]
I think someone else had this issue before and it may be fixed in the next update.

**Comment by weblancaster** [comment]
@verpixelt can you check https://github.com/Soundnode/soundnode-app/issues/225#issuecomment-125697361

**Comment by Chriz007** [comment]
@weblancaster Hooray, you're back! I've been anxiously waiting for you to return. I've been checking the website for activity like 3x a day. Morning, Afternoon, and Night.
