### ISSUE TITLE
[SUGGESTION] Change the Soundnode Icon to make it stand out more

### ISSUE THREAD

**Issue by Chriz007** [Soundnode/soundnode-app#295]
Take a quick look at this screeny below. 

![screen shot 2015-08-06 at 11 17 55 pm](https://cloud.githubusercontent.com/assets/12990919/9129837/6b61a6d2-3c91-11e5-9673-e8b8e098f613.png)

You see the dock right? Right. Now find the soundnode app. 

...

It took you longer than you expected to find it right? 

You see where I'm going? I think changing the look of the icon would make it stand out more in a sea of icons. Now I'm not saying the current one is bad-looking. Its much better than anything I could do! But I think it could use a quick facelift so users can see them quickly. I don't expect a rapid change though. Maybe you can think about it and change it in the future.

Just my two cents! 

P.S Also, before anyone says that I can just change the icon myself, I would much rather prefer an official icon.

**Comment by weblancaster** [comment]
@Chriz007 I agree. Going to add to the roadmap.

**Comment by Chriz007** [comment]
So I made these two icons really quick. Tell me what you think. Its ok if you don't like it. I'm just trying to help out every bit I can! :)


![soundnode icon orange](https://cloud.githubusercontent.com/assets/12990919/9146900/9ed955a8-3d15-11e5-99a1-11fd79ac5d34.png)
![soundnode icon blue](https://cloud.githubusercontent.com/assets/12990919/9146901/a25d987e-3d15-11e5-9f03-ef8c3702767f.png)

**Comment by weblancaster** [comment]
Cool! thanks @Chriz007 

I also like the third option.. is there any meaning for those logos? why you chose that format/color etc

**Comment by Chriz007** [comment]
Meaning? No. I just thought it looked cool to me. I also wanted to put a node design in the middle, so I spent 2 hours trying to make it. Like a colorful kind of node with it connecting to other dots. But it didn't end up looking good at the end. Maybe I'll try again when I get back home. If you'd like to try to make an icon, you can go to the website I used to make it. https://freeiconmaker.com

Thanks for your interest. By the way, who designed the current icon?

**Comment by weblancaster** [comment]
Got it @Chriz007 

A friend of mine designed the logo I have some version on white and black backgrounds.. I'm going to try them out

**Comment by Chriz007** [comment]
Cool @weblancaster 

If you wouldn't mind, be sure to post them here. I'd like to see how they look too.

**Comment by RampageJack21** [comment]
![sounnode_options](https://cloud.githubusercontent.com/assets/9271427/9807962/1330ae24-580f-11e5-8a2d-9b6e44e9b021.png)
Above was a screen shot, taken on Aug 4th, i uploaded to a now deleted non-issue i had filed where i couldn't pin the app.  i don't recall what i did for the pin option to show up but after "pinning"  to the task bar it changed to this type
![soundnode_app_icon](https://cloud.githubusercontent.com/assets/9271427/9807981/450628fc-580f-11e5-9963-20524847a224.PNG)
In windows 10 and win7 enterprise, I have been seeing what i can only describe as a "black hexagon compass" icon ever since.

**Comment by chrismessina** [comment]
I started tweaking the basic icon design to see if I could get something that would stand out a little more, but it'd be helpful to have the Soundnode icon/default album art source. Is that available? Otherwise, I'm stuck with something like this for a first draft:

![image](https://cloud.githubusercontent.com/assets/22610/10301359/7eb1d50a-6bb6-11e5-80cd-9ae32eefae13.png)

**Comment by Chriz007** [comment]
I think the design looks pretty cool @chrismessina. Would love a higher res icon, if @weblancaster has any from the previous design.

**Comment by weblancaster** [comment]
@chrismessina I have the comps.. let me find them and make available for anyone.

**Comment by weblancaster** [comment]
Here's the PSD for anyone interested on play with https://drive.google.com/file/d/0B-BiaVWuDohiT2h6NmVhcnV2QTJMemhSdHljN1k2dklvaDZN/view?usp=sharing

**Comment by Chriz007** [comment]
Very cool! Thanks Michael!

**Comment by chrismessina** [comment]
@weblancaster thanks! Do you happen to have the source vector artwork?

**Comment by chrismessina** [comment]
Here's what I was able to come up with, redrawing the icon myself. Here's the [.icns file](https://www.dropbox.com/s/yr3mtwkyg263ff7/Soundnode-App.icns?dl=0).

![icon_512x512](https://cloud.githubusercontent.com/assets/22610/10562261/ab03895a-7507-11e5-81bc-dd80c8d67d1c.png)

**Comment by chrismessina** [comment]
Bump?

**Comment by weblancaster** [comment]
Hey @chrismessina I haven't try yet, I will plan to do that once I'm done with what I'm working on.

**Comment by chrismessina** [comment]
@weblancaster cool, just wanted to make sure it didn't get lost! :)

**Comment by weblancaster** [comment]
(Finally) I have a friend working on it.. he showed me what he done and looks great.. he is also working on a couple of minor design changes (buttons minimize, maximize and close).

**Comment by Chriz007** [comment]
@weblancaster Good progress!

**Comment by foxgeere** [comment]
Just to throw in my thought - can we make sure it is the same size as the iTunes, spotify etc icons. The current one is larger than every other icon in the dock.

Also, really love the first icon by @Chriz007 - it might want some element of 'cloud' worked into it or 'nodes' coming off from the headphones. In addition, if the circle around the outside actually updated with the length of the track remaining that would be freaking epic - however, I suspect not massively possible :)

**Comment by weblancaster** [comment]
Just FYI people here's a PR for the new logo if anyone wants to follow #602

**Comment by iDuuck** [comment]
#602 is definitely my favorite!

**Comment by weblancaster** [comment]
New logo/icon/placeholders added.

**Comment by foxgeere** [comment]
When is the new logo going to show up in a build release?

**Comment by weblancaster** [comment]
I need to get a couple of bugs fixes and then release.. soon very soon
