### ISSUE TITLE
[FEATURE] Auto-refresh Stream 

### ISSUE THREAD

**Issue by Chriz007** [Soundnode/soundnode-app#297]
It would be cool to either have:
1) A refresh button to refresh the stream page
2) Have a notification on the top indicating whether or not a new track has been posted, therefore giving you the option you to refresh it.

For example:
![iconnode](https://cloud.githubusercontent.com/assets/12990919/9141636/114469ce-3cef-11e5-8d72-a30e3fdfafbe.jpg)

**Comment by weblancaster** [comment]
Hm this is good idea.. thanks @Chriz007
