### ISSUE TITLE
[BUG] "No tracks on your account" When in fact, there are tracks

### ISSUE THREAD

**Issue by Chriz007** [Soundnode/soundnode-app#298]
Wanted to report this issue a while ago, but I thought it was a very minor problem that didn't really matter. I decided to report it anyway.

Example shown down below:
<img width="1293" alt="cb7b2763a7" src="https://cloud.githubusercontent.com/assets/12990919/9146162/4008564c-3d0f-11e5-8844-1c32bca22b8e.png">

**Comment by Chriz007** [comment]
Wow, you worked on this really fast! Great job.

**Comment by weblancaster** [comment]
easy peasy this one @Chriz007
