### ISSUE TITLE
User hability to toggle notification alert/sound when track changes

### ISSUE THREAD

**Issue by MarkArranz** [Soundnode/soundnode-app#306]
As a user, I would like the option of turning off the notification sound or desktop alert when the soundnode app changes tracks.

**Comment by weblancaster** [comment]
Thanks for the feedback @MarkArranz 

I have been thinking to add user settings to enable/disable some features, so this will make it.

**Comment by MarkArranz** [comment]
Awesome. I am available to help you work on this if you'd like.

**Comment by weblancaster** [comment]
This was added on #383 and will be available in the next release.
