### ISSUE TITLE
[BUG] Graphical Glitch when adjusting volume

### ISSUE THREAD

**Issue by Chriz007** [Soundnode/soundnode-app#308]
Never noticed it before because I always used my keyboard or earphones to adjust the volume.

Example:
http://sendvid.com/k40t3pyy

**Comment by Pitros** [comment]
When running Soundnode on nw.js (0.12.3) this bug seems to be fixed (probably that was Chrome issue).

**Comment by weblancaster** [comment]
Yep, that's just a rendering/re-paint issue

**Comment by Chriz007** [comment]
You can close this issue now @weblancaster or @Pitros. Its fixed in the newest update

**Comment by weblancaster** [comment]
great.
