### ISSUE TITLE
[FEATURE] Info about songs + concept ideas

### ISSUE THREAD

**Issue by Chriz007** [Soundnode/soundnode-app#309]
Ex:
• Date uploaded
• Views gotten
• Likes gotten
• Comments gotten

Dunno how you're gonna fit all this in if you plan to, but good luck :+1: 

EDIT: Actually I have an awesome concept I'll work on that I think will work great! BRB

EDIT 2: Here's some concept ideas, I know I didn't get the date on there, thats going to have to be decided later. Down below I'll walk you through the stuff. Also, on the last picture, I know you may not be able to read the comments that well. The blur would have to be darker.

First concept, decided to change the design on this one and make the bottom part blurry.

Now, look at the first song on the list. You see it shows the comments, likes, reposts, and also it shows an arrow button to show more info. 
![concept info 2 blur](https://cloud.githubusercontent.com/assets/12990919/9300979/d3cf89dc-447f-11e5-9baa-dd8e7b4dbbee.jpg)
When you click the arrow, it slides up (just like in material design), and it shows all the comments where you can scroll through, read through them, and also decide to post one if you ever feel like
![comment concept 3 blur fix](https://cloud.githubusercontent.com/assets/12990919/9300981/d5a99860-447f-11e5-94ef-26905e8b9558.jpg)

**Comment by jakejarrett** [comment]
The second concept with transparency looks best, The opaque bar looks a bit odd.

**Comment by weblancaster** [comment]
@Chriz007 pretty cool concept.. We should work on something around that idea.

thanks!
