### ISSUE TITLE
Re-write Soundnode

### ISSUE THREAD

**Issue by weblancaster** [Soundnode/soundnode-app#310]
Time to move Soundnode from Angular to React (React router) and ES6/ES2015.

A branch called `soundnode-react` was created with the goal to move Soundnode forward to React.. this work will be in parallel with the work on master branch (nothing changes there).

I'm going to setup React in the project (soundnode-react branch) and we go from there.
The ideal is to start replacing Angular routes/views/controllers with React components.

Label anything related to this re-write with `re-write` label.

**Comment by Pitros** [comment]
May I know why you want to re-write almost whole app?

**Comment by weblancaster** [comment]
I have a lot of reasons @Pitros 

Apply my React knowledge in a medium size App and learn more about it at the same time.
Make the App faster, more modular, easier to understand as a dev point of view.

**Comment by weblancaster** [comment]
This won't happen.. we will re-write in Angular 2 @Pitros

**Comment by Pitros** [comment]
When you posted that issue, I wondered why would you like to rewrite whole app. But after a while i found out that there are some things that would be nice if those would be rewritten. As well i found out that Angular is bit tricky and it's sometimes hard to stick with doing things in "angular" way so if you feel better in react, there's no need to stick to Angular (when Angular 2 is much different compared to Angular "1").

**Comment by weblancaster** [comment]
@Pitros Yeah I haven't really make up my mind.. I like the structure Angular framework give out-of-the-box now in React lib we will need to come up with a nice and easy architecture (although I would use the same architecture we have in place right now).

What makes Angular 2 appealing is that they now use RxJS which I'm interested to apply on a project like Soundnode.

**Comment by weblancaster** [comment]
@jakejarrett @Pitros after analyze React and Angular 2, although I would go to Angular 2 because of RxJS/Observables style.. That's not ready or beta yet.

For that reason I started to re-write some small components in React I'm doing some refactoring in the grunt file to accommodate React.

**Comment by weblancaster** [comment]
Closing this issue since #433 is a start of the re-write in React + ES2015

**Comment by jakejarrett** [comment]
@Pitros @weblancaster Would it be worth the time to consider react/angular2 again now? The app has a lot of unnecessary complexity in parts (eg/ It's not super clear to someone wanting to contribute how they would alter the UI for the stream page)

**Comment by weblancaster** [comment]
@Pitros @jakejarrett I have been thinking about now almost every day but with work, another side projects and hobby my time is very limited.. so this would take a while.

Here's what I have been thinking to use React stack (react-router, redux), webpack, CSS modules, flow type

**Comment by weblancaster** [comment]
@Pitros @jakejarrett oh and a couple of designers are interested in redesign too which would be pretty cool for the re-write.. I'm going to setup a chat system so conversations can be easier to maintain.

**Comment by wb9688** [comment]
@weblancaster: Can you explain why you choose for React instead of
alternatives (eg. Vue or Angular 2)?

**Comment by wb9688** [comment]
@weblancaster: Nice! How will you do the chat? With Slack, Gitter, IRC or
what?

**Comment by Pitros** [comment]
@weblancaster @jakejarrett @wb9688 getting rid of that angular/react/jquery weird pack would be nice, but re-write would require some time. 
But still it's better to do it now than later when more features would be added. 

Also Angular 2 stable was finally released, and it might be worth to reconsider.

**Comment by wb9688** [comment]
If we're going to rewrite Soundnode with React and Electron, I'd be
interested in contributing…

@Pitros: Soundnode's current source code is really messy indeed…

@weblancaster: Can you please create a separate repository for the complete
rewrite?

**Comment by jakejarrett** [comment]
@weblancaster @wb9688 I've started work on this, I can push to a new branch on this repo instead of a fork if necessary.

We should utilize the new github projects utility to split this process up until small bits so anyone can jump in and help out whenever.

if you're interested in what i've implemented, check out the [Fork](https://github.com/jakejarrett/soundnode-app/tree/react)

**Comment by wb9688** [comment]
@jakejarrett: I tried to build your fork, but I got some errors that `node-sass` is missing, so I ran `npm install node-sass`, but now I'm getting the following error:
```
Running "clean:build" (clean) task
>> 0 paths cleaned.

Running "shell:target" (shell) task
Hash: d77958d65f93222d4a95
Version: webpack 2.1.0-beta.25
Time: 5385ms
  Asset     Size  Chunks             Chunk Names
   0.js  2.48 kB       0  [emitted]  
main.js  1.01 MB       1  [emitted]  main
 [291] multi main 28 bytes {1} [built]
    + 294 hidden modules

ERROR in 0.js from UglifyJs
SyntaxError: Unexpected token: name (Home) [0.js:14,6]

ERROR in main.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [main.js:14845,19]
Warning: Command failed: webpack -p
 Use --force to continue.

Aborted due to warnings.


Execution Time (2016-10-15 09:30:00 UTC+2)
shell:target  6.5s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
Total 6.5s

```

**Comment by jakejarrett** [comment]
@wb9688 I haven't ported over the grunt build process, I'm working on putting each piece of soundnode into components atm.

You can run `webpack -d` and just view the HTML file for the view to show atm. (Will have to pull)

**Comment by wb9688** [comment]
@jakejarrett: Ah, OK! Couldn't you just start with a boilerplate like [this one](https://github.com/chentsulin/electron-react-boilerplate)?

**Comment by weblancaster** [comment]
@wb9688 React because it's easier to understand and to move quickly, also because of other advantages like speed and developer adoption this days.

I also have been working with React now for two years so I believe I have a strong opinion on how to use and what to do moving Soundnode forward.

I considered at first Angular 2 but after learning more about it I decided that React will be better option.

**Comment by weblancaster** [comment]
@jakejarrett hold on re-writing things because I'm going to setup the base work before it gets messy.. we won't follow what is in place right now, we want new and better architecture.

also everything will be componentized meaning css will leave on the js, new patterns will be introduced.

**Comment by wb9688** [comment]
@weblancaster: Thanks for your explaination about why you chose React! Are you going to set up the base work in a new repository or in a new branch? Btw when will you set up the chat?

**Comment by wb9688** [comment]
>@jakejarrett hold on re-writing things because I'm going to setup the base work before it gets messy.. we won't follow what is in place right now, we want new and better architecture.
>
>also everything will be componentized meaning css will leave on the js, new patterns will be introduced.

@weblancaster: Have you set up the base work in the mean time?

**Comment by weblancaster** [comment]
@wb9688 

> also because of other advantages like speed and developer adoption this days.

Note on the developer adoption.. very few people use vue.

> Have you set up the base work in the mean time? I really wanna start working on it

I haven't because I still working on migrating everything from NW.js to Electron.js (https://github.com/Soundnode/soundnode-app/pull/894)

**Comment by weblancaster** [comment]
Just a few more things to get in place before another release having everything migrated.. hoping to make some time this weekend.

**Comment by weblancaster** [comment]
Maybe this will happen some day but closing the issue since got lost in the history.
