### ISSUE TITLE
Improve search dropdown design

### ISSUE THREAD

**Issue by weblancaster** [Soundnode/soundnode-app#312]
Although the feature is pretty cool, the design isn't that appealing.

![screen shot 2015-08-19 at 5 34 48 pm](https://cloud.githubusercontent.com/assets/549394/9370884/75bff8ba-4699-11e5-8768-88af4b588d83.png)

**Comment by Chriz007** [comment]
What about making the dropdown menu a dark color, making the letters white, and decreasing the space between the artists?

**Comment by Chriz007** [comment]
Or you could do it how spotify does it where they put the song on top and the artist on the bottom
<img width="245" alt="screen shot 2015-08-19 at 4 10 43 pm" src="https://cloud.githubusercontent.com/assets/12990919/9371808/e379c622-468c-11e5-9a44-48c9ab48c7e7.png">

**Comment by Pitros** [comment]
In last days I've been playing with Soundnode look (yes, again). I've already made few tweaks including search bar, dropdown, profile look and player progress bar and some under the hood improvements.

**Here's how it currently looks:**

![image](https://cloud.githubusercontent.com/assets/6910670/9372367/14b2f488-46de-11e5-87cf-96b3d7637e8d.png)

![image](https://cloud.githubusercontent.com/assets/6910670/9372372/21a8bbc8-46de-11e5-90ee-e4f2223f83d0.png)

Anyway do you guys need information about song licence on stream list? It mostly shows all-rights-reserved or cc-[something] and it takes rather quite a lot of space.
I still want to implement @Chriz007 idea - #309 so I'm just asking to be sure what to do with it.

Anyway tell me what you think :smiley:.

**Comment by Chriz007** [comment]
@Pitros That looks absolutely sick man!

**Comment by weblancaster** [comment]
Hey @Pitros thanks for working on it again.

First screenshot:
I liked the idea of having `show more` button for the profile.. but I want to use orange as little as possible just in a few small places e.g track progress bar so I wouldn't go with that color in the border for the button.

Second screenshot (dropdown):
everything looks pretty good I would just remove the orang from the top border (I would remove that border).
and change the border color for the titles artists/tracks

Thanks!

**Comment by Chriz007** [comment]
For the Following button, you should probably make it change colors so we can tell right away that we have followed them

**Comment by weblancaster** [comment]
Yeah I think the `hover` state and `following` can be orange but the button at default state should be something light white/gray.

**Comment by weblancaster** [comment]
@Pitros don't forget to open a PR for each feature/redesign please.

Also, if possible having the PR for the search dropdown first would be great.. just waiting for that to release next version of Soundnode.

**Comment by weblancaster** [comment]
close with #320
