### ISSUE TITLE
Unplayable Track

### ISSUE THREAD

**Issue by fortytw2** [Soundnode/soundnode-app#314]
Trying to play -> https://soundcloud.com/zedd/bn-greyremix inside Soundnode doesn't seem to work, but it also had some issues on Soundcloud itself - so I'm not sure if this is a Soundnode issue or if Soundcloud is doing something weird.

Great work though, using soundnode every day now :+1:

**Comment by Chriz007** [comment]
Yeah, how odd! I tried playing that same music but it didn't work. I don't think its part of soundclouds api limit usage, but maybe @weblancaster can look into the logs or something

**Comment by fortytw2** [comment]
Could soundcloud be rolling out a different format of some sort? There was a period of time yesterday that the track wouldn't play on web either. Really quite odd

**Comment by Chriz007** [comment]
I don't think so.. and plus the song still works on soundcloud. Just not soundnode.

**Comment by Pitros** [comment]
It's soundcloud issue, API does not return mp3 file, it returns blank page.
