### ISSUE TITLE
[IMPROVEMENT SUGGESTION] New Alphabetical order layout for artists in the "Following" page

### ISSUE THREAD

**Issue by Chriz007** [Soundnode/soundnode-app#315]
The artists are already in alphabetical order, I know already. But with many artists I follow, its hard to keep track of them. Thats why I've come up with an idea to make navigation through the page easier. (p.s I would do a concept art thing, but photoshop is messing up with me right now)

1) Put the artist's name on top/bottom of their profile picture. (some of them have designs, but you wouldn't really be able to tell if they didn't have their artist name on the profile pic)

2) Add an A-Z alphabetical order type of sorting on the side

3) Make the artist's pictures smaller, 

4) Add all the "A's" right next to each other, so you can be able to scroll horizontally and it would keep listing them to the right of one another. Then on the bottom of the "A's", you insert the next artist category, "B's" and so on and so forth.

Here is a very quick example

![following concept final2](https://cloud.githubusercontent.com/assets/12990919/9433637/89ceba5e-49ea-11e5-9b6c-72da35e9358e.jpg)

**Comment by Skkiz** [comment]
I would also like this feature too @weblancaster. I think it would be a good way to categorize the artists a little better.

**Comment by Skkiz** [comment]
Either that or have an option to resize the following page's artists. But I think I would like what something along the lines around the concept that @Chriz007 has come up with.
