### ISSUE TITLE
[Bug] Fix track info repost overlap

### ISSUE THREAD

**Issue by weblancaster** [Soundnode/soundnode-app#324]
in the image attached we can see that the activated/playing song has the infos comments, likes and reposts, where reposts is the one overlapping.

![screen shot 2015-08-24 at 12 55 39 am](https://cloud.githubusercontent.com/assets/549394/9433626/2902ebb2-49fb-11e5-964e-d5a36118bbb8.png)

**Comment by Chriz007** [comment]
To fix this, are you going to make the numbers scroll sideways like a Marquee? Or are you going to estimate the number of tracks played by writing 6K, 60K etc?

**Comment by weblancaster** [comment]
@Chriz007 second options most likely, but definitely not a marquee like haha.

**Comment by Chriz007** [comment]
Ah. And completely awesome update! just downloaded it!

**Comment by weblancaster** [comment]
and @jakejarrett

**Comment by Pitros** [comment]
We could stick with soundcloud format - round to 1K or 1M etc. 

Using small custom angular filter it looks like that:
![image](https://cloud.githubusercontent.com/assets/6910670/9448658/20ef18bc-4a9e-11e5-92b9-e5278b6bab6c.png)

**Comment by weblancaster** [comment]
@Pitros yes that is good.
