### ISSUE TITLE
Add checkmark for verified artists

### ISSUE THREAD

**Issue by Chriz007** [Soundnode/soundnode-app#327]
There are many posers out there on soundcloud with the same names/profile pictures as artists. I'd like to request a feature to add verified checkmarks to the end of an artist like this

![bsd](https://cloud.githubusercontent.com/assets/12990919/9452185/bd43aba6-4a67-11e5-9d5b-ab6e526bdb58.jpg)

**Comment by cdtinney** [comment]
SoundCloud does not verify users, so this is not possible. The best you could do is mark users that have paid for the "Pro" service (most professional artists) but you can't check this via the API either.

**Comment by Pitros** [comment]
@cdtinney API gives information about user subscription plans.

**Comment by cdtinney** [comment]
@Pitros I see the *plan* property under the */me* endpoint, but not */user*. So you could only check the user subscription plan for yourself. Is that incorrect?

**Comment by jakejarrett** [comment]
@cdtinney I'm fairly certain there is a plan property when you call the users endpoint, but I could be mistaken.

**Comment by Pitros** [comment]
@cdtinney @jakejarrett uh, I was wrong... 

SC has changed theirs API once again, earlier in each API call there was info about user subscription plan (as far as i remember), now it's gone. But something like `verified` has appeared, so they might add some day user verification.
