### ISSUE TITLE
[Bug] Download link for linux is disabled

### ISSUE THREAD

**Issue by jakejarrett** [Soundnode/soundnode-app#328]
When you visit soundnodeapp.com and try to download the linux build, it redirects you to a page stating that the URL has been disabled.

![screenshot from 2015-08-25 14-39-50](https://cloud.githubusercontent.com/assets/5661105/9458860/2f39a556-4b37-11e5-8f91-f18c837b0fe8.png)

**Comment by weblancaster** [comment]
It's fixed.
Thanks for letting me know @jakejarrett .. they must have updated the policy.
