### ISSUE TITLE
[Question] App not working

### ISSUE THREAD

**Issue by nmsadsfadsf** [Soundnode/soundnode-app#331]
![unbenannt](https://cloud.githubusercontent.com/assets/13980049/9491749/a48cc4ae-4bf1-11e5-80f5-d03ca70fdd75.PNG)
When I try to open the latest version of the soundnode app (0.5.7) it gets hung up on this screen.
I am running win 7 enterprise inside a company-network. could the problem be the firewall blocking soundcloud?

**Comment by Pitros** [comment]
You're launching it for first time or it stopped working after update? Did login window show on screen?
And press `Ctrl + /` and check if in console tab something showed up. 
It should work fine on Win 7, but it might be firewall blocking something.

**Comment by Chriz007** [comment]
That has happened to me when connecting to a school/company network. It just hangs up on me and won't connect. It's just the network

**Comment by weblancaster** [comment]
I can use Soundnode without problem on my company so that issue could be something else missed although haven't seem or nobody reported that issue before.

@nmsadsfadsf would be able to try to use in another network? and tell us if that work please.
Also, did you try connect with Facebook orGoogle?

Thanks.

**Comment by nmsadsfadsf** [comment]
I wasnt able to get to the login screen.. But i checked if i even could use souncloud with my browser and it said, that audio streaming is blocked by the network admin, which makes sooo much sense -.-
Does anyone know if i can change the adress where the app gets the music/account data from, so that it uses a proxy?

**Comment by weblancaster** [comment]
Oh ok so that's a Soundcloud "issue" @nmsadsfadsf (if you don't want to login automatically you need to log out)..

Soundcloud manages the music/account data.. nothing we can do.. sorry.
