### ISSUE TITLE
[Feature] Track page

### ISSUE THREAD

**Issue by Pitros** [Soundnode/soundnode-app#335]
I'm currently working on track page, it still need some polish, but overall it works.

And I completely rewrote `show more` button behavior, now it's based on max height not text length.

Here's small preview.
![image](https://cloud.githubusercontent.com/assets/6910670/9569661/b7261718-4f71-11e5-8193-ca91634d244b.png)

**Comment by Chriz007** [comment]
Great work Pitros!
