### ISSUE TITLE
[IMPROVEMENT] Tracks view simplification, like button behavior

### ISSUE THREAD

**Issue by Pitros** [Soundnode/soundnode-app#336]
I've been working on tracks view (see pic), looks simpler - less text etc. as well I made changes to likes directive - you can like and unlike tracks without reloading, as well you can see which tracks you already marked as liked. Let me know if you like those changes or not.

Here's preview:
![image](https://cloud.githubusercontent.com/assets/6910670/9569693/92ea00de-4f72-11e5-88be-7b7fe0df2de4.png)

**Comment by Chriz007** [comment]
Pitros, awesome work! Much more simplified and better looking. Do you plan to make groups for the different genres? For example you type in 'Bounce' in the search bar and it loads up a page of bounce songs ranging from Trending to Popular?

**Comment by Pitros** [comment]
@Chriz007 you mean genre/tag view? Like that one on Soundcloud: https://soundcloud.com/tags/tropical%20house ?

**Comment by Chriz007** [comment]
Yup! Thats what I meant
