### ISSUE TITLE
[FEATURE SUGGESTION] Explore

### ISSUE THREAD

**Issue by thefabulousdev** [Soundnode/soundnode-app#347]
I personally use [Soundcloud Explore](https://soundcloud.com/explore)
 90% of the time that I'm listening to music.

It would be cool to have something like that on the application.

**Comment by Chriz007** [comment]
Yes, they already know about this.

**Comment by wb9688** [comment]
We can use `https://api-v2.soundcloud.com/explore/categories?limit=10&offset=0&linked_partitioning=1` to get a list of categories and `https://api-v2.soundcloud.com/explore/Popular+Music?limit=10&offset=0&linked_partitioning=1` to get the tracks in that category (in that example the category is `Popular Music`)...

**Comment by tgjohnst** [comment]
I, too, use explore 90% of my SoundCloud time to play through the trending tracks playlists for various genres to discover new music. It would be wonderful if this were implemented at some point as right now I've had to go back to my hacky Fluid app as my only way to access SoundCloud Explore outside of my browser.

**Comment by insanexd** [comment]
I downloaded the app three days ago and it is awesome!
Playing with it I tried to find the "trending" tab but sadly i couldn't :(
So I thought to suggest this feature, it would be great to have it!
U r doing an extraordinary job guys! props!

**Comment by weblancaster** [comment]
This was added #539

**Comment by tgjohnst** [comment]
Awesome, thanks!! Suggestion for a future update - allow filtering by genre and/or new/hot rather than top, like the web version does. The overall site top 50 unfortunately doesn't change all too often.

**Comment by weblancaster** [comment]
Yes @tgjohnst that's the plan I added top 50 just as quick feat.. I will add filter for the next release
