### ISSUE TITLE
[Feature] Filtering

### ISSUE THREAD

**Issue by jackquack** [Soundnode/soundnode-app#349]
I would kill for filtering of Soundcloud tracks. Ideally their API would support this, but I haven't investigated. Though even if it isn't possible through their API, it could be client-side

Example use cases
- Filter to only show tracks longer than 20 minutes
- Filter to only show uploads, not re-posted tracks
- Only show tracks w/ more than 10,000 listens

**Comment by weblancaster** [comment]
We can definitely implement that..I will add to the roadmap although we have a bunch of work to do before start this one.
Thanks for the feedback @jackquack

**Comment by jackquack** [comment]
I have more faith in you implementing this feature than Soundcloud. They haven't innovated on anything in years. I have emailed them multiple times requesting this feature.

**Comment by weblancaster** [comment]
Haha thanks @jackquack

**Comment by weblancaster** [comment]
@jackquack this is implemented and will be release in the next version.

**Comment by Pitros** [comment]
@weblancaster, are you going to style those buttons or you want someone else to do it? As well it would be nice to add inputs/sliders for more filter control.

Another thing could be API filtering, becasue it's possible, and that would be much better in search and tag view (as far I remember, even api-v1 gives ability to filter tracks).

**Comment by weblancaster** [comment]
@Pitros I wasn't going to style the buttons.

And yeah filter tracks using the api would be the ideal case.. I just created a issue for that #487

**Comment by jackquack** [comment]
@weblancaster thanks so much! I'll be using Soundnode full time now!
