### ISSUE TITLE
[Bug] Having trouble Authenticating account with new version 

### ISSUE THREAD

**Issue by Chriz007** [Soundnode/soundnode-app#354]
![screen shot 2015-09-09 at 6 01 05 pm](https://cloud.githubusercontent.com/assets/12990919/9777764/cd462300-571c-11e5-88bc-bc0d566f374c.png)

**Comment by weblancaster** [comment]
Trying to fix it now @Chriz007

**Comment by weblancaster** [comment]
Are you on windows or mac @Chriz007

**Comment by Chriz007** [comment]
I ran it both on my mac and using my virtual machine, I ran it on windows. Both did not work

**Comment by weblancaster** [comment]
This is weird I tried here and worked

**Comment by Chriz007** [comment]
Strange. Is there some sort of console I can activate to copy/paste it on to here?

**Comment by Chriz007** [comment]
I wonder if anyone else is having that problem.

**Comment by weblancaster** [comment]
@Chriz007 I uploaded a new version.. can you check again please

**Comment by Chriz007** [comment]
Sure thing.

**Comment by weblancaster** [comment]
Didn't fix.. I just tried the download and did no work.. and there's no log of error or nothing

**Comment by Chriz007** [comment]
Yeah, was just about to say that.

**Comment by Chriz007** [comment]
Any luck in fixing it yet @weblancaster?

**Comment by jakejarrett** [comment]
This happened with the latest build for me due to universal-analytics missing.

**Comment by HypeHenry** [comment]
same here o/

**Comment by Pitros** [comment]
```javascript
Uncaught Error: Cannot find module 'universal-analytics'
````

@weblancaster you havent included `universal-analytics` files with release. 
To include those, `node_modules` directory containing `universal-analytics` must be placed in the same directory where package.json is located (that means `app/` ).

But the thing is, if we attach analytics, app size will increase by 3MB (4.5MB on hard drive), I don't think that's worth it. If you want to track which page is used more commonly, you should find another way.

**Comment by weblancaster** [comment]
I had found why last night (Chicago time) and committed.. I will keep the GA.

Thanks for the help all.
