### ISSUE TITLE
[FEATURE SUGGESTION] Add a "never play this again"  functionality

### ISSUE THREAD

**Issue by RampageJack21** [Soundnode/soundnode-app#356]
I often use soundcloud/node for music discovery.  A particular artist might have uploaded or re-posted an awful track that figuratively makes me ears bleed.  I know Soundcloud doesn't have the functionality to 'hide' or "dislike" tracks but i really wish they did.

Is this something that could be done client side? I use soundnode on my work computer and home computer, if a text file can be stored in the cloud (i.e. dropbox, googledrive, etc..) and soundnode could update/write-to it, this would allow syncing between computers (almost server-side functionality in a hacky way). 

I would like to know how would i go about asking soundcloud to add an API for developers (but not expose it on their web page) so they can store the list of awful tracks on server side.  

Perhaps Soundcloud wants to maintain a positive platform similar to how Facebook refuses to add a 'dislike' button and me asking them to implement this API + publicly expose it will likely get nowhere. 
But perhaps if the API was created for external applications like soundnode, this feature request would be much easier to implement. 

I noticed that right clicking in various places on the application does not do anything (ver 0.5.7), I am sure that is by design.  If this is at all possible to implement/maintain this request, maybe right clicking on the progress bar can give you the option to eliminate the track from the [stream] section for good.

**Comment by weblancaster** [comment]
This would be a good feature to have.. is definitely doable but I still need to look in to the syncing part because I don't want costs (e.g database) with Soundnode since it's free and open source.

**Comment by weblancaster** [comment]
also, update to version 0.5.8 is stable and working.. with a bunch of new feats.

**Comment by Chriz007** [comment]
@RampageJack21 Dude I hear ya! Sometimes I just absolutely hate a song and never want to hear again so I wish this was a thing soundcloud had.

**Comment by RampageJack21** [comment]
@weblancaster yeah i updated.  Excellent job with the queue structure, repeat, and shuffle all work really well.  I love how the "all rights reserved" disappeared from the bottom of each track; an aesthetic bonus.  

Yeah i know this would take time, and i'm very patient.  I find I can mostly focus on work and music is just background noise, unless a track comes on that give me goosebumps .. catches my attention and i hit like. the other instance is awful tracks and i quickly hit next.  Prior to the current version, shuffle wasn't available, so if an awful song was in that stream early on, i would hear it daily at work (it would get pushed down eventually by more recent tracks but still).

I really like contributing ideas to this project.  It makes me want to learn to code and contribute in a technical way.
