### ISSUE TITLE
[Discussion] What do you think of Soundnode going mobile?

### ISSUE THREAD

**Issue by Chriz007** [Soundnode/soundnode-app#357]
I'm so grateful this app exists, but what do you think of having an Android/IOS (preferably android) version of soundnode for on-the-go listening in the future?

**Comment by DidUknowiPwn** [comment]
Well SoundCloud already has applications for them but for me it's broken. It freezes about 60% into the song and plays the next one.

Galaxy S3

**Comment by Pitros** [comment]
@DidUknowiPwn that's something wrong with your phone, not the app itself. You should try wiping app data or reinstalling it. If it wont help only way seems to me is factory reset of whole phone. 

Building an Android/iOS app is in my opinion pointless, there are at least two apps for Soundcloud: official one and My Cloud Player which offers different features compared to official app.

**Comment by weblancaster** [comment]
Agree with @Pitros 

Develop and maintain a mobile version besides the Desktop would be a lot of work..We all have "real jobs" outside the Open Source world so that would be hard.

Closing the issue. Thanks for the suggestion though.
