### ISSUE TITLE
Not starting, stuck at Authenticating Account - Latest Version

### ISSUE THREAD

**Issue by iashraful** [Soundnode/soundnode-app#359]
I received update notification yesterday(Sept. 10th, 2015). 
Downloaded the latest version from main-website. 
I followed these steps to install.

01. Delete everything from previous installation in Soundnoe-App folder
02. _Extract new version_ downloaded
03. Copy & Paste all files from extracted folder(from Step. 02) to old Soundnode-App folder
04. Double-click 'Soundnode-App.exe' to run

ISSUE: The new version does not reach past 'Authenticating your SoundCloud Account' screen(screenshot included). I closed/run/closed/run/closed/run .... cleared my Temp folders, deleted the whole folder, redownloaded, extracted, run/closed/run/closed still stuck at this screen.
If I let it run, it crashes after 4/5 minutes and windows force-closes it.

![stuck](https://cloud.githubusercontent.com/assets/13736302/9807748/7a35ff24-5879-11e5-906a-6cad6f567156.JPG)

P.S: Since its portable I don't know how to actually remove any leftover. I checked my 
c:\users\my-user-name\appdata\ --> `Local` & `Roaming` folders for leftover but nothing there.

**Comment by iashraful** [comment]
Solved!
Sorry, I renamed the installation folder to Soundnode-App. Previously it was 'soundcloud-app'.

**Comment by weblancaster** [comment]
@iashraful I actually had released with a bug that was making the app get stuck in the part.. sorry and thanks.
