### ISSUE TITLE
[Feature suggestion] Miniplayer

### ISSUE THREAD

**Issue by HypeHenry** [Soundnode/soundnode-app#360]
Maybe it's a very good to have aan mini player for the soundnode app. 

like what iTunes have. 
<img width="295" alt="schermafbeelding 2015-09-11 om 12 42 36" src="https://cloud.githubusercontent.com/assets/10399325/9813136/5423ea30-5883-11e5-9be6-2914f5dd988d.png">

**Comment by Pitros** [comment]
It has been discussed last time - #209 but @weblancaster closed that issue. 
So probably wont happen but it might be good idea to create small draggable window with just track title and control buttons.

**Comment by HypeHenry** [comment]
like this ?  ->  <img width="295" alt="schermafbeelding 2015-09-11 om 12 50 30" src="https://cloud.githubusercontent.com/assets/10399325/9813188/c26ac702-5883-11e5-9b2a-9dd8f844eb5c.png">

**Comment by Pitros** [comment]
For me it might or even should be even simplier :) But yeah something like that.

**Comment by weblancaster** [comment]
@HypeHenry Soundnode App has no plan to support a mini player.. for that you can check out http://gillesdemey.github.io/Cumulus/ one of their contributors was actually a Soundnode core team member.

**Comment by weblancaster** [comment]
maybe down the road..but for now closing this issue as this was discussed before.
