### ISSUE TITLE
Playlist syncing and Genre searching

### ISSUE THREAD

**Issue by totalKraze** [Soundnode/soundnode-app#363]
I dont know if its just me having this problem but my Playlists, arent syncing and refreshing to my soundcloud account. Im a frequent SoundCloud user and have added new songs to my faves and Likes playlists recently, but though I am logged into SoundCloud through Soundnode, none of my most recent additions have been synced on soundnode. I have tried relogging, but that aswell didnt work. So I dont know if its a bug or not, but just throwing that little issue out there.

IM RUNNING WINDOWS 7 ULTIMATE 32BIT

I also wanted to suggest adding a genre playlist search. Im sure many others love exploring different artists and styles, and do it through the genre playlists, so just a suggestion to add that.

**Comment by weblancaster** [comment]
@totalKraze I will take a look in to this but I remember I had issues to not being alowed to display playlists..

**Comment by totalKraze** [comment]
Its not that big of a deal on my opinion, but it would be nice lol take your time with it, I know coding is complicated, so no real rush. Just enjoying the app and would like to help improve any way I can. Thanks.
