### ISSUE TITLE
[Bug] Pressing back from a page doesn't save the track's position from the stream

### ISSUE THREAD

**Issue by Chriz007** [Soundnode/soundnode-app#365]
Say I'm playing this song from the stream..
![screen shot 2015-09-15 at 12 02 56 am](https://cloud.githubusercontent.com/assets/12990919/9870004/2e10c428-5b3d-11e5-84d0-579866928097.png)
When I click the song's name that redirects me to the description/comments page, it doesn't save the track's position when I click the back button.
![screen shot 2015-09-15 at 12 03 17 am](https://cloud.githubusercontent.com/assets/12990919/9870006/2f2a2bd8-5b3d-11e5-9964-5c102935689f.png)
A fix for this would be great! Thanks

**Comment by weblancaster** [comment]
That's the default behavior @Chriz007 and not a bug.
