### ISSUE TITLE
[Bug] Continuous seeking 

### ISSUE THREAD

**Issue by DidUknowiPwn** [Soundnode/soundnode-app#371]
Video: http://www.youtube.com/watch?v=pVfpdO7GGtk

Issue: 
Song seeks to wherever mouse is hovering.

Steps:
Play any song
Press and hold onto the scrubber, drag it outside the form then let go while outside of it.

**Comment by Chriz007** [comment]
Not really sure this is an issue.. I think all applications have this. All you have to do is click once to return it back to normal..

**Comment by weblancaster** [comment]
This is not a bug, it's a feature.. that's how it suppose to work.
