### ISSUE TITLE
Dropdown menu doesn't disappear once you've hit enter

### ISSUE THREAD

**Issue by Chriz007** [Soundnode/soundnode-app#380]

**Comment by jakejarrett** [comment]
@Chriz007 which dropdown menu are you referring to?

**Comment by Chriz007** [comment]
Its the bar where you search up songs

**Comment by Chriz007** [comment]
<img width="503" alt="screen shot 2015-09-19 at 11 59 42 am" src="https://cloud.githubusercontent.com/assets/12990919/9977716/f1beeac2-5ec5-11e5-9f18-27479f34d329.png">

**Comment by jakejarrett** [comment]
@Chriz007 this doesn't appear to be occuring for me [video](https://sendvid.com/t52b011i), could you show what you did to encounter this bug?

**Comment by Chriz007** [comment]
This is what it does http://sendvid.com/7msabe5l

**Comment by Chriz007** [comment]
I think it reproduces when you try to type something in there already and click out of it.
