### ISSUE TITLE
[Feature] Settings Page

### ISSUE THREAD

**Issue by jakejarrett** [Soundnode/soundnode-app#382]
I've been working on a basic settings page where users could change settings that are built into the app.

This should allow users to make soundnode change its behavior to their liking. This uses localStorage for the settings.

![screenshot from 2015-09-20 14-10-08](https://cloud.githubusercontent.com/assets/5661105/9979184/83ee63ba-5fa1-11e5-8bfa-1a1f714ad570.png)

**Comment by Chriz007** [comment]
Cool. What other settings do you plan on implementing?

**Comment by jakejarrett** [comment]
@Chriz007 I'd love to make it so you could enable features from the settings page (like beta testing / unstable features) but this depends on what everyone else would like too.

**Comment by Chriz007** [comment]
Oh and if you don't mind, I have a settings page I designed really quick inspired by popcorn time's toggle-able buttons. Tell me what you think.
![settings beta](https://cloud.githubusercontent.com/assets/12990919/9979351/13a4a864-5f1d-11e5-8be2-e1430abf4e1e.jpg)

**Comment by jakejarrett** [comment]
Here's what i have so far.

![screenshot from 2015-09-20 16-15-47](https://cloud.githubusercontent.com/assets/5661105/9979484/eaceaaf2-5fb2-11e5-8a0f-6acfd8e56b7a.png)

**Comment by Chriz007** [comment]
@jakejarrett Sweet! Looks even better!

**Comment by Chriz007** [comment]
I have more ideas for the settings..
• Reposts (hide/unhide)
• Option to reset stream (blacklisted tracks that you want to bring back)
• Blacklist podcasts; longer than 10+ minutes. There can also be a slider to choose the limit

**Comment by jakejarrett** [comment]
[Here](http://sendvid.com/xujrn7a1) is a video of the settings page. 

@Chriz007 I think it's best to implement settings for features currently implemented and then implement newer features later

**Comment by Chriz007** [comment]
The setting page looks good so far! And I completely understand.

**Comment by Chriz007** [comment]
Also, are any of the toggles functional yet?

**Comment by jakejarrett** [comment]
Notification toggling works. repost toggling just breaks the entire stream view (Either nothing shows or things are just missing)

**Comment by RampageJack21** [comment]
subscribing to this.  this seems interesting

**Comment by RampageJack21** [comment]
For issue #344, a toggle to "always scroll to song when not in view" seems like it would belong in this settings page.  If it ends up being implemented.

**Comment by weblancaster** [comment]
@jakejarrett please do not add the feature to `auto scroll` to track, this was implemented to tracks in Queue list

**Comment by 17inginos** [comment]
Cool
