### ISSUE TITLE
[Enhancement] Songs that do not appear

### ISSUE THREAD

**Issue by jllodra** [Soundnode/soundnode-app#386]
Hi,

please take a look at this artist (app/index.html#/profile/25028100 - or just search for "XeviaN - STUDIO EVIL"). There are a lot of songs from the artist that do not appear, but the request (as seen in the Network dev tab) is returning more songs:

![image](https://cloud.githubusercontent.com/assets/273590/10026957/c6f82686-6164-11e5-8f87-f61df75e139c.png)

and the artist page shows 8 tracks only:

![image](https://cloud.githubusercontent.com/assets/273590/10026979/debb80a6-6164-11e5-866b-f9234c7950cb.png)

I did not take a look at the source yet and wanted to ask here first, maybe it's a duplicate or known issue.

Best

**Comment by Pitros** [comment]
Please check if track which don't appear on the list have in returned json data streamable: true.

**Comment by jllodra** [comment]
yes, streamable: false.

I googled about it but couldn't find anything, do you know why is that?
Those unstreamable songs are available for purchasing, could this be the reason?

**Comment by weblancaster** [comment]
@jllodra yes, tracks with streamable false can't be playable/streamed therefore we shouldn't display the track in the App

**Comment by Pitros** [comment]
Using API V2 we can access stream urls, but I don't know if it is right to do that if streamable is false for unknown reason.

**Comment by jllodra** [comment]
When the unstreamable song is in a playlist, it shows up, but it cannot be played back, so the playback stops and you have to manually restart it *sigh*.
FIX: the track could be hidden within the playlist as well, but hey, what if I want to know what songs are on my playlist? A setting like "Show unstreamable songs grayed out", as spotify does, is interesting.

No idea about the API V2 and the stream_urls. Why is the stream url there if the song is supposed not to be streamed? :smile:

**Comment by Pitros** [comment]
Scripts on SC website access to that api call which returns json with mp3 links, but reaching SC Devs to ask them can we use that is almost imposible. After a month and three tries they answered me in using API V2 with simple yes.

`https://api.soundcloud.com/i1/tracks/67579991/streams?client_id=02gUJC0hH2ct1EGOcYXQIzRFU91c72Ea&app_version=fb374fe`

**Comment by weblancaster** [comment]
That makes sense @jllodra changing from bug to enhancement.

**Comment by jllodra** [comment]
Do you accept PRs for that (the playlist issue)? I might have a look at it...

**Comment by Pitros** [comment]
@jllodra Everyone can post PRs, if PR will be fine it will be merged.

**Comment by jllodra** [comment]
Great, pull request #391 solves the problem with unstreamable songs appearing in playlists.
I'll try to add a new setting to show those tracks grayed out, now that I see there's a new place in soundnode for settings.

**Comment by weblancaster** [comment]
cool @jllodra 

Now I will close this issue and you start a new one related to disable tracks not streamable.
