### ISSUE TITLE
[UI Bug/Enhancement] "Liked" Tracks in Stream aren't highlighted

### ISSUE THREAD

**Issue by codeanpeace** [Soundnode/soundnode-app#394]
Tracks that you had previously liked that are still on the Stream page don't display an orange heart icon.

Version: 0.5.7
Downloaded from: soundnodeapp.com
OS: Mac OS X Yosemite 10.10.5

How to reproduce:
 - Open Soundnode App
 - Click on "Stream" under "MAIN"
 - Like a song
 - Click on "Likes" under "MAIN"
 - Click on "Stream" under "MAIN"

Actual result:
 - Song that was liked does not have an orange heart anymore

**Comment by weblancaster** [comment]
This was fixed/added and will be release on next version @codeanpeace

**Comment by codeanpeace** [comment]
Awesome!
How does updating work with Soundnode? Thanks

**Comment by weblancaster** [comment]
@codeanpeace you will get the notification when the next version is available. thanks.
