### ISSUE TITLE
[Enchancement] Allow copy/paste to work on the search bar

### ISSUE THREAD

**Issue by Chriz007** [Soundnode/soundnode-app#395]
Just realized there was no option to copy/paste to the song's search bar ._.

**Comment by jakejarrett** [comment]
Which OS? Mac requires edit to be enabled in menubar for copy paste.

**Comment by Chriz007** [comment]
This is mac that I'm referring to

**Comment by jakejarrett** [comment]
I'll make a pull request tonight with a fix.

**Comment by Chriz007** [comment]
^ thanks
