### ISSUE TITLE
Option to drag tracks from the 'likes' page to group them

### ISSUE THREAD

**Issue by Chriz007** [Soundnode/soundnode-app#396]
Add an option to drag tracks from the 'likes' page to self group them. I'm not sure if this is possible or not, but its just an idea!
![option to drag tracks](https://cloud.githubusercontent.com/assets/12990919/10127660/89396fb8-655a-11e5-921e-7e179d1bf6bd.jpg)

**Comment by weblancaster** [comment]
This is called playlist @Chriz007

**Comment by Chriz007** [comment]
Well.. I know that.. but this is something different. Let me see if I can explain this.. 
So, I have some tracks by [Artist 1] that I've 'liked'. But I also 'liked' other songs by other [artist 2] as well. Since the songs from [Artist 2,3,4 ect] occupy that space by [Artist 1], once I've liked other tracks that have come out by [Artist 1], they are no longer next to each other. So in other words, I want it organized. Another benefit to this that if I do want to play all the songs I like at a party or something, I can have them playing in a uniformed fashion, so the songs by [Artist 1] don't interfere with the style of [Artist 2]. 

I know there is a 'Playlist' functionality, but since I have songs by many, many artists in my 'likes' page, I would rather not spend the time putting them all in a playlist folder.

**Comment by weblancaster** [comment]
@Chriz007 No reason to have an feature to organized them that way.. it's much easier and more organized if a playlist is created instead.

What can turn into a new feature is filters (artist name, songs, date, etc)
