### ISSUE TITLE
[FEATURE SUGGESTION] Support right-click playback control

### ISSUE THREAD

**Issue by chrismessina** [Soundnode/soundnode-app#398]
SoundCleod happily supports [dock icon right-click playback control](https://github.com/salomvary/soundcleod/issues/62); since SkipTunes doesn't integrate w/ Soundnode-app (I'll file that separately), it'd be super handy if it were easier to control playback by right-clicking on the icon. Additionally, I think this would open up UI scripting so I could use an Alfred.app Workflow to setup globabl keyboard shortcuts.

*SoundCleod's right click menu*

![image](https://cloud.githubusercontent.com/assets/22610/10206854/faca8ef8-677d-11e5-8ca1-e4e358da36b5.png)

**Comment by Chriz007** [comment]
Don't know about this.. to be honest, I think changing tracks with the keyboard is easier.

**Comment by chrismessina** [comment]
Right — but how do you do that if the app isn't in focus?

**Comment by weblancaster** [comment]
Don't your keyboard has media player shortcuts @chrismessina
