### ISSUE TITLE
[FEATURE SUGGESTION] Support SkipTunes playback control

### ISSUE THREAD

**Issue by chrismessina** [Soundnode/soundnode-app#399]
I love using [SkipTunes](http://skiptunes.com/) as my universal playback controller. It'd be sweet if it could support Soundnode too. I'm not sure who needs to do what, but I reached out to SkipTunes's developer @gregdougherty to see. 

Wanted to file this issue here to track this request.

![image](https://cloud.githubusercontent.com/assets/22610/10207010/c64e0e7e-677e-11e5-81d4-fa443da89532.png)

**Comment by Chriz007** [comment]
This seems pretty interesting..
