### ISSUE TITLE
[FEATURE] Change song in toolbar.

### ISSUE THREAD

**Issue by AustinAbel** [Soundnode/soundnode-app#400]
The user should be able to: Go back a song, Go forward a song, Pause the song, See title and author of song from the lower toolbar in Windows.

**Comment by Pitros** [comment]
Lower toolbar? What's that?

**Comment by AustinAbel** [comment]
Taskbar or toolbar. Its the area which displays open applications and time. It can be used to operate Soundnode if implemented correctly.

**Comment by eigenstil** [comment]
I think @AustinAbel means this option/possibility, which you can see in the VLC Screenshot: if you hover over the application icon in then windows taskbar, it shows these 3 icons, which are clickable and do what you expect:
![windows-taskbar-icons](https://cloud.githubusercontent.com/assets/13272281/10690425/2176383e-7982-11e5-8fbb-6dcecbf4a8c9.jpg)

**Comment by eigenstil** [comment]
Why was this closed?

**Comment by weblancaster** [comment]
yes, we won't be implementing the toolbar sorry.
