### ISSUE TITLE
Add an Equalizer?

### ISSUE THREAD

**Issue by Chriz007** [Soundnode/soundnode-app#401]
I've told 4 of friends about this app, and they really enjoy it. One of them suggested if I could ask the developer and the other coders if they can implement an equalizer, so I'm asking you guys if this is possible or not. I know for sure MyCloudPlayer has one though, so I guess it is possible.

**Comment by jakejarrett** [comment]
This *is* possible. I can create an EQ plugin for soundnode. I'll look into how it affects overall performance.

**Comment by Skkiz** [comment]
Though an equalizer would be cool to play around with.. I don't think that is what we should implement just yet. I would like for the soundnode development "team" to work on the following first.

#291  Option to repost tracks & show other reposted tracks from artists 
#297  Auto-refresh stream
#347  "Explore" feature
