### ISSUE TITLE
Use MPRIS for Linux

### ISSUE THREAD

**Issue by taaem** [Soundnode/soundnode-app#404]
On Linux you can use an interface called MPRIS2 for controlling music its a freedesktop.org (http://www.freedesktop.org/wiki/Specifications/mpris-spec/metadata/) standard and used in all major desktop enviroments (Unity, Gnome, Plasma).
A NodeWebkit App which uses MPRIS2 is here https://github.com/twolfson/google-music-electron/ That would be nice for all linux users since it would also enable keyboard shortcuts, etc...

Greetings

**Comment by jakejarrett** [comment]
@taaem I can give this a shot over the weekend. I've been interested in implementing this feature

**Comment by jakejarrett** [comment]
Just an update on this, Spent some time on it today & got pretty decent support on it so far (Need to work on passing through soundnode functions to mpris)

Should have something ready shortly :+1:

**Comment by taaem** [comment]
Great just tested your changes on plasma 5 and it works! Now it just need to be merged
