### ISSUE TITLE
[Bug] Tracks shuffle even though the option is turned off

### ISSUE THREAD

**Issue by Chriz007** [Soundnode/soundnode-app#405]
Songs don't play the next track automatically. Instead they indefinitely shuffle forever, even if the shuffle feature is turned off

**Comment by weblancaster** [comment]
@Chriz007 I'm going to take a look on it

**Comment by Skkiz** [comment]
I also encounter the bug @Chriz007 has pointed out. Although it happens infrequently, I still get it sometimes.

**Comment by Skkiz** [comment]
I also believe its because the Queue lists the songs differently than what it shows on the stream, therefore it shuffles it
