### ISSUE TITLE
Logging in with Google doesn't work

### ISSUE THREAD

**Issue by Moppko** [Soundnode/soundnode-app#407]
I can't log in using Google. When I click the sign in with google button a new empty window opens up but nothing happens. This is really unfortunate because I'd love to try out the app and don't want to make a new soundcloud account that doesn't use google. I am on Windows 10.

![image](https://cloud.githubusercontent.com/assets/9677311/10418253/37a5069c-7056-11e5-858b-8f5e253fbcbd.png)

**Comment by Chriz007** [comment]
hmm. Thats odd. What OS are you using? Have you tried deleting the entire app along with the folders that come with it?

**Comment by Moppko** [comment]
I'll try that right now.

**Comment by Moppko** [comment]
Ok, it's working. That was to easy, thank you ^^

**Comment by Chriz007** [comment]
No problem! You can close this issue now
