### ISSUE TITLE
[Bug] cmd + click open new blank tab

### ISSUE THREAD

**Issue by weblancaster** [Soundnode/soundnode-app#412]
A friend discovered that when cmd + click just like in the browser, Soundnode App actually opens a new blank tab that is because it's a single page app (running on a browser) and the path is the local user.

Anyway.. to fix just "preventDefault" on cmd + click.

**Comment by jakejarrett** [comment]
Also affects linux if you control + click. Should affect windows too.

**Comment by weblancaster** [comment]
Yep

**Comment by eigenstil** [comment]
@jakejarrett yes, affects windows too, just verified that ;-)
