### ISSUE TITLE
[Discussion-Feature] Visualizer for Soundnode

### ISSUE THREAD

**Issue by Chriz007** [Soundnode/soundnode-app#414]
I'm going to leave a link here to show what I mean: http://sendvid.com/kxhjo7de

I'd was thinking a visualizer would be perfect for soundnode. I wonder if this is possible and if anyone has experience with this. I was thinking you could track how many BPMs a song has to give it various colors to change along with the beat. Of course, it doesn't have to be like the example I showed above, but it could be something along the lines of it.

Example 2)

![visualizer](https://cloud.githubusercontent.com/assets/12990919/10571801/70b06eda-75f7-11e5-8bb3-0775740232e7.jpg)

Example 3)

![visualizer 2](https://cloud.githubusercontent.com/assets/12990919/10572073/b26b200c-75f9-11e5-90b6-402223fbeb32.jpg)

**Comment by weblancaster** [comment]
I vote as a no.. visualizer have been outdated for a while now.. nobody will keep watching it specially because it's a Desktop App.

**Comment by Skkiz** [comment]
@weblancaster What do you mean visualizer has been outdated for a while? The code for it? I'm utterly disappointed you said "no" to this. @Chriz007 idea sounded pretty darn awesome if it was implemented. 
I was imagining some kind of visualizer similar to a game called "Beat Hazard". The best/most accurate visualizer that plays any music you play. If this is a code kind of problem, maybe you can contact this guy, and somehow transfer that code or something into this application. As for performance problems, people can just have the option to turn it off. But.. I guess I'll just have to stick to music channels that have visualizers to satisfy myself. :/

**Comment by Skkiz** [comment]
By the way @Chriz007 I like your design of the second one. Hopefully, if this topic can be picked back up again, I'd vote for some kind of design like that! Sorry this idea didn't go through! I would have loved to have it. I'm sure others would love this too.

**Comment by Chriz007** [comment]
Thanks @Skkiz for your input. I'm disappointed @weblancaster isn't planning on adding this. I've had this idea for a while, but really thought this should be added since the visualizers I see on some channels look sick when playing a really good song. Especially on Monstercat. *sigh*

**Comment by MindCntrl** [comment]
Oh, that's a bummer. However, I think you are generalizing a bit there @weblancaster how
"Nobody will keep watching it specially because it's a Desktop App"

**Comment by weblancaster** [comment]
Sorry disappoint you guys @Chriz007  @Skkiz @MindCntrl but this feature isn't a "must have" or anything close to that level.. when I say it's a desktop app I meant by it's an music desktop app..

Most people are listening to songs and doing something else.

@Skkiz the code isn't a problem.. I can code that any time but I'm concern about the quality of the App in the long run.

Still a no.
