### ISSUE TITLE
[MINOR BUG] Liking a song from tracklist does not update the (heart symbol) in streamview

### ISSUE THREAD

**Issue by RampageJack21** [Soundnode/soundnode-app#416]
Windows 7 x64 Enterprise
Official release 0.6.0

Steps to reproduce:

1. hit play on stream view
2. wait for a song which hasn't been liked to come on and click the track list button
3. hover over the 'i' 
4. hit like
[green popup message appears indicating the song was successfully saved to likes]
[heart is still grey]

heart becomes red when you switch to "likes" tab and switch back to "stream" tab

expected result:  heart becomes red without having to switch out of stream view

**Comment by weblancaster** [comment]
#424 closes this one.
