### ISSUE TITLE
[Enhancement] Improve the players now playing bottom bar

### ISSUE THREAD

**Issue by eigenstil** [Soundnode/soundnode-app#418]
Referencing issues #417 and #259 there are some more improvements to make in the "now playing" bottom bar:

* clicking on the **track name** should take the user to the track view in soundnode (just like clicking on a trackname in the stream view)
* clicking on the **cover** should take the user to the track view in soundnode (just like clicking on a trackname in the stream view)
* clicking on the **artist name** should take the user to the artist view in soundnode (just like clicking on the artist name in the stream view)

**Comment by weblancaster** [comment]
#410 closes this one. Thanks for the feedback @eigenstil
