### ISSUE TITLE
[BUG] Liking song(s) from stream and then Playing from Likes does not play correct queue

### ISSUE THREAD

**Issue by jakejarrett** [Soundnode/soundnode-app#426]
Steps to reproduce-
1) Like a song on stream
2) Go to likes view/page
3) Play the song you just liked
4) Press next

It should play the next song in likes, but plays the next song from stream.

**Comment by weblancaster** [comment]
Yes.. if the song you liked in stream is playing and then you go to likes view that is expected because the queue doesn't know the user wants a new queue list from likes..
