### ISSUE TITLE
Stuck in authentication

### ISSUE THREAD

**Issue by nm4d** [Soundnode/soundnode-app#431]
I just cloned the git repository and executed the installation steps in your Development wiki, yet when I open the app/index.html file I seem to be stuck in "Authenticating your Soundcloud account" even though I never entered my username or password. What am I doing wrong?

I am using Firefox on Ubuntu Gnome 14.04 LTS.

**Comment by Pitros** [comment]
Please set `toolbar` to `true` in `app/package.json`, and run app once again but now check if in dev tools  are there any errors in console.
