### ISSUE TITLE
Replace jshint with eslint

### ISSUE THREAD

**Issue by weblancaster** [Soundnode/soundnode-app#435]
Since we started to use ES2015 with React we need to replace jshint with eslint

**Comment by sergeylaptev** [comment]
@weblancaster Hi! When are you planning fully migrate to React? What is your tech stack?

**Comment by weblancaster** [comment]
@sergeylaptev that will take some time, because one so far I'm the only one that pushed React code so far.. two I have a bunch of todo's for work.

But at this time I'm working on setup React Stack starter kit at work, so I'm just going to use the same ESlint I put in the project there
