### ISSUE TITLE
Keyboard function keys do not control playback

### ISSUE THREAD

**Issue by ryanvade** [Soundnode/soundnode-app#439]
I grabbed the latest version from http://www.soundnodeapp.com/ (64bit) and my laptops function keys do not control playback. Everything else is fine.  I'm on Manjaro Linux with GNOME 3.18.

**Comment by jakejarrett** [comment]
This is related to #422 Linux needs mpris support for keyboard shortcuts

**Comment by pwittchen** [comment]
I am not sure, if it's the same issue, but playback controls via Gnome Pie app also doesn't work on Ubuntu Linux.

**Comment by jakejarrett** [comment]
This is a duplicate of #404

mpris integration should resolve the issue (closing as its a duplicate, continue discussion in #404)
