### ISSUE TITLE
[Bug] Queue list dropdown nav is overlapped

### ISSUE THREAD

**Issue by weblancaster** [Soundnode/soundnode-app#440]
Bottom right side, the dropdown nav in Queue list is overlapped.

![screen shot 2015-11-10 at 3 08 31 pm](https://cloud.githubusercontent.com/assets/549394/11075859/24b782b6-87bd-11e5-8356-1c0c562e3d80.png)

**Comment by jakejarrett** [comment]
This should be fixed by setting the z-index higher than everything else?

**Comment by weblancaster** [comment]
@jakejarrett will work for the items a bit farther from the bottom but let's say for the latest item in the list although the z-index might fix the layer issue won't fix the height

**Comment by mradionov** [comment]
I've picked it up and will provide a fix soon.

**Comment by weblancaster** [comment]
This is now released.
