### ISSUE TITLE
Media keys don't work on Windows 10

### ISSUE THREAD

**Issue by PachowStudios** [Soundnode/soundnode-app#442]
I'm using SoundNode on Windows 10 with a Razer BlackWidow Chroma keyboard, and none of the media keys work.

They work perfectly on for any other app that uses media keys, so the issue must be SoundNode.

**Comment by weblancaster** [comment]
@PachowStudios do you have any App open that uses the media keys?

**Comment by PachowStudios** [comment]
No, but it shouldn't matter. If I ever do have multiple apps open that support media keys, they both respond.

**Comment by Kuenstler** [comment]
I partly can confirm this issue.
I'm on W10, too and had this issue as I first tried soundnode (a few weeks ago)

Yesterday I downloaded the latest version and the media keys are working!

**Comment by PachowStudios** [comment]
Currently on v0.6.0 and I still have this issue.

**Comment by Kuenstler** [comment]
It matters, if an app, which already use media keys, is already running
Tried it with chrome (with media keys addon) and soundnode:
The app which is started first, (only) grants media keys access.

**Comment by Nightshaxx** [comment]
Can confirm this is an issue. Chrome with media keys is not the issue. I have turned off the extension, and it still doesn't work. Additionally, I can run music bee and chrome w/ media keys , and as long as I am not playing music on chrome music bee still gets the media key input.  Using Logitech G105 keyboard and Logitech G502 mouse. Windows 10

**Comment by weblancaster** [comment]
@PachowStudios @SLiX69 @Nightshaxx can you check if #705 solution can solve your issue?

**Comment by narc0tiq** [comment]
For Logitech keyboards, I've found that convincing SetPoint to stop touching the media keys fixes it -- [instructions on SuperUser](http://superuser.com/a/888413) (might be a bit techy)

**Comment by weblancaster** [comment]
@narc0tiq thanks for letting us know.
