### ISSUE TITLE
[Feature] Highlight & copy text, any text

### ISSUE THREAD

**Issue by thinking-sc** [Soundnode/soundnode-app#443]
I think it'd be useful to have the ability to highlight text anywhere within the SoundNode window to copy to the Windows clipboard.  I often find myself copying tracks from tracklists for later and find it frustrating to have to open the permalink to a mix, copy, close the tab, and go back to SoundNode.  Is it possible to make this a simple add within the SoundNode app window?

**Comment by mradionov** [comment]
@weblancaster , is there any reason behind disabling test selection? I see that there is a CSS prop `-webkit-user-select: none; ` set for `body`.

**Comment by weblancaster** [comment]
Ha I did that because I wanted to give a more native app experience.. very often you can select text in native apps.

**Comment by mradionov** [comment]
Yeah, it's true. Maybe selection can be enabled only for text content like artist names, track names, descriptions, tags, comments, etc?

For example, if you drag cursor across the application window (trying to select everything), only text content will be selected.

![image](https://cloud.githubusercontent.com/assets/2007370/11854212/7a80efae-a453-11e5-8e10-22729a6c6501.png)
![image](https://cloud.githubusercontent.com/assets/2007370/11854228/938ca9d4-a453-11e5-995b-cb127530b15e.png)

**Comment by Pitros** [comment]
Imho text select still should be disabled at least for most part of the app.
Profile, description might be selectable, as well track name, comments but only on track/artist page, that will be compromise between native app experience and giving possibility to copy something eg track title. 
Accidently selected track view would he hard to deselect as well that would look as crap. 

To toggle ability to select text, simple css class will do the work.

**Comment by weblancaster** [comment]
I added this feature.

**Comment by weblancaster** [comment]
This is now released.

**Comment by thinking-sc** [comment]
:+1:  :clap:
