### ISSUE TITLE
[Feature] Play button in track details

### ISSUE THREAD

**Issue by thinking-sc** [Soundnode/soundnode-app#444]
Would it be possible to have a play button within the track details window?  For example, we can click the track's icon to play it in the stream/playlist view.  But if I click the title to open the track's page, there appears to be no way to play the track without backing out and clicking the icon.  Can the same play functionality be implemented, for example, as shown below, by clicking on the track image within the track details?

![capture](https://cloud.githubusercontent.com/assets/15896597/11224708/f17209e2-8d3b-11e5-9313-27ad602b51bc.PNG)

**Comment by eigenstil** [comment]
+1

**Comment by Chriz007** [comment]
good idea

**Comment by christopherturner** [comment]
:+1:
