### ISSUE TITLE
[BUG] Playlist stays in the list after removal

### ISSUE THREAD

**Issue by mradionov** [Soundnode/soundnode-app#457]
When I remove a playlist, it tells me that playlist is removed, but it is still in the list after that. Even if I reload the page or go to another page and come back - it is still here. If I go to SoundCloud website - playlist is removed in there. But API still returns it as existing playlist. It happens for multiple deletions too - if I remove two or three, they are still present. They disappear only when I create a new playlist, then on the playlists page I get an actual list without deleted ones.

**Comment by weblancaster** [comment]
I noticed this too.. I'm going to fix it.

**Comment by weblancaster** [comment]
Ok, after dig more on this bug I found out it's actually a Soundcloud bug.

Even if I try to remove using the Soundcloud website doesn't work.. we are good then (I'm just going to let the users know).
