### ISSUE TITLE
Quick Question about the application

### ISSUE THREAD

**Issue by Chriz007** [Soundnode/soundnode-app#461]
Hey to all who can help me. I want to put soundnode on my hotbar for windows, but there seems to be no way to do so. I know that if you install applications with a setup.exe file, you can put those apps in the hotbar. 

Also, I would also like to change the icon for the soundnode application, but there seems no way to do so. I searched online for answers, but to no avail. What kind of files does windows accept for icon replacement? .ico? Because I tried that and windows said it was invalid. Thanks!

<img width="1314" alt="screen shot 2015-12-07 at 1 28 50 pm" src="https://cloud.githubusercontent.com/assets/12990919/11640316/cb9a6812-9ce6-11e5-97ac-517a9dca4c16.png">

Error it gives me when I try to set a icon.ico as the apps icon :

<img width="1314" alt="screen shot 2015-12-07 at 1 36 44 pm" src="https://cloud.githubusercontent.com/assets/12990919/11640500/9baff116-9ce7-11e5-9b19-b4e4b20731b0.png">

**Comment by Pitros** [comment]
All you need is just proeper `.ico` file and it should work. But i'll make pull request with added icon so with new relase Windows version will have it's own icon too.

Here's working ico: https://dl.dropboxusercontent.com/u/25785523/ShareX/2015/12/soundnode.ico

**Comment by weblancaster** [comment]
closed by #465
