### ISSUE TITLE
Linux build won't open on Linux Mint 17.2 XFCE

### ISSUE THREAD

**Issue by zestyr** [Soundnode/soundnode-app#463]
Nothing happens when I try launching the program. If I try running it via the terminal, I get the following message.

> Soundnode-App: error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory

The previous version works fine.

**Comment by wb9688** [comment]
You must install libnotify with something like `sudo apt-get install
libnotify`
Op 8 dec. 2015 09:03 schreef "Zestyr" <notifications@github.com>:

**Comment by zestyr** [comment]
I tried that, but it isn't in the package repositories.
> E: Unable to locate package libnotify

**Comment by jakejarrett** [comment]
I think it's called libnotify-bin on mint

**Comment by zestyr** [comment]
> libnotify-bin is already the newest version.

Well..

**Comment by jakejarrett** [comment]
Are you using 64bit or 32bit?

**Comment by zestyr** [comment]
64bit

**Comment by jakejarrett** [comment]
can you run this command to test if you do have libnotify.so.4

```bash
locate libnotify.so.4
```

**Comment by zestyr** [comment]
> ~/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libnotify.so.4
~/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libnotify.so.4.0.0
~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libnotify.so.4
~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libnotify.so.4.0.0
/usr/lib/x86_64-linux-gnu/libnotify.so.4
/usr/lib/x86_64-linux-gnu/libnotify.so.4.0.0

**Comment by jakejarrett** [comment]
Hm odd. it should be running fine. I'll check this out when i have some free time this week.

**Comment by wb9688** [comment]
Does it works after you do `sudo ln
/usr/lib/x86_64-linux-gnu/libnotify.so.4 /usr/lib/libnotify.so.4`?
Op 8 dec. 2015 19:05 schreef "Jake Jarrett" <notifications@github.com>:

**Comment by zestyr** [comment]
Nope, still same error.

**Comment by jakejarrett** [comment]
Are you using the latest version of mint?

**Comment by wb9688** [comment]
@jakejerett No, he says he is using Mint 17.2, and a few days ago 17.3 came
out.

@zestyr What if you go to the dir where Soundnode is installed and run `cp
/usr/lib/x86_64-linux-gnu/libnotify.so.4 .`? Does it works then? Else,
what's the output of `export`?
Op 9 dec. 2015 06:49 schreef "Jake Jarrett" <notifications@github.com>:

> Are you using the latest version of mint?
>

**Comment by zestyr** [comment]
Tried it, still same error.

Here's my export: http://pastebin.com/6BYZdMnk

**Comment by wb9688** [comment]
Are you using the 64 bit version? Does it work after you do `ldconfig` (with sudo???)? Else try executing `export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/`...

**Comment by zestyr** [comment]
Oh, it seems I accidentally downloaded the 32-bit version. Sorry!
(the new scaling works perfectly by the way, it was terrible before)
