### ISSUE TITLE
[Bug] Stream view empty with latest release 0.6.1

### ISSUE THREAD

**Issue by RampageJack21** [Soundnode/soundnode-app#468]
![win7_enterprise_soundnode_ver0 6 1](https://cloud.githubusercontent.com/assets/9271427/11732215/e23723b8-9f56-11e5-9f44-ff0bded04ef9.JPG)

Has anyone run into this issue?  After updating to the latest version, upon first opening the app, stream view had items (i distinctly remember album artwork that was not there yesterday).  

Tracks in the "Likes" tab still show up.  

I had paused the app a couple times since updating and just noticed this issue when no new music was playing.  Is there anything system information i can provide that would help narrow down the problem before i reboot my system?   A soundnode log of some sort?

If no experiments, then I will reboot my system to see if i can reproduce it again.

**Comment by jakejarrett** [comment]
To get an output of errors, Press control+/ and it will bring up chrome dev tools, Switch over to console and it should have the errors

**Comment by jakejarrett** [comment]
@RampageJack21 Can you check on  soundcloud.com if this is also occuring? There was an issue on soundcloud for me where i would only see my own tracks / reposts

**Comment by mradionov** [comment]
I thought it might be the issue with SoundCloud V2 api, but I've downloaded latest version from the website and also checked master build - I get the results for stream in both cases.

**Comment by jakejarrett** [comment]
There was an issue with soundcloud today, It should be fixed now.

http://status.soundcloud.com/

**Comment by RampageJack21** [comment]
no longer seeing this today.  Havent rebooted.  I think it was the issue @jakejarrett mentioned.
