### ISSUE TITLE
[Bug] Reset size parameters on launch

### ISSUE THREAD

**Issue by Chriz007** [Soundnode/soundnode-app#469]
<img width="1314" alt="screen shot 2015-12-11 at 10 25 06 pm" src="https://cloud.githubusercontent.com/assets/12990919/11760609/1fbd0ab8-a056-11e5-8e26-9366ceb5dc57.png">

**Comment by weblancaster** [comment]
We have that as a feature to remember the window size when the user come back.. you can disable that on settings.

**Comment by Chriz007** [comment]
No what I mean is whenever I open the application back up, it resets the window size to that. I set it back to what it was originally, but it still does that

**Comment by weblancaster** [comment]
It's working fine here.. when I close the app saves the state (width) and when I open again I have the old state when I closed.

**Comment by Chriz007** [comment]
Ah, I forgot to mention that this only happens when I reboot my computer. It works fine after I open/close it again. But if I turn off my computer and turn it back on, and open the application, it changes its size

**Comment by Chriz007** [comment]
I'm going to close this issue. I think it may just be my computer itself

**Comment by Pitros** [comment]
@Chriz007 this also happens to me, so that's not an issue with your computer. I'll check that later, because that's really annoying, and it probably ony happens on Windows.

**Comment by weblancaster** [comment]
Thanks @Pitros
