### ISSUE TITLE
[Feature] Compact view

### ISSUE THREAD

**Issue by mradionov** [Soundnode/soundnode-app#471]
Some of the audio players I've used have a so called compact view, where only the most important action buttons and information is displayed. The window itself can be displayed on top of other windows on the desktop to be always accessible. Also the window can be moved around the desktop. It gives fast GUI access to app features.

Sample illustration:

![image](https://cloud.githubusercontent.com/assets/2007370/11763687/5e7e980a-a125-11e5-9c08-986810ad2aa3.png)

I am not sure if it can be really useful, a lot of users use global shortcuts to control playback, but it may be a nice-to-have feature, if it is relatively easy to implement from nw.js side.

**Comment by Pitros** [comment]
#209, as @weblancaster said, he doesn't want to support that.

**Comment by weblancaster** [comment]
#360 is the particular one.. #209 is more about the adaptive part when resizing.
