### ISSUE TITLE
It doesn't work anymore :-(

### ISSUE THREAD

**Issue by wb9688** [Soundnode/soundnode-app#474]
I only get this:

![Soundnode](http://i.imgur.com/FfLEVGi.png)

**Comment by Pitros** [comment]
Please go to settings and clear local storage, then run app one more time and post results.

**Comment by wb9688** [comment]
It works now. Thanks, Piotr Cholewa!
Op 21 dec. 2015 13:48 schreef "Piotr Cholewa" <notifications@github.com>:
