### ISSUE TITLE
State of playing/paused only changes when I hover other song

### ISSUE THREAD

**Issue by PatriqDesigns** [Soundnode/soundnode-app#476]
For example the music is now paused and I according to the playbar it's playing (because I can pause).
![2015-12-23_00-55-41](https://cloud.githubusercontent.com/assets/3120671/11969334/f1ce1490-a90f-11e5-8b52-a650209028b8.jpg)

Upon hovering other song the bar updates to the current state, in this cause with the song paused because I paused it in the beggining.
![2015-12-23_00-54-39](https://cloud.githubusercontent.com/assets/3120671/11969326/ccc16b52-a90f-11e5-9f5e-421ceb095765.jpg)

As you can see is the same song playing.

Thank you very much!

**Comment by weblancaster** [comment]
This is fixed and will be on the next release

**Comment by weblancaster** [comment]
This is now released.
