### ISSUE TITLE
Update Brew Cask

### ISSUE THREAD

**Issue by theaccordance** [Soundnode/soundnode-app#481]
The current brew cask listing for the app is at v 0.5.7, if one of you guys initially added it to the registry, can you update it to the current version?  

If not, I can dive into the docs and pitch in, figured I'd ask the question first to save time.

**Comment by weblancaster** [comment]
@theaccordance I didn't even know we had Soundnode up there and I don't think none of us (core team) had uploaded that.

**Comment by theaccordance** [comment]
Okay, I'll look into it.  It's not an upload from what I understand, just a listing for the package

**Comment by mdtusz** [comment]
@weblancaster looks like the cask package is pointing to `http://www.soundnodeapp.com/downloads/mac/Soundnode-App.zip`, but I see that on the downloads page, the OSX link is to `http://goo.gl/wDlo2c`.

If this is or can be changed to a static url for all future releases, I'd be happy to update the cask to reflect it.

**Comment by theaccordance** [comment]
have at it :)

**Comment by weblancaster** [comment]
@mdtusz I will change to a static link.. I don't need short link version anymore.

I will get back to you once I do that.

**Comment by weblancaster** [comment]
I updated the website to use the absolute link.. let me know if that works

**Comment by mdtusz** [comment]
It will pull the latest version when a user installs, but `brew update` doesn't know that there's a new version so to upgrade, you need to manually `brew cask uninstall soundnode` then reinstall. 

This could be added to your release step to bump the version in the brew cask, or just make a note maybe in the README.

**Comment by mdtusz** [comment]
The cask for soundnode doesn't have a version specified so `brew cask update` won't properly update. 

You can work around this by using

```
brew cask uninstall soundnode
brew cask cleanup
brew cask install soundnode
```

but it's not ideal. If the maintainers can just bump the version number of [this](https://github.com/caskroom/homebrew-cask/blob/master/Casks/soundnode.rb) on each release, it should all work though.
