### ISSUE TITLE
[Feature] Auto load next tracks if last loaded element is playing

### ISSUE THREAD

**Issue by SLiX69** [Soundnode/soundnode-app#483]
Hi, if I start playing and the last track in 'Stream' ends (not scrolling down), no further tracks are loaded and the music stops. I have to scroll down to the bottom to load new tracks. I'm using 0.6.1 on Windows.

So it would be great if there are only a few songs left to hear, the next/older tracks will be loaded automatically (in the background), so the music doesn't stop.

**Comment by weblancaster** [comment]
I agree that feature need to be implemented.

**Comment by weblancaster** [comment]
This was implemented and will be added to the next release.

**Comment by weblancaster** [comment]
This is now released.

**Comment by SLiX69** [comment]
Thanks for that, does work very well!
