### ISSUE TITLE
[Feature] Resume last played song

### ISSUE THREAD

**Issue by LoreGas** [Soundnode/soundnode-app#484]
In my opinion it would be cool to save the song and minute that you are playing so that when you open the app again it will resume from where you left

**Comment by edisonchee** [comment]
Seems trivial. The SoundCloud track resource is a JSON object which has track duration attribute, of which the app is already making use

**Comment by weblancaster** [comment]
Feel free to work on it @edisonchee

**Comment by christopherturner** [comment]
This would be nice; looking forward to seeing it implemented.

**Comment by edisonchee** [comment]
@weblancaster I've given this a go, 2448efd8c0f530a4e7a8369aa895651ac359add9. I've only tested it on OSX; if anyone could test it on Linux or Windows that'd be great. Maybe @LoreGas or @christopherturner can help?

**Comment by LoreGas** [comment]
Is this in the new version or where can I download to test?

**Comment by edisonchee** [comment]
If you're familiar with git, you can add my fork as a remote and merge with a branch from your own fork. Otherwise, give me some time to test it on Linux and Windows and hopefully I can do a PR for this feature.

**Comment by weblancaster** [comment]
Nice work @edisonchee can you open a PR though? and besides descriptive title also put closes #484 on the title.. thanks
