### ISSUE TITLE
Failed [Native media keyboard shortcuts] Linux

### ISSUE THREAD

**Issue by ronaldoats** [Soundnode/soundnode-app#488]
Failed in Linux.
Manjaro 
Linux lnxSMJ 4.2.8-1-MANJARO #1 SMP PREEMPT Tue Dec 15 08:34:13 UTC 2015 x86_64 GNU/Linux
Desktop --> Cinnamon 2.8.6

**Comment by nebulade** [comment]
Duplicate of #445
