### ISSUE TITLE
close to the system tray

### ISSUE THREAD

**Issue by ronaldoats** [Soundnode/soundnode-app#489]
Seria bien que haga eso.
System Tray.

**Comment by thiboot** [comment]
Hey,
It would be a great thing if we could close or minimize to the tray :-)

**Comment by ELKOKACOLO** [comment]
Yes, definitely this would be useful or maybe even to minimize to a little player into a corner of the screen like AIMP3 does.

**Comment by ronaldoats** [comment]
Hey!!! this code is for Tray Icon for soundnode-app

code in "**app/public/js/system/guiConfig.js**"

after from 
`// Store the GUI window
guiConfig.getGUI = gui.Window.get();`

Insertar este código :smile: 

`// Tray Icon for System
var tray = new gui.Tray({ title: 'Tray', icon: 'soundnode.png' });

// Give it a menu
var menu = new gui.Menu();

var visible = false;
// Controlar visibilidad al dar click sobre el icono
tray.click = function(){
  if(visible){
    guiConfig.getGUI.hide();
  }else {
    guiConfig.getGUI.show();
  }
  visible=!visible;
};

// Anexamos un boton de Salir al Menu del TrayIcon
var menuitem = new gui.MenuItem({ label: 'Salir [X]' });
menu.append(menuitem);
menuitem.click = function() {
    guiConfig.getGUI.close(true);
};

// Menu for Try Icon
tray.menu = menu;

**Comment by ronaldoats** [comment]
haría un Fork al código pero es mas tardado y quienes quieran tener el Tray Icon estare compilando uno para que puedan descargarlo hasta esperar a que el sr. Lancaster tenga la versión oficial compilada y con un Tray Icon mas genial.

**Comment by ronaldoats** [comment]
unoficcial versión with Tray Icon
[http://bi-ni.com/Applications/soundnode-app/linux32.tar.gz](url)
[http://bi-ni.com/Applications/soundnode-app/linux64.tar.gz](url)
[http://bi-ni.com/Applications/soundnode-app/osx64.tar.gz](url)
[http://bi-ni.com/Applications/soundnode-app/win32.tar.gz](url)

**Comment by weblancaster** [comment]
@ronaldoats is there anyway you can use english (maybe a translator)?

also, please do not share the code directly here you can send pull requests for that.. another thing is do not share your own version here.

for those reasons I'm closing this issue, since doesn't follow any good practice and doesn't help none of us to solve the problem.

**Comment by ronaldoats** [comment]
Hi, sorry I'm not very good with English.
