### ISSUE TITLE
App CSS does not load - initial installation

### ISSUE THREAD

**Issue by cdtinney** [Soundnode/soundnode-app#494]
Hi, 

First time attempting to install and and run this application. Running into a problem where the CSS does not load. See attached picture.

Windows 7 x64.

Is there a step I may have missed? No errors logged
![soundnode_bug](https://cloud.githubusercontent.com/assets/3266047/12518275/ab5aa0f6-c105-11e5-9ae3-9d1671670ac2.png)
 when installing or running.

**Comment by cdtinney** [comment]
Beginning of the "npm install" output indicates some warnings:

npm WARN deprecated lodash@0.9.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN prefer global jshint@2.8.0 should be installed with -g
npm WARN prefer global node-gyp@3.2.1 should be installed with -g

**Comment by weblancaster** [comment]
@cdtinney those are just warnings.. so nothing to worry about.

Now try running `grunt dev` that should build the css files.

**Comment by cdtinney** [comment]
Works now - thanks a lot. Missed that step - my apologies.

**Comment by weblancaster** [comment]
no problem

**Comment by cdtinney** [comment]
Is it possible to have the application update its views if I modify CSS without relaunching?

Or do I just keep "grunt watch" running continuously and close/open the application each time I make a change?

Sorry if this is not the right place to ask questions.

**Comment by Pitros** [comment]
@cdtinney use `location.reload()` in console (inside Dev Tools)

**Comment by weblancaster** [comment]
@cdtinney So far we haven't add anything to reload automatically.. but what I do is just open the devtools and refresh (command + R).. or I do the changes in the devtools then copy over to the original file
