### ISSUE TITLE
[FEATURE REQUEST] Needs a better icon

### ISSUE THREAD

**Issue by CaioBianchi** [Soundnode/soundnode-app#498]
It's barely visible right now on my dock. Plus, it doesn't resemble SoundCloud at all.

![screen shot 2016-01-24 at 10 56 27 pm](https://cloud.githubusercontent.com/assets/681326/12542178/ce3c927a-c2ed-11e5-907a-3d4e33fa0356.png)

**Comment by weblancaster** [comment]
We are working on changing the icon.. and we are not trying to resemble Soundcloud we just use their API to be able to build the Desktop App.

**Comment by christopherturner** [comment]
:+1:

**Comment by Riotherio** [comment]
This!

**Comment by AhmedAtef07** [comment]
+1

**Comment by wb9688** [comment]
There's already #295 for this... Can someone (@weblancaster?) close this issue?
