### ISSUE TITLE
header icons are ovals not circles

### ISSUE THREAD

**Issue by contra** [Soundnode/soundnode-app#499]
![](https://cldup.com/XnlFTnma3u-3000x3000.png)

looks kind of wonky

**Comment by weblancaster** [comment]
Mac or Win? @contra

**Comment by weblancaster** [comment]
nvm.. I just noticed on Mac..

**Comment by weblancaster** [comment]
this fix will be released in the next version.. thanks @contra

**Comment by weblancaster** [comment]
This is now released.

**Comment by Chriz007** [comment]
Wow, @weblancaster you've really been hustling this past week. Good to see all the improvement added to the app. Loving your work man!
