### ISSUE TITLE
Settings for HTTP Proxy.

### ISSUE THREAD

**Issue by atanasbozhkov** [Soundnode/soundnode-app#502]
It would be nice if we could configure a http/s proxy. This would make it usable for all those people sitting behind corporate firewalls.
Would it be straightforward to add a setting that we can tweak in a config file?

Furthermore - when I launch the app from behind a firewall it just comes up with a blank screen. It might be good to implement a simple connectivity check and display an error message instead.

**Comment by DarrylD** [comment]
i agree, this would be an awesome

**Comment by jmackhh** [comment]
I too think this would be outstanding...
