### ISSUE TITLE
[Improvement] Remove song from Playlist

### ISSUE THREAD

**Issue by vulture916** [Soundnode/soundnode-app#518]
Not sure if this was intentional or not, but it is sort of a pain when trying to remove multiple songs from a playlist:

After removing a song from a specific playlist, Soundnode takes you back to a list of all playlists, rather than staying in the current playlist.

**Comment by weblancaster** [comment]
This is intentional @vulture916 we reload the view to "get" the latest. I guess we can improve that not reloading the view (I changed the title to improvement) and just remove the track from the list.

**Comment by vulture916** [comment]
Right on - forgive the misclassification. This is my first "contribution" to any sort of project (I'm just learning to code, but love finding bugs) because your app is awesome. 

Keep up the great work, man!

**Comment by weblancaster** [comment]
Thanks a lot for the feedback @vulture916

**Comment by weblancaster** [comment]
this is done and will be released in the next version.. thanks @vulture916

**Comment by weblancaster** [comment]
This is now released.
