### ISSUE TITLE
[BUG] Next/Prev hotkeys on Mac moves queue twice

### ISSUE THREAD

**Issue by satyakb** [Soundnode/soundnode-app#519]
When using the cmd + right and cmd + left hotkeys on a Mac, the queue moves forward/backward twice, instead of just once. This behavior is only 

Version: Release 0.5.7 for Mac
Downloaded from: soundnodeapp.com
OS: Mac

How to reproduce:
 - Open Soundnode App on a Mac
 - Play any song
 - Hit "cmd + right"
 - Hit "cmd + left"

Actual result:
 - It skips forward two songs and then skips backward two songs (instead of just one and one)

**Comment by weblancaster** [comment]
@satyakb we are not maintain version 0.2.7 anymore.. I would suggest download the latest version.

**Comment by satyakb** [comment]
Sorry, I forgot to change that part of the template in CONTRIBUTING.md. I'm actually using version 0.5.7 for Mac.
