### ISSUE TITLE
[INSTALL] How to install this from source code (ubuntu 64 bit)?

### ISSUE THREAD

**Issue by daxlab** [Soundnode/soundnode-app#521]

**Comment by weblancaster** [comment]
https://github.com/Soundnode/soundnode-app/wiki/Development let me know if you have any problem.. cc ( @jakejarrett )

**Comment by jakejarrett** [comment]
@weblancaster I'll make a new VM and write down the dependencies needed :+1:

**Comment by weblancaster** [comment]
Aren't you on Linux @jakejarrett ?

**Comment by jakejarrett** [comment]
@weblancaster Yeah, but it'd be easier to write down which ones would be needed if i start from scratch (EG/ @daxlab might not have webpack installed)

**Comment by weblancaster** [comment]
got it @jakejarrett cool.. thanks!

**Comment by jakejarrett** [comment]
for grunt build to pass, You need webpack & grunt-cli install  globally.

I'm using nvm w/ Node v5 installed on the VM, and i get some errors (async missing)

Only need to add webpack to the requirements to build :+1:

**Comment by weblancaster** [comment]
great thanks a lot @jakejarrett

**Comment by mikeboy91** [comment]
Just cloned the repo and tried to build the app. I'm sitting on a relatively new installation of Kubuntu 16.04 (64 Bit). I just wanted to say that I had to install pkg-config and libdconf-dbus-1-dev and the node package nw-gyp to complete the build without errors.

`sudo apt-get install pkg-config libdconf-dbus-1-dev`
`sudo npm install -g nw-gyp`

Wanted to share this information. Might be helpful for other people :)
