### ISSUE TITLE
[Feature] Add charts

### ISSUE THREAD

**Issue by extensionsapp** [Soundnode/soundnode-app#522]
Hi.

Nice app!

Add charts - https://soundcloud.com/charts/top

**Comment by weblancaster** [comment]
I've never used (or seen) the charts section before.. looks pretty good so I will add to Soundnode soon

**Comment by weblancaster** [comment]
This is now released @extensionsapp

**Comment by extensionsapp** [comment]
Thank you @weblancaster. However, the choice of genres would be in great demand.

**Comment by weblancaster** [comment]
I will add filters for the next release.. this is a quick solution.

**Comment by cenderin** [comment]
You read my mind on the top 50, if you get genres up I think it will be very helpful for the app to get more people using it :).
