### ISSUE TITLE
[FEATURE SUGGESTION] Offline Syncing

### ISSUE THREAD

**Issue by christopherturner** [Soundnode/soundnode-app#527]
Similarly to how Spotify can sync content locally for playback without an internet connection, a nice feature for future implementation in Soundnode would be offline syncing/playback.  One could do this song-by-song, for all of the songs in a particular playlist, or for all of the uploads by a particular user.

Thanks for all of the hardwork so far :+1:  Thoughts?

**Comment by kjutbring** [comment]
This will violate the API terms of use of Soundcloud. See under "Caching and Downloading". https://developers.soundcloud.com/docs/api/terms-of-use
