### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by hassanzayan** [Soundnode/soundnode-app#529]
when mouse hovers on a album artwork instead of the current pop up play button, use the new webkit blur filter together with a fade animation (-webkit-backdrop-filter: blur(10px);), this adds a transparent blur like in iOS and OSX. Also maybe add an option for different tile sizes.

Just noticed that when a track is on repeat the app downloads the track every time it repeats, might be troubling for users who have limited bandwidth.

**Comment by weblancaster** [comment]
Interesting.. let me explore that some time.

**Comment by Pitros** [comment]
Backgdrop-filter starting from Chromium 46 is hidden behind flag, as well we're currently running Chromium 41, so we can't use it right now (first we need to move to nw.js 0.13 or electron.js).

Different size titles was mentioned before and it's still good idea, as well as list display for tracks.

**Comment by weblancaster** [comment]
@hassanzayan We can do nothing when the user have to repeat the track and Soundnode download again.. we have to stream the track from Soundcloud.. we can not download and store anywhere.
