### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by krishnanandreddy** [Soundnode/soundnode-app#530]
Allow us to add new songs to now playing instead of playlist.

**Comment by weblancaster** [comment]
did you mean the queue list as now playing? if so you are able to do that by clicking.

**Comment by iDuuck** [comment]
But then the whole queue is replaced with the list the song is currently in. It's a playing queue as Spotify has it.

**Comment by krishnanandreddy** [comment]
weblancaster - What I mean is instead of adding a song to playlist while listening to another song, Allow us to add to "now playing" queue just like windows media player. And also background play if possible.

**Comment by valevalorin** [comment]
I personally wanted this feature so I made a fork and finished it:  https://github.com/valevalorin/soundnode-app

But I don't know if there's interest in merging it into the primary repo. If there is I'll put in a PR and we can get a code review going.

**Comment by weblancaster** [comment]
@valevalorin you need to open a PR and then the team can take a look and test your work.
