### ISSUE TITLE
[FEATURE REQUEST] Full screen on mac

### ISSUE THREAD

**Issue by jghyllebert** [Soundnode/soundnode-app#531]
At the moment it is not possible to use this app in Full screen mode.

If possible, this function should be able to be run with the shortcut "CMD + ^ + F", which is what the major apps seem to be using (eg. Chrome, Spotify, Skype, ...)

**Comment by Ajeey** [comment]
What's the shortcut on Spotify? I tried "CMD + ^ + F" and nothing happens!
Chrome works on "Control + Command + F"

**Comment by dgattey** [comment]
This would be awesome. Native fullscreen is supported by NW.js. If I have some time in the next few weeks, I'll attempt a PR.

**Comment by wb9688** [comment]
And on Windows with F11?
Op 4 feb. 2016 00:44 schreef "Dylan Gattey" <notifications@github.com>:
