### ISSUE TITLE
[FEATURE SUGGESTION] Support LastFM API / Audioscrobbler

### ISSUE THREAD

**Issue by bob6664569** [Soundnode/soundnode-app#543]
It would be great to sync played tracks & loved ones with the LastFM API ! 

See http://www.last.fm/fr/api/scrobbling

**Comment by weblancaster** [comment]
Sorry @bob6664569 but we are focusing on Soundcloud only.

**Comment by bob6664569** [comment]
Wait but... Lastfm isn't a streaming service. It's just used to keep tracks of the music you play on various supports (ie. feature supported in Spotify, on VLC, Banshee, and even some hifi players like Onkyo) : each time you play a song, you send the artist & title to the audioscrobber service for statistics, and that's it ! 
It would be really cool if we could keep tracks of the songs we play through SoundNode :+1:

**Comment by weblancaster** [comment]
@bob6664569 I'm aware of that... but at the moment there is no plan to integrate with anything else.

This might change as soon as the major Soundnode feat are in place.

**Comment by bob6664569** [comment]
Alright ! Hope so, then you'll count me in :)
