### ISSUE TITLE
error while loading shared libraries: libgconf-2.so.4

### ISSUE THREAD

**Issue by IonicaBizau** [Soundnode/soundnode-app#546]
I downloaded the app, `unzip`ped and ran `./Soundnode-App`.

Getting the following error:

```sh
./Soundnode-App: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
```

I tried to solve it by running `sudo apt-get install libgconf-2-4`, but the error is still there.

I'm using Ubuntu 15.10, 64bit.

**Comment by wb9688** [comment]
What's the output of `ls /usr/lib|grep libgconf`?
Op 27 jan. 2016 17:13 schreef "Ionică Bizău" <notifications@github.com>:

**Comment by jakejarrett** [comment]
I don't think we have any gnome utilities as a dependency, was this downloaded from soundnodeapp.com?

**Comment by IonicaBizau** [comment]
@wb9688 Just nothing.
@jakejarrett Yes, I downloaded the zip file and unzipped and ran the executable.

**Comment by jakejarrett** [comment]
Turns out chrome requires libconf now, is this 32 or 64bit version of soundnode?

**Comment by wb9688** [comment]
@jakejerret it's 64bit, see issue start
Op 27 jan. 2016 21:44 schreef "Jake Jarrett" <notifications@github.com>:

**Comment by jakejarrett** [comment]
I meant the application, not the OS haha.

**Comment by wb9688** [comment]
@jakejarrett Haha, indeed he must run the 64bit version, because 32bit applications (normally) don't work on 64bit Linux...

**Comment by IonicaBizau** [comment]
>  is this 32 or 64bit version of soundnode?

Ahhh, turns out that I downloaded the 32bit version, not 64. :smile: Sorry guys for confusion. Nice project, btw! :grin:
