### ISSUE TITLE
Make the website open-source 

### ISSUE THREAD

**Issue by ahmedlhanafy** [Soundnode/soundnode-app#554]
Make the website open-source so people can come out with better design for it

**Comment by weblancaster** [comment]
at some point was.. I will make available again.

**Comment by wb9688** [comment]
@weblancaster And what about the sc-redirect.herokuapp.com (without the
SoundCloud API keys)?
Op 28 jan. 2016 00:10 schreef "Michael Lancaster" <notifications@github.com

**Comment by weblancaster** [comment]
@wb9688 that one I will keep private.

**Comment by weblancaster** [comment]
Done. you can find the website here https://github.com/Soundnode/soundnode-website
