### ISSUE TITLE
[Suggestion] Permalink URL has "?client_id=*some_numbers_here*" at the end of the URL

### ISSUE THREAD

**Issue by chrisatanasian** [Soundnode/soundnode-app#558]
When clicking on the permalink button in Soundnode, a link in the browser is opened. The URL is normal except that it has `?client_id=*some_numbers_here*` at the end of it, making it annoying to copy paste the URL to other people.

Version: Release 0.5.7 for Mac
Downloaded from: soundnodeapp.com
OS: Mac OS X El Capitan 10.11.2 64bits

How to reproduce:
 - Open Soundnode App
 - Click on "permalink" button on any song
 - Wait for browser to open URL
 - See that the URL has `?client_id=*some_numbers_here*` at the end of it

**Comment by weblancaster** [comment]
I updated your title to suggestion since this is not a bug. Also you can always remove the numbers if that annoys you. thanks,

**Comment by chrisatanasian** [comment]
@weblancaster: Ah, I thought it was unintentional. Why exactly is this a feature? I don't see why users would want their client_id to show up in the URL, and this is a one or two line fix.

**Comment by weblancaster** [comment]
that's not a feature but to be able to see the link from an third party app you need the client id there.. I can't see that being a problem

**Comment by chrisatanasian** [comment]
I'm not sure what you mean. If we go to `openExternalLinkDirective.js` and change the second part of the if statement (line 15 at the moment) to `el = attrs.href;` the link works fine. Am I missing something?
