### ISSUE TITLE
[Bug] Log out button doesn't work. 

### ISSUE THREAD

**Issue by Cuvinisme** [Soundnode/soundnode-app#561]
I get sent out to the previous application I used, but music is still playing and I'm logged in. Also, the cursor does not change to a hand on hover.

**Comment by Pitros** [comment]
Are you sure, that you're running latest version of Soundnode? It was fixed a while ago.

**Comment by Cuvinisme** [comment]
Downloaded the version which is on this page like 30 min ago. http://www.soundnodeapp.com/
It's version 0.5.7 (0.5.7) - using the mac client

Is that the latest one? If not, where can I get the latest one?

**Comment by Pitros** [comment]
The latest one is 0.6.2 so its really outdated. Those links should give you the latest version, I don't know what could happen.
@weblancaster

**Comment by PhernandoPhelix** [comment]
I am having the same issue. I am stuck on 0.5.7 version. The link of the Mac client on http://www.soundnodeapp.com is linking to the 0.5.7 version and not to 0.6.2. 

I really don`t know what to do to update... =/

**Comment by weblancaster** [comment]
Can you guys go to the website and refresh until you see the image on the right of this link https://github.com/Soundnode/soundnode-app/commit/442575bfad7153cab56a55804f290cd29a02104f

if you are seeing the image on the left your browser cached the website.

**Comment by weblancaster** [comment]
Oh you are actually right.. we all missed that. You can go to top right side and click on the gear icon then click in about you will see the latest version at the bottom of the modal that opened.

Also, I tried to log out although it does log me out since the app doesn't shut down completely it keep me logged in until I force to close.

**Comment by weblancaster** [comment]
this was fixed while ago.
