### ISSUE TITLE
[FEATURE SUGGESTION] Do likes with click on heart, update count

### ISSUE THREAD

**Issue by phw** [Soundnode/soundnode-app#562]
Clicking on the heart icon next to the likes of a song should actually perform the like action. Currently this only works with the like button in the upper right corner. Also Increasing the like should immediately update the like count.

Here is an animation to make this more clear:

![peek 2016-01-28 21-16](https://cloud.githubusercontent.com/assets/29852/12657593/6706fca2-c604-11e5-8c3f-29ff0fed464a.gif)

In case this is supposed to already work and it is a bug instead: I am running Soundnode 0.6.2 on Gnome 3.18, Arch Linux

**Comment by Pitros** [comment]
No, it's not supposed to work, I never thought that someone would click that heart to like a track... 
Liking track as well is paired with button.

**Comment by vladjerca** [comment]
I can take care of this and implement the feature.
