### ISSUE TITLE
Wrong styling when the name is long on the profile menu

### ISSUE THREAD

**Issue by ahmedlhanafy** [Soundnode/soundnode-app#563]
![screen shot 2016-01-28 at 10 52 27 pm](https://cloud.githubusercontent.com/assets/7052827/12658482/f89961ac-c611-11e5-81d0-906d1ae7372e.png)

**Comment by weblancaster** [comment]
First.. what a long name my friend.. second we will fix that for the next release

**Comment by cenderin** [comment]
Fixed this, not sure if thats the way you want it fixed.  I can change it if you want something specific.

**Comment by weblancaster** [comment]
Closed by #566
