### ISSUE TITLE
Can't move window

### ISSUE THREAD

**Issue by fille97** [Soundnode/soundnode-app#585]
System: OSX 10.10.5
Soundnode: 0.5.7

To reproduce:
- I move the window so that the bottom of the software is below the screen
- I resize the top of the software and drag it further down
- Now I can't move around the software to make the PLAY-button visible again
- By pressing the green button in upper left corner the software is resized to fill my whole screen and I can once again move around the software on my screen.

Nothing is written to the console.

**Comment by weblancaster** [comment]
@fille97 you probably need to select the `top orange bar` and before move up-down try moving sideways.

Let me know if that helps.

**Comment by fille97** [comment]
@weblancaster Thanks for your reply. Yes, pulling the small orange line right or left, makes it possible to move the window. But I don't think that behavior feels intuitive. 
Would you like to keep these kind of "logical bugs", or shall I close this issue?

**Comment by weblancaster** [comment]
Yeah I agree with you @fille97 that's not ideal but for now let's keep this way if more people complain I will do something about it.. thanks.
