### ISSUE TITLE
Implement min-width & min-height

### ISSUE THREAD

**Issue by Ajeey** [Soundnode/soundnode-app#586]
The app should have a min-width and min-height. Below which it should not scale down. 
[try spotify app as an example].

Any suggestions on what is a sensible min width and height ?

**Comment by Pitros** [comment]
Min-height and min-width already exists, and are set respectivly to 710px and 350px. We only need to change them to better ones (somewhere near 690x600 for me).

**Comment by edisonchee** [comment]
Wouldn't a common aspect ratio of 16:9 be better?

**Comment by mathiash98** [comment]
@edisonchee there is no point to lock it to 16:9 minimum format, the point is to avoid users from scaling it down to the matter where functions gets hidden.

**Comment by weblancaster** [comment]
I agree with @mathiash98

**Comment by edisonchee** [comment]
Ah, I see. That's true :)
