### ISSUE TITLE
[FEATURE SUGGESTION] (Managable) Play Queue

### ISSUE THREAD

**Issue by TAHassing** [Soundnode/soundnode-app#587]
First off thanks a lot for this great app. Love it! :)

My suggestion would be to add a 'Play Queue' functionality, that would appear on the left side menu list (under 'MAIN'). Song/tracks/playlists can then individually be added to this queue to create a desired order of playback. Clicking on the 'Play Queue' entry on the left side entry would display the current queue, and give the user the ability to manipulate this list (add/(re)move/replace songs).

**Comment by weblancaster** [comment]
Hey @TAHassing thanks for the feedback.. I'm glad you liked Soundnode.

Now, you are already able to do that on the Queue list on the right side, see below.

![screen shot 2016-02-01 at 11 49 47 am](https://cloud.githubusercontent.com/assets/549394/12725778/f68c4684-c8d9-11e5-854b-e4af43eb4719.png)

**Comment by TAHassing** [comment]
Right, it seems that I'm a complete moron ;) Thanks for the response, keep up the awesomeness.

**Comment by weblancaster** [comment]
No worries.. It's actually a flaw that we don't have a way to tell the users the various shortcuts we have.. I will add this improvement in the next version.

Thanks.
