### ISSUE TITLE
[FEATURE SUGGESTION] Arrow key integration

### ISSUE THREAD

**Issue by roeeaizen** [Soundnode/soundnode-app#594]
Allow user to:
Use left arrow key to go to the previous track
Use right arrow key to go to the next track
Press Alt+Left arrow key to go to the previous page viewed (similar to web browsers)
Press Alt+Right arrow key to go to the next page viewed (also similar to web browsers)

**Comment by weblancaster** [comment]
we have shortcuts in place already @roeeaizen 

`ctrl/cmd + left` or `ctrl/cmd + right`
