### ISSUE TITLE
[BUG] The tracks after loading more liked list are duplicated

### ISSUE THREAD

**Issue by sjntn** [Soundnode/soundnode-app#599]
In liked list, the tracks after loading more are duplicated like below.

![loading_more_liked_list](https://cloud.githubusercontent.com/assets/3044172/12734397/9526363e-c983-11e5-973b-4523eaca4862.gif)

Application Version: 0.5.7
Mac OS: 10.11.1

**Comment by weblancaster** [comment]
this issue is duplicated #564
