### ISSUE TITLE
[Feature] add a copy to clipboard button next to the permalink

### ISSUE THREAD

**Issue by weblancaster** [Soundnode/soundnode-app#604]

**Comment by Ajeey** [comment]
You mean here right ?
<img width="473" alt="screen shot 2016-02-03 at 5 07 59 pm" src="https://cloud.githubusercontent.com/assets/1799117/12781182/ce9528e2-ca98-11e5-8871-2ea104631475.png">

**Comment by weblancaster** [comment]
Yep and also here 
![image](https://cloud.githubusercontent.com/assets/549394/12786724/e683256c-ca57-11e5-8810-335d51ed1349.png)

**Comment by Ajeey** [comment]
I can implement this. Suggestions on images to be used would be helpful.

**Comment by weblancaster** [comment]
@Ajeey we don't use images we use font-icons (https://fortawesome.github.io/Font-Awesome/icons/) in this case you can try using http://fortawesome.github.io/Font-Awesome/icon/clipboard/

**Comment by Ajeey** [comment]
Awesome, thanks.
