### ISSUE TITLE
Only 50 playlists ... !!??

### ISSUE THREAD

**Issue by devirto** [Soundnode/soundnode-app#605]
"Playlists" list contains (shows) only 50 of them and I got more than 80 (atm) how to access (listen) the others 30 and more (and counting lol) Can you fix this please Thanks and keep up good job :)

App v.0.6.2 
Win10Pro 64bit

**Comment by cenderin** [comment]
Thats interesting, the api doesn't have a limit that I can find.  Not sure why only 50 is showing.  seems like a bug of some sorts.  I don't have an account with 50+ playlists to test this and fix it tho...

**Comment by devirto** [comment]
Sorry but no way to show you , have to believe me ... and I need this to be fixed, please

**Comment by Pitros** [comment]
Uh, @weblancaster probably didn't expect that somebody may have so many playlists, so app fetches only ~50 playlists, and there's no function to get more (for now at least).

**Comment by cenderin** [comment]
@Pitros I don't see where its limited to 50~, is there some sort of dashboard that you can set that?

**Comment by Pitros** [comment]
@cenderin probably that's default value for SC API, setting param `limit=XX` might work (200 is max for likes, dunno how it works for playlists) but you can also do `linked=partitioning=1` so you will get link to next api call with rest of playlists.

**Comment by devirto** [comment]
Hey it's good to see you all working on this Thanks guys ;-) 
I really appreciate this.

**Comment by cenderin** [comment]
For sure, the fix I added is tiny but I think it will work.

**Comment by devirto** [comment]
Can I test it ?

**Comment by cenderin** [comment]
Only way to do that would to be clone my branch, build the app, and then open it up and check.  Or I could send you a build with my fix in it, email is on my page.

**Comment by devirto** [comment]
You can send me a build with your fix in my email , much easier I think

**Comment by devirto** [comment]
I just found another issue ... show it here or ... !!?

**Comment by cenderin** [comment]
Make a new issue in my opinion.

**Comment by devirto** [comment]
FYI ... 0.6.3 playlists window is EMPTY , all the playlists are gone now

**Comment by weblancaster** [comment]
@devirto looks like it's fine.. check your network, if your playlists are private or streamable.

**Comment by devirto** [comment]
Network is fine, playlists are not private or streamable ...

![emptypllsts_181105](https://cloud.githubusercontent.com/assets/17032123/14066008/a5e0ec00-f447-11e5-9fea-dd0bd9c75800.jpg)

also LIKEs still show twice ... = no change till 0.6.2

**Comment by weblancaster** [comment]
No you shouldn't need to do that @devirto if you keep having that issue let me know please.

**Comment by devirto** [comment]
Sure

**Comment by devirto** [comment]
0.6.4 report 
... same as 0.6.3 "Playlists are starts to showing after I clean local storage, log out and log in again"
