### ISSUE TITLE
[FB login] direct password request?

### ISSUE THREAD

**Issue by lollox** [Soundnode/soundnode-app#606]
Hi

I just downloaded Soundnode for testing purpose, but the direct request to insert my Facebook credentials leaves me a bit hesitant ... in other apps (Spotify for example) they used a more (a lot more) secure and trusted method to login, simply asking (in the browser) to gain access to the profile, but the password is NEVER exposed to thirdy parts

I really suggest you to implement it

**Comment by weblancaster** [comment]
@lollox your password isn't exposed to Soundnode at any point.. when you see the screen to login that's actually Soundcloud's way to authenticate (if you go to their website logout and login again you will see it's the same).

If you are not comfortable in using the App I understand your choice.

**Comment by lollox** [comment]
[Just to discuss it]

it's a bit different. Apart my concerns of a nerdy user, when you use Soundcloud in a browser you see very well that on Facebook login you are on "https://facebook.com", and not on "http://fake-pishing.com" :P ... In an app like Soundnode you don't, and even if an addressbar would be implemented, you can't really trust it ;)

just my opinion of course... good work ;)

**Comment by weblancaster** [comment]
It's very simple @lollox if you are a nerdy as you say you would understand how api's work, also If you don't trust don't use it.

thanks
