### ISSUE TITLE
When a sing was liked, it doesn't shop up beneath

### ISSUE THREAD

**Issue by wb9688** [Soundnode/soundnode-app#607]
When a song was already liked and I listen to it, then the lower heart isn't colored orange.
![Screenshot](http://i.imgur.com/RSOVMgi.png)

**Comment by weblancaster** [comment]
Yeah @wb9688 I chose to left that out to ship the feature asap.. this will come to next version.

**Comment by weblancaster** [comment]
This is fixed and will be available in the next release.
