### ISSUE TITLE
Add track to Playlist

### ISSUE THREAD

**Issue by tseboho** [Soundnode/soundnode-app#608]
When adding a song that is currently playing to a Playlist, the song is skipped and the next song on the feed starts playing.

**Comment by dgattey** [comment]
Doesn't appear to be a problem in the latest version. To be clear, you start playing a song, then click the button below the song to add it to a playlist, and it skips to the next song in addition to adding it to a playlist? Which version of the app are you using on which platform?

**Comment by tsiiiboho** [comment]
It was the first version on OSX, the issue went away 2 updates ago.

**Comment by tsiiiboho** [comment]
This issue is back with the current version.

**Comment by tsiiiboho** [comment]
This issue can be solved by simply restarting the client.

**Comment by tsiiiboho** [comment]
The issue persists shortly after restart.

**Comment by weblancaster** [comment]
@tsiiiboho I'm going to try take a look during the weekend, thanks.
