### ISSUE TITLE
Update using Sparkle

### ISSUE THREAD

**Issue by dgattey** [Soundnode/soundnode-app#613]
Is there a reason why we're not using Sparkle on OS X for automatic updates so users don't have to navigate a website? It would be a slick addition and remove the need for update available text in the upper right.

**Comment by wb9688** [comment]
I think because it's Mac OS X only...
Op 4 feb. 2016 00:46 schreef "Dylan Gattey" <notifications@github.com>:

**Comment by iDuuck** [comment]
But what about https://www.npmjs.com/package/nw-updater?

**Comment by wb9688** [comment]
`nw-updater` isn't updated for a year and Soundnode is (probably) going to
migrate to Electron, which has a built-in updater...
Op 4 feb. 2016 15:22 schreef "Dominik Schmidt" <notifications@github.com>:

**Comment by weblancaster** [comment]
That's the ideal @wb9688
