### ISSUE TITLE
[bug] wrong cursor when hovering over song name in playlist add

### ISSUE THREAD

**Issue by rmf34** [Soundnode/soundnode-app#619]
wrong cursor when hovering over song name in playlist add

Version: Version 0.5.7 (0.5.7) OSX
Downloaded from: soundnodeapp.com
OS: OSX

Required setup:
 - must have a playlist
 - must have a "liked" track

How to reproduce:
 - Open Soundnode App
 - click likes in the left sidebar
 - click the ribbon to add to playlist
 - see list of playlists
 - hover over name of playlist
 - don't see cursor change
 - hover over line (not song name)
 - see hand cursor 
 - click and song is added 
 - Wait for song to start

Expected behavior:
 - should get visual feedback that clicking will perform action

**Comment by rmf34** [comment]
:+1:

**Comment by weblancaster** [comment]
Thanks reporting @rmf34 this is fixed and it's available in the next release

**Comment by rmf34** [comment]
thanks to @dgattey for fixing! love soundnode. keep it up hope to contribute down road.
