### ISSUE TITLE
Track not displayed in app 

### ISSUE THREAD

**Issue by theaccordance** [Soundnode/soundnode-app#630]
Version: 0.6.2
OS: Mac OS X 10.11.3
Downloaded: soundenodeapp.com

Description:
Tracks that are visible from SC's native platform are missing from views in the app.  I've confirmed this behavior in the likes view, but I believe this extends into other views as well. This [track](https://soundcloud.com/eric-prydz/eric-prydz-space-miami-2015) for example  does not appear in my [likes](https://soundcloud.com/theaccordance/likes).  

Screenshot from Web: Track is shown middle row, far right
![screen shot 2016-02-05 at 12 33 14 pm](https://cloud.githubusercontent.com/assets/1813001/12855396/ca450222-cc04-11e5-8047-e596b16b14f6.png)

Screenshot from App:  Track should appear middle row, between Black Tiger Sex Machine and Superheroes Anonymous 8
![screen shot 2016-02-05 at 12 33 22 pm](https://cloud.githubusercontent.com/assets/1813001/12855454/2d047fb4-cc05-11e5-80c4-9a4bb6ce0a43.png)

Steps to reproduce:
- Add [track](https://soundcloud.com/eric-prydz/eric-prydz-space-miami-2015) to likes using SC native platform 
- Reload soundenode app, check likes view 

Actual Result: Track is missing from view.

**Comment by weblancaster** [comment]
@theaccordance some tracks are not available for third party streaming so we don't show them in that case.
