### ISSUE TITLE
Update version displayed in app

### ISSUE THREAD

**Issue by theaccordance** [Soundnode/soundnode-app#631]
There's a view in the app where the version information is out of date.  

Version: 0.6.2
Platform: OS X 10.11.3
Downloaded from: official website

Steps to reproduce:
- From the top-menu bar, click Soundnode-app > About Soundnode

Result:
- View displays as version 0.5.7 instead of 0.6.2

Screenshots:
Accessing the view
![screen shot 2016-02-05 at 12 40 21 pm](https://cloud.githubusercontent.com/assets/1813001/12855596/05aeba82-cc06-11e5-95b1-10f51da98050.png)

View with wrong version info
![screen shot 2016-02-05 at 12 40 31 pm](https://cloud.githubusercontent.com/assets/1813001/12855601/0a44b362-cc06-11e5-841c-80eba0081244.png)

App's actual about view showing the accurate version info
![screen shot 2016-02-05 at 12 43 39 pm](https://cloud.githubusercontent.com/assets/1813001/12855645/30114088-cc06-11e5-99d1-963860f7297a.png)

**Comment by weblancaster** [comment]
I have updated a couple of days ago.. thanks @theaccordance
