### ISSUE TITLE
[Feature] GUI improvements

### ISSUE THREAD

**Issue by LoreGas** [Soundnode/soundnode-app#633]
- Close panel after interaction (Currently the volume panel needs to be manually closed same for the setting menu)
- (In Windows with the app maximized) if you put the mouse at the very top right corner it is not over the close button

**Comment by LoreGas** [comment]
Is not really a feature is it.. just realized :/

**Comment by christopherturner** [comment]
See enhancement #544

**Comment by weblancaster** [comment]
closing because it's duplicated.. thanks for posting here though.
