### ISSUE TITLE
New logo looks ugly in taskmgr

### ISSUE THREAD

**Issue by wb9688** [Soundnode/soundnode-app#634]
The new logo looks ugly in `taskmgr`:

![](http://i.imgur.com/FLlJEAf.png)

**Comment by jakejarrett** [comment]
I haven't used win10 much but it looks like a scaling issue with their rendering engine

**Comment by weblancaster** [comment]
Honestly.. I don't really care how the logo looks on the taskmgr.. But I appreciate the feedback.

**Comment by Pitros** [comment]
@weblancaster but logo doesn't look bad only in taskmgr
![image](https://cloud.githubusercontent.com/assets/6910670/12902803/b1b81aac-cec3-11e5-98d1-c56016ad2f70.png)
Icon that size looks really bad, probably too much details for icon, icon with less colors and less details would be better.

**Comment by weblancaster** [comment]
@pmarquees anything you can help us? what's your thoughts?

**Comment by Chriz007** [comment]
To be completely honest, does this really matter?

**Comment by pmarquees** [comment]
It might be something on the way I built it, nothing to do with having too many colors. Firefox's icon is here to prove this. 

I'll check if I did something wrong when saving the .ico file and get back here.

**Comment by weblancaster** [comment]
Can always be how Windows render the icons also which is common.

**Comment by wb9688** [comment]
Doesn't an .ico contain an image for every resolution? Then you can create
a simple low-res icon with a S instead of the nodes...
Op 9 feb. 2016 16:59 schreef "Michael Lancaster" <notifications@github.com>:

**Comment by Pitros** [comment]
I found main problem - .ico only has low-res logo not multiple (from 16x16 to 256x256). I've generated new ico and it looks much better. Here's comparsion: old, new, spotify.
![image](https://cloud.githubusercontent.com/assets/6910670/12925026/a67d07f8-cf5c-11e5-88b4-e0b0c17d1108.png)

And that's how it looks when you have really big icons. (new, old, spotify)
![image](https://cloud.githubusercontent.com/assets/6910670/12925060/d1aebbe2-cf5c-11e5-9012-758b3148b0fa.png)

And another one with clearly visible difference.
![image](https://cloud.githubusercontent.com/assets/6910670/12925115/0b138868-cf5d-11e5-8205-625f8cac6957.png)

@pmarquees Can you provide a higher res icon .png file (there's only 112x112px in repo), or you might make other PR and replace both `logo-short.png` and `logo-badge.png` which still are the old version of logo.

**Comment by pmarquees** [comment]
I'll do it today! Commit is on it's way! I'll also create a folder with all the assets related to the logo! Thanks @Pitros !

**Comment by brainscript** [comment]
**Another bug, kinda related to this:**
If you start Soundnode on Windows and pin it to the taskbar, you will see this icon (red):
![soundnodescreenshot](https://cloud.githubusercontent.com/assets/8706734/15483262/134bb662-2134-11e6-8f7a-26312dd9acf9.jpg)
If you unpin it again or hover over the taskbar icon, you can see the "normal" icon (green).

I think that's because the `.exe` file still contains this (old?!) compass icon. Please fix this. :smile_cat:

**Comment by wb9688** [comment]
That's the logo of nw.js, there was already a seperate issue for that…

**Comment by brainscript** [comment]
@wb9688 Didn't know that. :smile:
