### ISSUE TITLE
Doubled Likes

### ISSUE THREAD

**Issue by devirto** [Soundnode/soundnode-app#640]
After scrolling down a page or two 'Likes' starts to show twice 
Here's what Im talking about  > 

![sc-sn](https://cloud.githubusercontent.com/assets/17032123/12925283/46411b0e-cf66-11e5-8ecc-93626ac55387.jpg)

App v.0.6.2 
Win10 Pro 64bit

**Comment by Pitros** [comment]
Duplicated issue #564.

**Comment by devirto** [comment]
oops sorry
