### ISSUE TITLE
Your username should link to your page.

### ISSUE THREAD

**Issue by miketamis** [Soundnode/soundnode-app#642]
Your username in the top left corner should link to your page, as I would love to see what I have reposted.

**Comment by Ajeey** [comment]
Open the link in the browser or in the app?

**Comment by miketamis** [comment]
App, I love to play the songs I reposted.

**Comment by calvwng** [comment]
+1 for this feature request because my profile (specifically the list of my reposted songs) is always my first stop when I don't want to pick-and-choose songs from my Following Stream.
