### ISSUE TITLE
How do i play...

### ISSUE THREAD

**Issue by danielhq** [Soundnode/soundnode-app#644]
Hey, thanks for this awesome app, been using it since day 1.
One thing i always wondered, why there is no play button when I'm watchin a song page?
![screen shot 2016-02-12 at 15 41 43](https://cloud.githubusercontent.com/assets/1651415/13009886/22ca5344-d19f-11e5-8692-64e47fd0ebe2.png)
I have to go back to the previous screen and click on play

**Comment by weblancaster** [comment]
Hey @danielhq we have added this feat and will be released in the next version.. planned for beginning of next week

**Comment by weblancaster** [comment]
#444

**Comment by danielhq** [comment]
Oh sorry didn't see there was already

**Comment by weblancaster** [comment]
No problem @danielhq .. hard to see when was closed
