### ISSUE TITLE
[FEATURE SUGGESTION] Don't quit app on closing window

### ISSUE THREAD

**Issue by alexbw** [Soundnode/soundnode-app#647]
Would be great, like iTunes or Spotify, if music kept playing if the window was closed with Cmd+W on Mac, or equivalent on Windows.

**Comment by weblancaster** [comment]
We have that added and will be released in the next version

**Comment by alexbw** [comment]
This works when clicking the red "X" button, but not when using the shortcut "Cmd+W"

**Comment by weblancaster** [comment]
Sorry @alexbw but I did not release the next version yet.. I'm going to try to do this today.

**Comment by alexbw** [comment]
Ah, sorry!
