### ISSUE TITLE
[BUG] Duplicating tracks when I scroll down my LIKES to load more songs

### ISSUE THREAD

**Issue by Jmurray1018** [Soundnode/soundnode-app#655]
When I go into my 'LIKES' I scroll down to load more music, once the next group of tracks are loaded all them are doubled up. This also affects the random playlist that is generated causing all the songs in there to be doubled up as well
![screen shot 2016-02-19 at 3 51 56 pm](https://cloud.githubusercontent.com/assets/13137606/13188696/0683ffbe-d721-11e5-9087-25ede27320e3.png)

**Comment by weblancaster** [comment]
Thanks for reporting @Jmurray1018 but we already have an issue about this bug #564.. and someone is already working on fix for this.

**Comment by Jmurray1018** [comment]
oh awesome! thanks for the timely update @weblancaster !! I love the app and just want to see it improved

**Comment by SaahilMehta** [comment]
Issue is still occurring
