### ISSUE TITLE
Rainmeter Visualizer support?

### ISSUE THREAD

**Issue by Chriz007** [Soundnode/soundnode-app#656]
So I have this cool visualizer on my windows computer, and it works really well. Even though it picks up the sound, it doesn't pick up the **Song ID** and the **Track ID**. I'm not sure who would be the one responsible for changing/adding code into the app for it to work. Just give me your thoughts. Heres the website:
http://docs.rainmeter.net/manual/plugins/nowplaying#playerlist
https://www.rainmeter.net

<img width="1314" alt="screen shot 2016-02-14 at 11 43 04 pm" src="https://cloud.githubusercontent.com/assets/12990919/13191181/c899951a-d716-11e5-8d3c-452db4c95d4c.png">

**Comment by wb9688** [comment]
That would be nice indeed. Where did you download that Rainmeter skin or
did you make it yourself?
Op 19 feb. 2016 23:50 schreef "Chris" <notifications@github.com>:

**Comment by Chriz007** [comment]
Its the Monsterdcat Visualizer skin. Heres the download link if you want it.
http://marcopixel.deviantart.com/art/Monstercat-Visualizer-for-Rainmeter-1-3-486330771

**Comment by wb9688** [comment]
Thanks for that link!

BTW that must be done with either:

1. The Rainmeter team put that feature in Rainmeter
2. Someone makes a Rainmeter plugin for that
Op 20 feb. 2016 11:07 schreef "Chris" <notifications@github.com>:

**Comment by Chriz007** [comment]
Yeah, I emailed the team a while ago, they said they had no plans for it or probably won't in the future. I would have liked it but oh well.

**Comment by Dclyde747** [comment]
Darn, I was really hoping to be able to do this.
