### ISSUE TITLE
Refreshing page 

### ISSUE THREAD

**Issue by jbl92** [Soundnode/soundnode-app#659]
Hello, 

I just downloaded this soft yesterday, it's pretty cool but still some bugs I think.

When I am loading the tracks of a random artist all tracks are loaded proprely but when I scroll down to load more ... 
first problem: the tracks loaded appear dupplicated.
second problem: the sound navigator is too wide when I'm scrolling down with my mouse I  accidentally click at the end of the track.
thrid problem: when I decide to like a sound the "like mark" doesn't appear under the track image and at the bottow at the same time if I decide to click on this mark at one emplacement or the other
fourth problem; number of followers and following wrong. 
 
For more accuracy check the image below.

**Comment by jbl92** [comment]
![problemes](https://cloud.githubusercontent.com/assets/17500930/13361686/35feef5c-dc8e-11e5-8da8-597ff6036367.png)

**Comment by dgattey** [comment]
1) has already been fixed, just hasn't made it into a release. 2) is a design decision, but I can see how that might be tough to use. I'm working on a fix fo 3) at the moment, so stay tuned. Does 4) continue to be a problem when you open & close app?

**Comment by GamingOcto** [comment]
This is my first day using the program, and I'm still having the repeating songs when refreshing issue. It's really annoying since I can't just listen to an artist without getting repeats.
