### ISSUE TITLE
Shortcuts please ? 

### ISSUE THREAD

**Issue by jbl92** [Soundnode/soundnode-app#661]
Hello, 

This soft is cool , maybe some shortcuts could make it more pleasant ? 

Like in the original website : 

![sh](https://cloud.githubusercontent.com/assets/17500930/13364819/25305092-dc9f-11e5-844f-9699a5598ff1.png)

Thank you in advance.

**Comment by weblancaster** [comment]
We have a lot of shortcuts in place but no where the user can discover them.. this will be added in the next version
