### ISSUE TITLE
[FEATURE SUGGESTION] Option to hide the minimize/maximize buttons.

### ISSUE THREAD

**Issue by jamesbvaughan** [Soundnode/soundnode-app#674]
I run a tiling window manager and windows tend to look nicer without any minimize/maximize buttons, so it would be awesome to be able to hide them in Soundnode.

**Comment by Ajeey** [comment]
Where would the likely place for this option be? Settings tab?

**Comment by jamesbvaughan** [comment]
Yep, having it in the settings tab would be perfect!
