### ISSUE TITLE
Tracks are shown twice (OSX)

### ISSUE THREAD

**Issue by ddawson90** [Soundnode/soundnode-app#687]
I am using the Soundnode application on OSX and I found that quite often tracks are duplicated ie there are two of every track. This is especially annoying when you are trying to listen to tracks in order and each one plays twice. Can't work on any rhyme or reason for it but it seems that it affects older uploads.
![screenshot 2016-03-24 16 37 44](https://cloud.githubusercontent.com/assets/17260576/14009342/f8aa6120-f1de-11e5-9c95-545ceebd254d.png)
![screenshot 2016-03-24 16 38 03](https://cloud.githubusercontent.com/assets/17260576/14009343/f9994ef2-f1de-11e5-8387-11828be92c95.png)

**Comment by weblancaster** [comment]
This is duplicated #564
