### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by cirocosta** [Soundnode/soundnode-app#69]
Seems like everything is ok for running this on ubuntu-based linux distros *(tested on Linux Mint 16 - MATE desktop)*.

**It would be great if more people could test this**. I've been so happy by seing spotify supporting linux :P An opensource soundcloud client implementation supporting it as well would be awesome! 

For making it happen i just had to enable the build for linux64 at the `Gruntfile.js`, ran `grunt build` (which then generates a pure  `Soundnode-App.nw` at `/dist/releases/Soundnode-App`) and then openned it with `nw` for linux.

There's also something to be noticed: when building with `linux64` enabled an error is raised (*Fatal error: incorrect header check*) but that does not prevent the build.

**Comment by jakejarrett** [comment]
:+1: on supporting linux, I can start on bringing more native features to Linux. (Most of the native features are implemented in [MPRIS](https://www.npmjs.com/package/mpris-service)).

Latest version of nw.js w/ the ffmpeg from Chrome 43 works flawlessly after ~1 hour of testing

**Comment by taaem** [comment]
Any update on this?

**Comment by jakejarrett** [comment]
@taaem I've been working on linux support. I'll be doing a pull request once the application runs 100% smoothly for my testing (Pretty much there, Multimedia keys won't work)

**Comment by fidelisrafael** [comment]
@jakejarrett Good to know, keep us updated ;)

**Comment by cirocosta** [comment]
@jakejarrett @fidelisrafael  :+1:
