### ISSUE TITLE
Getting error - "Use of const in strict mode" after latest pull.

### ISSUE THREAD

**Issue by Ajeey** [Soundnode/soundnode-app#695]
Debugged and found out the line causing that  - const SONG_TIMEOUT_THRESHOLD = 3;

Whats the fix though ?

**Comment by jakejarrett** [comment]
@Ajeey where does this error occur? I'm unable to reproduce (Just playing songs & restarting some songs)

**Comment by dgattey** [comment]
Don't think this is an issue in the latest?

**Comment by weblancaster** [comment]
I haven't seen this issue when opening the app.. for that reason closing this issue.
