### ISSUE TITLE
The "shortcuts" button does nothing

### ISSUE THREAD

**Issue by zestyr** [Soundnode/soundnode-app#697]
When I click the "shortcuts (shift + ?)" button, nothing happens. I looked at the [code](https://github.com/Soundnode/soundnode-app/blob/d3bfbc0d3ce39ea8c8232542964fba39a560d5e3/app/public/js/components/header/settingsNav.jsx#L25) and it seems it just doesn't call anything. Why not? If it can be opened with the shortcut shift+?, it shouldn't be a problem opening it with the button.

**Comment by weblancaster** [comment]
Ha I just wanted to show the user how to use that way they can get the habit instead of going to the menu and clicking ;)

**Comment by zestyr** [comment]
Ah, alright, it was just a little bit confusing when clicking it did nothing :)

**Comment by dgattey** [comment]
This can be closed @zestyr
