### ISSUE TITLE
Play button stuck on ▸when track is playing

### ISSUE THREAD

**Issue by iRuisu** [Soundnode/soundnode-app#698]
Pretty much the pause button || is now broken.

**Comment by iRuisu** [comment]
Tbh, what did this latest 'update' even bring to the table? I love this application and appreciate the work that goes towards it but this update has only brought more bugs..

**Comment by weblancaster** [comment]
Hey @iRuisu can you describe the bug please?

**Comment by cyberhck** [comment]
I'm also having same issue with latest release, I can play and pause but the icon remains the same.

**Comment by weblancaster** [comment]
Fixed. although this will land in the next version.

**Comment by iRuisu** [comment]
Awesome, thanks dude!
