### ISSUE TITLE
Soundnode app not syncing with main soundcloud website

### ISSUE THREAD

**Issue by Adam-Bronfin** [Soundnode/soundnode-app#699]
Running Version 0.6.3 on Mac OS X 10.10.5 Yosemite 64 bit

Steps:

1. Like, add to a playlist, or repost any song from soundcloud website.
2. See that it doesn't appear in sound node app.

No developer tool console errors except google font failing to load:

http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=latin,latin-ext Failed to load resource: net::ERR_EMPTY_RESPONSE

**Comment by weblancaster** [comment]
@Adam-Bronfin Soundnode won't keep a real-time state of your changes on Soundcloud..

here's a quick flow.

On Soundcloud you like a track and you have Soundnode open on the like view, that won't update with latest.. Soundnode will always get latest when you visit (return) the view/page again so in this case I'm mentioned you would have to go to any other section of Soundnode and then come back to Like view.

**Comment by Adam-Bronfin** [comment]
@weblancaster Shouldn't have closed so quick.....I definitely tried that multiple times. 

In fact, I went as far as un-authenticating my soundcloud account with soundnode-app, and tried a complete new install and login of my account to no avail. Newly liked tracks are simply not showing up.

**Comment by weblancaster** [comment]
if you tried what I said multiple times that is the problem.. Soundnode does not keep a real time data of your Soundcloud data.

Thanks for your feedback @Adam-Bronfin

**Comment by Adam-Bronfin** [comment]
@weblancaster Is there anything that can be done to manually sync the two?

Reason I report this is because after I downloaded the most recent version, this occurred where as before it was showing newly liked songs on soundcloud within the soundnode-app right away.

**Comment by weblancaster** [comment]
at the moment there is no way to do manually @Adam-Bronfin

**Comment by Adam-Bronfin** [comment]
@weblancaster Then I have to say this is a bug.

Soundnode-app will simply not pull new songs in from soundcloud, real time or not.

**Comment by weblancaster** [comment]
the track need to be streamable otherwise we won't display on Soundnode @Adam-Bronfin
