### ISSUE TITLE
(feature suggestion) download sound from the app

### ISSUE THREAD

**Issue by neji013** [Soundnode/soundnode-app#700]
Just a quick message to say it is a shame and a waste of time, everytime i click the download button of a track my browser opened. your app is the best by far but this could make the whole even more fluid.

best regards

**Comment by weblancaster** [comment]
@neji013 agree this is a shame. Been planning to migrate to a better platform that way automatic updates would be available.

**Comment by weblancaster** [comment]
@neji013 Oh reading again what you said I just noticed you are talking about downloading the track not the App..

Third party apps are not allowed to download tracks.
