### ISSUE TITLE
Problem with somes Profiles

### ISSUE THREAD

**Issue by darknessAlex** [Soundnode/soundnode-app#701]
Hi guys, I have a problem with somes profiles. 
![soundnode](https://cloud.githubusercontent.com/assets/8302155/14066214/faa2217e-f400-11e5-820f-1663844c87f1.PNG)

I can't acces to tracks of somes artists. This has happened over the previous version.

Thanks a lot! Great app!

**Comment by weblancaster** [comment]
hey @darknessAlex a lot of artists/profiles doesn't allow third party apps to stream/show their tracks.. this is one of those artists. thanks for the feedback though.
