### ISSUE TITLE
Songs Duplicating

### ISSUE THREAD

**Issue by Exani** [Soundnode/soundnode-app#702]
Songs duplicate everytime a new page is loaded.
![soundnode_2016-03-27_19-48-23](https://cloud.githubusercontent.com/assets/18103205/14066819/f03d3828-f454-11e5-94f4-44b7ec2c57c1.png)

**Comment by DrJosepon** [comment]
Fixed: https://github.com/Soundnode/soundnode-app/pull/703

**Comment by weblancaster** [comment]
This is duplicated issue #583
