### ISSUE TITLE
Keyboard shortcut keys not working unless application is at front

### ISSUE THREAD

**Issue by dequeues** [Soundnode/soundnode-app#705]
Before I could use the Pause/Skip keys without the app being focused on.

Now they don't work unless I have the app opened.

EDIT: Looks like Microsoft's software had something to do with this. Odd. Uninstalled it and it now works.

**Comment by CoCoNO** [comment]
When you say "Uninstalled the keyboard " do you mean The driver?

**Comment by weblancaster** [comment]
The media shortcuts won't work if you have any other application open that uses the media shortcuts

**Comment by narc0tiq** [comment]
For Logitech keyboards, I've found that convincing SetPoint to stop touching the media keys fixes it -- [instructions on SuperUser](http://superuser.com/a/888413) (might be a bit techy).
