### ISSUE TITLE
Like button doesn't update

### ISSUE THREAD

**Issue by zestyr** [Soundnode/soundnode-app#709]
The little like button in the bottom left doesn't update on liked songs. When you play an already liked song, it doesn't light orange. If you click it, it lights orange and says "Song added to likes", even though you've already liked it. If you click it again, it unlikes.

![image](https://cloud.githubusercontent.com/assets/9434921/14141835/f22e54da-f681-11e5-8622-16fe92c1a949.png)

This also causes a bug when you open the Likes list, play a song, hit the botton-left like button twice so you unlike it, then hit the like button underneath the song itself to unlike it (again), an error pops up saying "Oh no! Something went wrong."

![image](https://cloud.githubusercontent.com/assets/9434921/14141942/c10486da-f682-11e5-9835-d75df2e7d401.png)

This probably won't happen very often, but I thought I'd report it.

**Comment by weblancaster** [comment]
We don't have that feat in place yet.. soon to be build

**Comment by grant-h** [comment]
I'd also like to point out that when the song is paused, the like button in the bottom left is hidden, which seems strange to me. Maybe when spelunking that could be addressed if it's not a feature.

**Comment by weblancaster** [comment]
you can open a new issue for that @grant-h

**Comment by weblancaster** [comment]
This is fixed and will be available in the next release.
