### ISSUE TITLE
Soundnode app displays songs multiple times & skips song on page lazy load

### ISSUE THREAD

**Issue by Adam-Bronfin** [Soundnode/soundnode-app#711]
Running Mac OS X 10.10.5 Yosemite & Soundnode Version 0.6.3, the following issue is experienced:

Songs are loaded a duplicate number of times as indicated by the screen shot, and when lazy load is activated by scrolling to the bottom of currently loaded songs on the page, the currently playing song is skipped/restarted.

<img width="936" alt="soundnode-bug" src="https://cloud.githubusercontent.com/assets/3970155/14158995/4e839ec4-f688-11e5-8cef-a8ac42fa48d9.png">

**Comment by weblancaster** [comment]
duplicated #564
