### ISSUE TITLE
Soundnode song status like button disappears on pause

### ISSUE THREAD

**Issue by grant-h** [Soundnode/soundnode-app#722]
While the current song is playing this is visible

<img width="313" alt="screen shot 2016-04-04 at 3 26 31 pm" src="https://cloud.githubusercontent.com/assets/3030665/14260478/ade4cb0a-fa79-11e5-9408-6200244b3d64.png">

after pausing this is what I see

<img width="307" alt="screen shot 2016-04-04 at 3 26 42 pm" src="https://cloud.githubusercontent.com/assets/3030665/14260477/ade3c0ac-fa79-11e5-8e17-0b525585adc0.png">

I believe that the like button should be visible at all times. This is slightly related to #709 in that the bottom like button has some state issues.

I believe the most relevant lines are here: https://github.com/Soundnode/soundnode-app/blob/9e60387b708c95405f32bb19142f551faea475fa/app/index.html#L152-L156

**Comment by grant-h** [comment]
Based on the code `<span class="player_favorite" ng-click="favorite($event)" ng-hide="!isSongPlaying">` it seems like this was meant as a feature. Not sure I feel that way, but open to opinions.

**Comment by weblancaster** [comment]
Yes we did on purpose @grant-h but now we should do it the right way.

**Comment by grant-h** [comment]
@weblancaster Thanks for the response! Would you like me to submit a PR or should I let you handle it?

**Comment by weblancaster** [comment]
Feel free do contribute @grant-h the only thing is that we are going to review and test your code.

**Comment by weblancaster** [comment]
What need to be done here isn't just to always display the "heart" but for each song playing we should check if that song was liked before and mark if so.

**Comment by weblancaster** [comment]
This is fixed and will be available in the next release.
