### ISSUE TITLE
[FEATURE SUGGESTION] Changelog not available

### ISSUE THREAD

**Issue by jeancarlozapata** [Soundnode/soundnode-app#724]
Hello!

Great work on this application. Is there a way to have a changelog when updating?

That would be great, it could be as a file in the repository or in the main Soundnode website.

Thank you and keep up the good work guys!

**Comment by wb9688** [comment]
There is already a changelog on
https://github.com/Soundnode/soundnode-app/releases

**Comment by jeancarlozapata** [comment]
Great! I didn't find it because I looked at the source code, not the releases page, and I downloaded it from the main website (http://www.soundnodeapp.com), sorry :smiley: 

Thank you for the quick reply
