### ISSUE TITLE
Double liked songs

### ISSUE THREAD

**Issue by niceguyluca** [Soundnode/soundnode-app#728]
When I go to the likes section, as soon as i scroll to the bottom to load more songs, they all appear as double, and dis-liking one of the two also dis-likes the other(duh, because it's the same song)

**Comment by weblancaster** [comment]
Yes, this was a known issue and it's fixed.

**Comment by niceguyluca** [comment]
But it's still present in 6.3

**Comment by weblancaster** [comment]
I forgot to mention that this is going to be in the next release @niceguyluca

**Comment by niceguyluca** [comment]
Oh i see, thanks ☺
