### ISSUE TITLE
[FEATURE SUGGESTION] Remember expanded/collapsed playlist while running

### ISSUE THREAD

**Issue by daniellbg** [Soundnode/soundnode-app#735]
OS X v0.6.4
Navigating away from the playlist pane and then back will reset the view. Ideally expanded playlist(s) and scroll position would be remembered for convenient non-consecutive song navigation.

**Comment by dgattey** [comment]
Duplicate of #663 (though more specific, and I agree, a really nice feature to have)

**Comment by weblancaster** [comment]
as @dgattey said this is duplicated for that reason I'm closing this issue.. for further info please check #663
