### ISSUE TITLE
play other music 

### ISSUE THREAD

**Issue by dimohamdy** [Soundnode/soundnode-app#739]
play other music file when scroll down

**Comment by Pitros** [comment]
Please provide more info.

**Comment by dimohamdy** [comment]
i play song then open details of this song then back when scroll down to other songs the app play other song ,and while scroll other songs play

**Comment by Chriz007** [comment]
@dimohamdy what exactly are you trying to say? English is clearly not your first language, so can you tell us with as much detail as you can if you are facing a problem with music playback, or if there is a feature you want put in?

**Comment by jakejarrett** [comment]
@dimohamdy Do you mean when you scroll down a page, it will skip and play a new song like #632 ?

**Comment by dimohamdy** [comment]
@jakejarrett  it's the same
