### ISSUE TITLE
launch soundnode

### ISSUE THREAD

**Issue by stephdgenius** [Soundnode/soundnode-app#748]
How to launch soundnode on nwjs ? because soundnode not charging in my nwjs

**Comment by Pitros** [comment]
First of all you need to install node.js and NPM to install dependencies if you want to run Soundnode from source code. Then run `npm install` and after that you need to run `grunt dev` to compile css etc. and finally you can drag app directory on nw.js executable. 

For faster launching you can create script in package.json by simply adding:
```javascript
scripts: {
"start": "nw app/"
}
``` 
and then run from command npm start, or just simply make shortcut.

More details you can get [here](https://github.com/Soundnode/soundnode-app/wiki/Development).

**Comment by stephdgenius** [comment]
i ha ve a new message : Loading "Gruntfile.js" task...ERROR

**Comment by Pitros** [comment]
Try `npm i -g grunt-cli webpack` and then `grunt dev`

**Comment by stephdgenius** [comment]
okay

**Comment by JonasGroeger** [comment]
@stephdgenius Did it work? Then we can close this here.
