### ISSUE TITLE
Unable to Play a Private Track

### ISSUE THREAD

**Issue by AdityaNG** [Soundnode/soundnode-app#749]
Issue : refer to title

How to recreate : Upload a track to soundcloud, set it to be private and attempt to play it on Soundnode

Error Message : **Oh No** Something went wrong. I can't play this track :(

**Comment by weblancaster** [comment]
Hey @AdityaNG private tracks are not streamable for that reason Soundnode isn't able to play.

I'm going to close this issue. thanks for the feedback.
