### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by rhys0178** [Soundnode/soundnode-app#756]
Could we enable the right hand side sidebar again please? I'm not sure why it's hidden, and I've looked at the source but I couldn't wrap my head around it

**Comment by weblancaster** [comment]
Hey @rhys0178 if you are talking about the Queue list you should be able to see it.. try shift + q to toggle or click the icon at the bottom right

**Comment by rhys0178** [comment]
@weblancaster Hi Michael, soo sorry didn't realise that :-). thanks.

**Comment by weblancaster** [comment]
no problem.
