### ISSUE TITLE
[FEATURE SUGGESTION] Global hotkeys

### ISSUE THREAD

**Issue by rafirafirafi** [Soundnode/soundnode-app#760]
Would be nice to have global hotkeys to be able to control the app while out of focus (at least on windows)

**Comment by weblancaster** [comment]
@rafirafirafi what do you mean? we do have support for media plyer keyboard

**Comment by rafirafirafi** [comment]
my bad! I don't have media keys and I am used to winamp w/ global keys. like Ctrl+PageDown = Next, Ctrl+PageUp = Previous Track etc... I guess i should get a new keyboard :)

**Comment by wb9688** [comment]
Ctrl+PageUp/Down would be good idea as hotkey for people without media
keys. BTW I als don't have media keys on my keyboard and AFAIK you can't
get another keyboard in a laptop :-)

**Comment by weblancaster** [comment]
@rafirafirafi if you don't have the media keys in your keyboard at the moment there is no way to use shortcuts when not focusing on App.

**Comment by rafirafirafi** [comment]
ok fair enough !
