### ISSUE TITLE
Running from the master

### ISSUE THREAD

**Issue by RedstoneGeek223** [Soundnode/soundnode-app#767]
I downloaded the "master" code (from [Here](https://github.com/Soundnode/soundnode-app)) to make sure that my program is fully up to date and want to compile it so i can use it in Windows/Linux/OSX how would I go about doing that?

P.S. I know it might be buggy but hey no harm in trying right?

**Comment by jakejarrett** [comment]
There's a guide on building [here (wiki)](https://github.com/Soundnode/soundnode-app/wiki/Development)

**Comment by RedstoneGeek223** [comment]
Thanks!
