### ISSUE TITLE
System integration on Linux

### ISSUE THREAD

**Issue by pwittchen** [Soundnode/soundnode-app#779]
Hi!

Thanks for the cool project! It would be great if it would have system integration on Linux based systems like Spotify or other players have (see attached screenshot). I'm currently using Ubuntu 14.04 LTS with Gnome.

![system_integration](https://cloud.githubusercontent.com/assets/695319/15633718/d062d0a8-25b4-11e6-942a-67703e8624be.png)

Alternatively, you can provide some tips how to do that, so maybe I can try to implement it or it may be helpful for other contributors.

Regards,
Piotr

**Comment by jakejarrett** [comment]
@pwittchen This is implemented in #645 but needs to be tested on Windows/OSX versions & some small fixes.

**Comment by pwittchen** [comment]
Thanks for the comment! Do you know, when it's gonna be merged to the master branch? The last comment on that issue is almost one-month-old.

**Comment by dn5** [comment]
The mpris is now in a latest build and work on all supported platforms.

**Comment by pwittchen** [comment]
Thanks! I'll check it later.

**Comment by pwittchen** [comment]
Is version with that feature already released? I have version 0.6.4 and it says it's the latest version, but it doesn't integrate with the system.

**Comment by jakejarrett** [comment]
mpris support isn't merged yet. Hopefully it gets merged soon :smile_cat:

**Comment by pwittchen** [comment]
Nice. Can't wait. :)
