### ISSUE TITLE
Audio Not Working

### ISSUE THREAD

**Issue by Joe-LB-03** [Soundnode/soundnode-app#789]
I just downloaded Soundnode. i run the program, sign in and select my favourite song. I hit play - and nothing happens! The now playing bar says the song is playing, but there is no sound. I the volume on the desktop, the volume on the software. Nothing. Please help!

**Comment by wb9688** [comment]
What OS are you using?

**Comment by Joe-LB-03** [comment]
SteamOS which is pretty much Debian.

Get Outlook for iOS




On Wed, Jun 8, 2016 at 9:18 PM +0100, "wb9688" <notifications@github.com> wrote:





What OS are you using?


---

**Comment by jakejarrett** [comment]
@Joe-LB-03 I haven't tested steamOS before, Can you check if soundnode is listed on the applications tab in sound?

If you're unsure on how,
Go to desktop mode, Settings -> Sound -> Applications tab at the end

**Comment by weblancaster** [comment]
closing this since we haven't heard on this for a while
