### ISSUE TITLE
[FEATURE SUGGESTION] Global keyboard shortcuts.

### ISSUE THREAD

**Issue by AdrianSkar** [Soundnode/soundnode-app#790]
Hi guys, love the app, use it every day but I'd also love to have global keyboard shortcuts (as in apps like Clementine, VLC) just for the basic things at least (Play/pause and Next track).

Great work, thank you!!

**Comment by wb9688** [comment]
They already are there: the media keys (if your keyboard has them)

**Comment by AdrianSkar** [comment]
Couldn't get them working on Ubuntu (at least with this one), thats why I needed to use this feature also on those other apps. Ty.

**Comment by wb9688** [comment]
For Linux try #645

**Comment by AdrianSkar** [comment]
My knowledge of git is basic and I don't even know where to start but I'll try. Thank you.

**Comment by wb9688** [comment]
`git clone -b mpris https://github.com/jakejarrett/soundnode-app.git` iirc

**Comment by jakejarrett** [comment]
@AdrianSkar You can do a git clone, but you'll need to install all the dependencies
```bash
npm install -g grunt-cli webpack && npm install --legacy-bundling && grunt build
```

should do the trick once you've got it cloned

**Comment by AdrianSkar** [comment]
I've managed to get it built but it doesn't work (the app launches but no content is shown, just the Main menu and controls). 
I'll stick with the current version and try to get the media keys working globally for my distro.  
Thank you guys, you're great.
