### ISSUE TITLE
Promote Ubuntu/Debian packages

### ISSUE THREAD

**Issue by JonasGroeger** [Soundnode/soundnode-app#791]
Hi @weblancaster!

I am maintaining a [Debian and Ubuntu repository on packagecloud.io](https://packagecloud.io/JonasGroeger/soundnode). This is very nice for Debian and Ubuntu users since the installation and updates are very convenient:

    # Installation
    curl -s https://packagecloud.io/install/repositories/JonasGroeger/soundnode/script.deb.sh | sudo bash
    sudo apt-get update
    sudo apt-get install soundnode

    # Updates come with normal OS updates

Currently, the latest development version is uploaded. However, we could for example have 2 separate repositories: `soundnode` and `soundnode-latest`.

We already have some successfull users of the repository in #775 and #780. My Account on [packagecloud.io](packagecloud.io) is run using the OpenSource package they provide, which means I'm not paying for that (15GB bandwidth and 5GB of storage). Since the package is about 40MB, we can have a total maximum of (15GB / 40MB = ) 375 downloads/month.

I would like to have the instructions on how to install soundnode on Debian/Ubuntu be published / promoted on [soundnodeapp.com](soundnodeapp.com).

How can we arrange that?

**Comment by wb9688** [comment]
I have time today to update Soundnode/soundnode-website#7, which will be
merged if I changed the suggestions in it. I'll also add instructions to
install the Ubuntu/Debian packages.

**Comment by JonasGroeger** [comment]
@wb9688 That'd be great!

**Comment by wb9688** [comment]
Off-topic: @jonasgroeger `sudo apt-get install soundnode` doesn't
automatically install it's dependencies…

**Comment by JonasGroeger** [comment]
@wb9688 I'm not sure what you mean? Which dependencies?

**Comment by wb9688** [comment]
libgconf-2-4 and some others
Op 9 jun. 2016 17:20 schreef "Jonas Gröger" <notifications@github.com>:

**Comment by JonasGroeger** [comment]
@wb9688 You're probably trying that in a docker environment?

**Comment by wb9688** [comment]
No, a real machine with Debian Jessie and just openbox

**Comment by JonasGroeger** [comment]
@wb9688 Ehhm :sweat_smile: see #792

**Comment by hasuki** [comment]
@JonasGroeger i have a trouble: "E: unable to locate package Soundnode"
please help!

**Comment by jakejarrett** [comment]
@hasuki What linux distro & version are you running?

Also, can you try running `sudo apt update && sudo apt install soundnode` and paste the output?
