### ISSUE TITLE
Update to lastest nw.js

### ISSUE THREAD

**Issue by Pitros** [Soundnode/soundnode-app#796]
I've been trying to update nw.js to latest version (0.15.3) but there's an issue with opening authentication window - webpage scripts are unable to open new window by using `window.open()`.

So I thought we could rework how authentication works by removing hidden window which points at `sc-redirect.herokuapp.com` which @weblancaster uses, and make each time authentication is needed the localhost server which will handle redirect after login. That would be easy and probably the best way to fix it. 

Of course we could even not use node http server but that would eliminate ability to login using Facebook or Google.

@weblancaster, doing those changes also will require you to change redirect url in api settings, but that will also kill authentication in older Soundnode versions. So new API might be needed?

**Comment by JonasGroeger** [comment]
I guess #892
