### ISSUE TITLE
[FEATURE] Add ability to download and and choose where to save song locally...

### ISSUE THREAD

**Issue by weblancaster** [Soundnode/soundnode-app#80]
Add ability to download and and choose where to save song locally without leave the App

**Comment by Chriz007** [comment]
^ Waiting for this feature so bad. I always go to http://www.clipconverter.cc/ to download my songs from either youtube or soundcloud. Hope this can be added in the next version or something

**Comment by Pitros** [comment]
It's against API terms of use, so it might be bad idea. 
https://developers.soundcloud.com/docs/api/terms-of-use#caching

**Comment by weblancaster** [comment]
Oh that's a bummer.. thanks for sending @Pitros 

For that reason this is not a future feature.
