### ISSUE TITLE
As a user I want to be able to know when we hit API limit

### ISSUE THREAD

**Issue by weblancaster** [Soundnode/soundnode-app#803]
At the moment the "solution" in place isn't helpful.. perhaps letting the user know before the start playing tracks

**Comment by kiingkiller** [comment]
or maybe having the system delete the local file on launch so that the user can not reach the limit, im not use to this kind of code so i don't know if that will have any negative effects.

**Comment by jakejarrett** [comment]
If the api returns an error on profile hits, we could ping a profile on startup and to verify we hit the rate limit?
