### ISSUE TITLE
Center Mouse Click

### ISSUE THREAD

**Issue by sllafer** [Soundnode/soundnode-app#809]
When u click on any User or song with the center mouse click, app turns white and crash it.

**Comment by weblancaster** [comment]
yes that's because you opened a tab to that link.. the same way you can do for a browser.

We need to add something to block that

**Comment by sllafer** [comment]
If u need help/support, I could help u with any issue.

Im actually IT.

Greats!


2016-07-05 3:54 GMT+02:00 Michael Lancaster <notifications@github.com>:
