### ISSUE TITLE
Keeps telling me there is an update

### ISSUE THREAD

**Issue by Legitgamer264** [Soundnode/soundnode-app#813]
I downloaded the zip file and ran soundnode. On the top it says "Update available" so I re-did the download, and I got the same thing. Keeps having "Update available" in the top right of the app

**Comment by Pitros** [comment]
Which Soundnode version you've downloaded?

**Comment by Legitgamer264** [comment]
The one from the website - http://www.soundnodeapp.com/

**Comment by Legitgamer264** [comment]
0.6.2 is what I have but on the website it says "What's new in 0.6.4". So I assuming I am supposed to be getting 0.6.4, but it shows 0.6.2 in the app

**Comment by Pitros** [comment]
What OS are you using, because that build must be outdated for some reason.

**Comment by Legitgamer264** [comment]
I am on Windows 10 insider preview 14383

**Comment by Pitros** [comment]
Ok, that's weird. Latest version on webpage is 0.6.2 for some reason. 
@weblancaster

**Comment by wb9688** [comment]
I think that @weblancaster hasn't pushed version 0.6.4 to the repo of the
website and that since my new website is online it stores the old version…

**Comment by Pitros** [comment]
Last commit is from 7 Jan, but I'm sure he pushed newer versions. Or he forced old commit for some reason.

**Comment by Legitgamer264** [comment]
is there a place I can get the latest version? Or do I have to wait for it to be updated on the site?

**Comment by Pitros** [comment]
You can download repo and run it from there, but you also need to install node.js

**Comment by Legitgamer264** [comment]
I have node.js and all the dependencies for Soundnode  installed

**Comment by wb9688** [comment]
Piotr, he has pushed it to the website before merging the new website, but
not to the GitHub repo of the website, so the version 0.6.4 is lost.

**Comment by wb9688** [comment]
If you've installed Node.js and Git, you can compile it yourself with:

git clone https://github.com/Soundnode/soundnode-app.git
cd soundnode-app
npm i -g grunt-cli webpack
npm i --legacy-bundling
grunt build

Then you can open it in the `build` folder.

**Comment by weblancaster** [comment]
Looks like when I updated the website merging latest PR and added automated deploy I overwrote the latest App build.. going to release a new version today @Pitros @jakejarrett any objection? if you have seen anything too broken to release please let me know.

take a look here to see what's going to be released https://github.com/Soundnode/soundnode-app/compare/0.6.4...master

**Comment by Pitros** [comment]
@weblancaster, everything works fine. Also #810 can be merged because that's simple fix.

Uh, and #740  was tested for other platforms and works fine, also I've changed what you asked.

**Comment by weblancaster** [comment]
#740 I still think there is better way to do so let's hold on that one.

**Comment by weblancaster** [comment]
I reverted the website back to what was and you should be able to download the correct version now @Legitgamer264 

I was going to release but then decided to hold a bit because I want to merge some of the PRs open.

**Comment by wb9688** [comment]
@weblancaster Can't you replace the download of the new Soundnode website with the latest version?
