### ISSUE TITLE
[FEATURE SUGGESTION] - As an end user, I want to be able to download the media file I am listening to.

### ISSUE THREAD

**Issue by MuhammadHewedy** [Soundnode/soundnode-app#825]
First, I'd like to thank you for your great effort, I like to mention that I did an effort before to create a click when I couldn't find one.

The link for the client I created is: https://github.com/MuhammadHewedy/sooty

Actually I like yours, thought it is much rich than mine, but still I think it need extra work.

I just opened this ticket to ask you to add to your plan the ability to download the media file directly from the player.

**Comment by wb9688** [comment]
It's against the SoundCloud ToS to allow users to download the stream. But
we could add a button for downloading the download which isn't available on
every track.

**Comment by Pitros** [comment]
If author posts download/buy link, it's visible on track page (you need to click on track title). Other download methods violate ToS.

**Comment by isaachinman** [comment]
@MuhammadHewedy Do you have any interest in maintaining a fork that breaks ToS?

**Comment by MuhammadHewedy** [comment]
@isaachinman actually no, I wanted this feature as I see this is a very famous sound cloud client, moreover I created a simple [client](https://github.com/MuhammadHewedy/sooty) couple of years ago with this feature (download any sort of media I like) and I am very comfortable with it :) .
