### ISSUE TITLE
Soundnode v0.6.5 on Packagecloud

### ISSUE THREAD

**Issue by wb9688** [Soundnode/soundnode-app#829]
@JonasGroeger: Can you add the new Soundnode v0.6.5 release to the Packagecloud repository?

**Comment by Mar-tin-W** [comment]
There's a repo but it doesn't work :(

**Comment by wb9688** [comment]
It works, but v0.6.5 hasn't been packaged yet (only v0.6.4)…

**Comment by JonasGroeger** [comment]
@wb9688 I didn't yet update it because I'm having problems with the build.

See #831

**Comment by JonasGroeger** [comment]
Package updated.

Packaging is now done for

    ubuntu/trusty # 14.04 LTS
    ubuntu/xenial # 16.04 LTS
    ubuntu/yakkety # 16.10
    debian/jessie # 8
    elementaryos/jupiter # 0.1
    elementaryos/luna # 0.2
    elementaryos/freya # 0.3
    linuxmint/qiana # 17
    linuxmint/rebecca # 17.1
    linuxmint/rafaela # 17.2
    linuxmint/rosa # 17.3
    linuxmint/sarah # 18

via https://github.com/JonasGroeger/soundnode-app-debian/blob/master/push-deb / https://circleci.com/gh/JonasGroeger/soundnode-app-debian

**Comment by JonasGroeger** [comment]
This can be closed.
