### ISSUE TITLE
Soundnode doesn't load on OpenSuse

### ISSUE THREAD

**Issue by Keepco** [Soundnode/soundnode-app#832]
Hello,
I'm currently trying to get Soundnode working on OpenSuse, but I can't get it to load my stream. My Soundnode client looks like this after logging in:
![screenshot from 2016-07-24 22-16-33](https://cloud.githubusercontent.com/assets/8766773/17086211/de06243a-51ec-11e6-9479-3c7897ae4984.png)

I get the following Warnings/Errors from Soundnode:[571:0724/221112:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[590:0724/221112:ERROR:sandbox_linux.cc(325)] InitializeSandbox() called with multiple threads in process gpu-process
[571:0724/221112:ERROR:nss_util.cc(819)] After loading Root Certs, loaded==false: NSS error code: -8018
[601:0724/221329:WARNING:channel.cc(553)] Failed to send message to ack remove remote endpoint (local ID 1, remote ID 1)
[601:0724/221329:WARNING:channel.cc(320)] RawChannel write error
Parent failed to complete crash dump.

Mozilla-nss is installed&Chromium works without problems.

**Comment by wb9688** [comment]
What's in the console of the devtools (Ctrl+/)?

**Comment by Pitros** [comment]
Same as here - #830, problem with `mpris-service` package, probably not included in build somehow (uh, probably while @weblancaster didn't install that npm package on his machine).

**Comment by weblancaster** [comment]
I think I installed the package correctly if we have on `package.json`. Going to dig more to see if I find why the build is bad for linux
