### ISSUE TITLE
Repo does not work Linux

### ISSUE THREAD

**Issue by Mar-tin-W** [Soundnode/soundnode-app#833]
![screenshot from 2016-07-25 11 47 19](https://cloud.githubusercontent.com/assets/20623262/17097303/99625850-525d-11e6-888b-f1bd098c8a38.png)

**Comment by wb9688** [comment]
There is no Eementary OS package. You should add it manually with the
instructions at https://packagecloud.io/JonasGroeger/soundnode/install and
use ubuntu trusty…

**Comment by Mar-tin-W** [comment]
Which lines do I  need to change?

**Comment by Mar-tin-W** [comment]
just make a deb file to download, it easier.

**Comment by wb9688** [comment]
Go to /etc/apt/sources.list.d/, change the content to `deb
https://packagecloud.io/JonasGroeger/soundnode/ubuntu/ trusty main` and
finally run `apt-get update`.
Alternatively go to https://packagecloud.io/JonasGroeger/soundnode and grab
the .deb for `ubuntu/trusty` for i386 (32 bit) or amd64 (64 bit), but you
won't get updates that way…

**Comment by saikatbsk** [comment]
'deb https://packagecloud.io/JonasGroeger/soundnode/ubuntu/ trusty main' does not work.

**Comment by wb9688** [comment]
The repo works 100% fine, but you should run either:

    curl -s
https://packagecloud.io/install/repositories/JonasGroeger/soundnode/script.deb.sh
| sudo bash
    sudo apt-get install soundnode

Or manually install `apt-transport-https` and add the PGP key of the repo
to your trust store…

**Comment by alma4rebi** [comment]
## change repositories on linuxmint 18.*

**go to**

`sudo gedit /etc/apt/sources.list.d/JonasGroeger_soundnode.list`

**#Delete or disable this repositories**

#deb https://packagecloud.io/JonasGroeger/soundnode/linuxmint/ sylvia main
#deb-src https://packagecloud.io/JonasGroeger/soundnode/linuxmint/ sylvia main

**#change repositories** 

```
deb https://packagecloud.io/JonasGroeger/soundnode/ubuntu/ xenial main
deb-src https://packagecloud.io/JonasGroeger/soundnode/ubuntu/ xenial main
```
