### ISSUE TITLE
Missing tracks

### ISSUE THREAD

**Issue by airpoint** [Soundnode/soundnode-app#834]
Is it just me or some tracks simply don't appear in the app?
Like this example: https://soundcloud.com/ferry-corsten/ferry-corsten-tomorrowland-daybreak-session

Tried to Like it, add to Playlist—no help—simply doesn't appear in the app. Hmmm…

**Comment by SW1FT** [comment]
This has also happened to me in 0.6.4 with other track: https://soundcloud.com/miguel/come-through-and-chill-prod-by-salaam-remi

**Comment by Pitros** [comment]
Those tracks cannot be played - just are simply blocked so we're not displaying it.

**Comment by airpoint** [comment]
@Pitros what you mean cannot be played? They both play just fine in the browser…

**Comment by Pitros** [comment]
@airpoint from soundcloud website every track can be played, but api sometimes returns `playable: false` and even if you try to play that track, you wont get `mp3` for it.
