### ISSUE TITLE
[FEATURE SUGGESTION] OS X app should be signed with a Developer ID

### ISSUE THREAD

**Issue by tnorthcutt** [Soundnode/soundnode-app#837]
This would avoid the pesky `'can't be opened because it is from an unidentified developer` error on OS X. There is a workaround, but it's still pesky.

**Comment by cheekygit** [comment]
I see this so frequently that I wonder if it is forgetfulness or refusal to pay the nominal fee to sign up for an Apple developer ID.

**Comment by weblancaster** [comment]
I did not know about this nor looked to solve because wasn't something people complained.. I do have the apple developer ID I will take a look.
