### ISSUE TITLE
[FEATURE SUGGESTION] Shuffle play

### ISSUE THREAD

**Issue by Mar-tin-W** [Soundnode/soundnode-app#840]
Would be nice to have :)

**Comment by weblancaster** [comment]
we do have shuffle but isn't the best solution. something better might be implemented soon.

**Comment by tripleducke** [comment]
Shuffle in Likes only shuffle what is being displayed/rendered, instead of my entire list. Has been like this since I started using soundnode awhile back. :cry:

**Comment by weblancaster** [comment]
yes just what is on Queue list is shuffled
