### ISSUE TITLE
Make it possible to use Windows-like close buttons on Linux

### ISSUE THREAD

**Issue by wb9688** [Soundnode/soundnode-app#841]
Make it possible to use Windows-like close buttons on Linux, because that'll fit more in some configurations:

![Screenshot](https://cloud.githubusercontent.com/assets/9780201/17360399/b36db694-596b-11e6-8fd2-537ad7c4c8bb.png)

**Comment by Mar-tin-W** [comment]
you mean include the gtk?

**Comment by Pitros** [comment]
You can download repo and change it if you want.

**Comment by wb9688** [comment]
@Mar-tin-W That'd be better, but just an option in the settings to use the Windows close buttons would be good enough for me…

**Comment by weblancaster** [comment]
Let's keep how the OS native works, which is differently.

**Comment by wb9688** [comment]
@weblancaster If you want it how it native works, then you've to:

1. Detect what window manager a user is using
2. Parse the config of that WM to see in what order the close buttons should appear and what theme the user is using
3. Parse the theme and load the images of the close buttons

**Comment by wb9688** [comment]
@weblancaster On my Linux the close buttons are at the right. So that's not
a valid point IMHO…
