### ISSUE TITLE
[FEATURE SUGGESTION] Allow Mac OS X playback control buttons on keyboard (pause/play/next/previous)

### ISSUE THREAD

**Issue by Trismirite** [Soundnode/soundnode-app#845]
It would be nice to see this addition since the shortcut controls on the menubar doesnt work on multiple applications, also resets the size of the screen. I'd much rather use the playback controls on the keyboard (f7, f8, f9)

**Comment by wb9688** [comment]
Soundnode already has support for the media keys…

**Comment by Ucodia** [comment]
I can also confirm that these keys work fine on OSX 10.11.
