### ISSUE TITLE
Repository add failed on Linux Mint 17

### ISSUE THREAD

**Issue by melanholly** [Soundnode/soundnode-app#846]
I am was trying to install this app on Mint 17 and got some unexpected results. After the install script has been run the `apt` could not find `soundnode` on the sources. I've checked out the `/etc/apt/sources.list.d/JonasGroeger_soundnode.list` file and found there was a problem. The distribution should point to the debian package instead of mint package since there is no one premade for mint. 

```
Distributor ID: LinuxMint
Description:    Linux Mint 17.3 Rosa
Release:    17.3
Codename:   rosa

```

The file content of  `/etc/apt/sources.list.d/JonasGroeger_soundnode.list`  was 

``` bash
# this file was generated by packagecloud.io for
# the repository at https://packagecloud.io/JonasGroeger/soundnode

deb https://packagecloud.io/JonasGroeger/soundnode/linuxmint/ rosa main
deb-src https://packagecloud.io/JonasGroeger/soundnode/linuxmint/ rosa main
```

I have modified it so the content now is:

``` bash
# this file was generated by packagecloud.io for
# the repository at https://packagecloud.io/JonasGroeger/soundnode

deb https://packagecloud.io/JonasGroeger/soundnode/debian/  jessie main
deb-src https://packagecloud.io/JonasGroeger/soundnode/debian/ jessie main
```

After running `apt update` the app installed as expected

**Comment by rijnhard** [comment]
linking to related 
https://github.com/Soundnode/soundnode-app/issues/775#issuecomment-225809833

**Comment by JonasGroeger** [comment]
I added Linux Mint to packaging, see: https://github.com/JonasGroeger/soundnode-app-debian/blob/master/push-deb#L47

**Comment by weblancaster** [comment]
thanks @JonasGroeger

**Comment by z-impi** [comment]
For Linux-Mint 18.2 Sonya:

nano /etc/apt/sources.list.d/JonasGroeger_soundnode.list

deb https://packagecloud.io/JonasGroeger/soundnode/ubuntu/ xenial main
deb-src https://packagecloud.io/JonasGroeger/soundnode/ubuntu/ xenial main

or

sudo echo "deb https://packagecloud.io/JonasGroeger/soundnode/ubuntu/ xenial main" > /etc/apt/sources.list.d/JonasGroeger_soundnode.list && echo "deb-src https://packagecloud.io/JonasGroeger/soundnode/ubuntu/ xenial main" >> /etc/apt/sources.list.d/JonasGroeger_soundnode.list

sudo apt-get update && sudo apt-get install -y soundnode
