### ISSUE TITLE
[FEATURE SUGGESTION]Allow app to be ran on background

### ISSUE THREAD

**Issue by glowdemon1** [Soundnode/soundnode-app#849]
Would be nice if we could run Soundnode on the background, meaning that I can close to GUI and keep listening. I don't mean minimizing it only, but removing the button from the taskbar as well.

**Comment by weblancaster** [comment]
@glowdemon1 what OS are you? if MAC OS you should be able to do that otherwise Windows can't do

**Comment by glowdemon1** [comment]
@weblancaster I'm indeed on W10. If it's impossible, I'll close this.

**Comment by Pitros** [comment]
It could be possible, I made PR so you could minimize it to tray but it's still not merged.

**Comment by weblancaster** [comment]
@Pitros he mentioned close (just like we do on Mac) not minimize, is that what the PR is for?

**Comment by Pitros** [comment]
For windows minimizing to tray is the way to do that.

**Comment by weblancaster** [comment]
@Pitros I believe we have that at least last time I checked minimize was working fine.

**Comment by glowdemon1** [comment]
@weblancaster Clicking the minimize button only minimizes it, the close button closes it completely.
