### ISSUE TITLE
Blank application screen in the newest release (0.6.5) on Linux

### ISSUE THREAD

**Issue by pwittchen** [Soundnode/soundnode-app#866]
Hi,

I downloaded the newest release of Soundnode app for Linux (64-bit) from http://www.soundnodeapp.com/ website and it seems it doesn't work.

When I started app and authorized my account, it looked like that:

![soundnode](https://cloud.githubusercontent.com/assets/695319/18232139/d988d9ae-72c9-11e6-85e8-7e53df35a090.png)

When I tried to choose different options the main window was still blank.
Of course, I restarted the app. I even restarted my system and the problem still occurs.

I'm using Ubuntu 14.04 LTS 64-bit.

The older version of the app (0.6.4) works fine.

**Comment by weblancaster** [comment]
this a known issue and duplicated of #830
