### ISSUE TITLE
Drag and drop media bug

### ISSUE THREAD

**Issue by bduman** [Soundnode/soundnode-app#867]
When i drag and drop media onto soundnode, it accepts media and doesn't work anymore.

![pxjjuwr2rt](https://cloud.githubusercontent.com/assets/5374623/18234252/ede7c396-7306-11e6-931f-6e6451e6263e.gif)

**Comment by weblancaster** [comment]
that's not really a bug that's just how it works.. If you want to work, don drag and drop things on the app ;)
