### ISSUE TITLE
Stuck on "Authenticating Your Soundcloud Account."

### ISSUE THREAD

**Issue by jacobysuh** [Soundnode/soundnode-app#868]
As title says, it gets stuck on boot on the authentication page for me. What do I need to provide to help?

Mac OS X 10.11.6

EDIT: Just got the Soundcloud sign-in page now after reopening after a few hours. But upon open, I got "nwjs Helper EH quit unexpectedly" message, which I recall getting after the first time as well. I could login just fine now though.

**Comment by wb9688** [comment]
Are you using v0.6.5 on Linux? If so, that build is broken…

**Comment by jacobysuh** [comment]
Nope, on v0.6.5 on Mac.

**Comment by weblancaster** [comment]
Weird but keep us posted
