### ISSUE TITLE
Play/Pause buttons out of alignment

### ISSUE THREAD

**Issue by wowwood** [Soundnode/soundnode-app#885]
The Play/Pause buttons are not under the mouse when you go near them.
![image](https://cloud.githubusercontent.com/assets/6392165/19022335/06b64faa-88ce-11e6-961a-721bd86ee97c.png)

**Comment by 1percent** [comment]
This is the case for me whenever I reach Play/Pause down from the top or going left from right.
To be honest, I didn't notice this until you posted, I use the space bind almost always.

**Comment by 1percent** [comment]
![detect](https://cloud.githubusercontent.com/assets/22567658/19022465/31900954-888e-11e6-8f53-050b99614ff8.png)
This green right angle looks like its the trigger.

**Comment by weblancaster** [comment]
this was fixed and will be released on the next version

**Comment by wowwood** [comment]
Great!
