### ISSUE TITLE
Artist Restrictions?

### ISSUE THREAD

**Issue by thebitbrine** [Soundnode/soundnode-app#889]
Is there any restrictions about artists and tracks to not show up?
tracks of some of the artists like "Flume" and "Disclosure" doesn't show up in the search results and also it shows no tracks in their profile? Bug or Restriction?

![capture](https://cloud.githubusercontent.com/assets/10282676/19218566/685e54e2-8e0e-11e6-9f35-1b1086c849c8.PNG)

**Comment by wb9688** [comment]
Some artists make their tracks not streamable by third party Soundcloud
clients like Soundnode, so Soundnode just hides them…
