### ISSUE TITLE
timeline clicks are ignored in osx

### ISSUE THREAD

**Issue by nazikus** [Soundnode/soundnode-app#890]
cannot skip track to certain time by clicking on the timeline. Clicks are simply ignored and nothing happens.

OSX 10.11.6 x64
soundnode 0.6.5 build

**Comment by weblancaster** [comment]
@nazikus correct, this is no a feature yet.

**Comment by bryguy** [comment]
Dupe of #847, no?

**Comment by weblancaster** [comment]
yep, it's a dupe.. thanks @bryguy and this can be closed now.
