### ISSUE TITLE
[FEATURE SUGGESTION] Chocolatey Package

### ISSUE THREAD

**Issue by vladjerca** [Soundnode/soundnode-app#891]
Hey there.

I don't know about most of people, but I personally use Chocolatey for managing all my Windows apps.
I found soundnode in the package list.

https://github.com/jvtrigueros/soundnode-app

Above is the github repository for the chocolatey installer.

I wanted to see if this could be integrated in the official repository, this way when a release is made, the new binaries can also be published on chocolatey.

Advantages: 
- easy installation
- easy update
- chocolatey package is always up to date

Distavantages:
- some **_wasted**_ time to integrate it into the deployment strategy 

PS: If everyone is okay with this idea, I can try and make the changes myself this weekend and issue a pull-request. I just want to know if the majority is in on this so I don't invest time unnecessarily.

**Comment by jvtrigueros** [comment]
I'm the author of the Chocolatey package, I'm willing to transfer ownership of the project to the Soundnode organization. The main challenge with creating the Chocolatey package is that I'm pointing to the Soundnode App download url, which does not let me specify a version, so when there's an update on Soundnode the md5 hash breaks the Chocolatey package because it no longer matches.

Right now I have an IFTT recipe listening on releases to alert me when there's a new Soundnode version :)

**Comment by weblancaster** [comment]
@jvtrigueros is the link the one on the website? does it help if I start adding versions to the download link?

**Comment by jvtrigueros** [comment]
Yes, the link is from the website: http://www.soundnodeapp.com/downloads/win/Soundnode.zip
Having alternate links for the different versions would help only if it's valuable to download the older versions of Soundnode App.

It will help in that Chocolatey wont break if I haven't updated the md5 checksum, but that's about it.

**Comment by jvtrigueros** [comment]
Yes, the link is from the website: http://www.soundnodeapp.com/downloads/win/Soundnode.zip
Having alternate links for the different versions would help only if it's valuable to download the older versions of Soundnode App.

It will help in that Chocolatey wont break if I haven't updated the md5 checksum, but that's about it.

**Comment by jakejarrett** [comment]
Would also help with other package managers (AUR, homebrew etc)

**Comment by weblancaster** [comment]
Ok then, next release I'm going to add version numbers
