### ISSUE TITLE
OSX keyboard media buttons not working

### ISSUE THREAD

**Issue by peterklijn** [Soundnode/soundnode-app#896]
Hi,

I'm using Soundnode version 0.6.5, running OSX 10.11.6, and for some reason the keyboard media buttons don't work correctly with Soundnode.

Pressing play/pause triggers OSX to start another audio player (iTunes, Spotify, Vox) instead of pausing the currently playing music in Soundnode. Also the next/previous buttons don't work.
Same goes for using the audio buttons on my headphone.

Not sure if this is a bug or not a feature. In case of the latter, I'd love to see this implemented :)

Cheers,
Peter

**Comment by weblancaster** [comment]
@peterklijn if you have any application open that makes use of the keyboard media that will disable Soundnode from using them.

Otherwise I would try quitting and opening again because should work normally.

**Comment by peterklijn** [comment]
Thanks for the reply @weblancaster.

I had no other programs running and had restarted SoundNode several times. The problem was somewhere else, I also have Vox installed together with the 'Vox Media Buttons' plugin, which had a checkbox 'Launch VOX Player on pressing Play/Pause' turned on. Disabling that seems to fix it.

<img width="780" alt="screen shot 2016-10-20 at 15 55 40" src="https://cloud.githubusercontent.com/assets/2742131/19562916/7baabd82-96de-11e6-8fdb-9f4caee11b4e.png">

Weird thing is that I never have this issue with either iTunes, Spotify or VLC, so I still have the assumption that SoundNode does something different here. Might be interesting to look into it.

**Comment by weblancaster** [comment]
@peterklijn when i said running I was also counting any background software that uses the media keyboard.

This happens because Soundnode media keyboard give away power to OS when something else is using it (not every App does that).

since this is fixed I'm closing the issue. thanks.
