### ISSUE TITLE
It keeps failing while playing song

### ISSUE THREAD

**Issue by GerardRodes** [Soundnode/soundnode-app#897]
But works great from soundcloud web, looks like a connection problem, could be from the api or the app, just wanted to report it because it's not the first time it happens to me.

Great app btw

![captura](https://cloud.githubusercontent.com/assets/16310380/19797246/385594f0-9cea-11e6-9211-a300b77b2a76.PNG)

**Comment by wb9688** [comment]
Does this happen with every song? If so, could you please post a screenshot
of the console (Ctrl+/)?

**Comment by GerardRodes** [comment]
Yeah, it does, it looks like api is rejecting connection due to many requests
![captura](https://cloud.githubusercontent.com/assets/16310380/19797521/e12f50c4-9ceb-11e6-8880-fa9ae4bbcaf1.PNG)

**Comment by wb9688** [comment]
Appearantly we're hitting the API limit again, see eg. #802. For now, you
could try setting `window.localStorage.scClientId` and
`window.localStorage.scAccesToken` to your own ones…

**Comment by weblancaster** [comment]
correct the rate limit was reached.
