### ISSUE TITLE
Soundnode stopped working 

### ISSUE THREAD

**Issue by PouyaJavadzadeh** [Soundnode/soundnode-app#899]
Couple of days ago Soundnode client stopped working and it cannot play any track. I am using version 0.6.5 on Windows 10. It shows the following error message 
![error_message](https://cloud.githubusercontent.com/assets/2132840/19845637/97bacaec-9f73-11e6-8266-594a004fcf39.png)

.

**Comment by weblancaster** [comment]
@PouyaJavadzadeh we have been hitting the API rate limit Soundcloud give to us.

**Comment by 719Ben** [comment]
@weblancaster Might wan't to keep this issue open. I was about to file another before looking in closed.

**Comment by wb9688** [comment]
@719Ben: #802, the first one, is still open…
