### ISSUE TITLE
Soundnode songs wont play or load.

### ISSUE THREAD

**Issue by OfficialCloudee** [Soundnode/soundnode-app#900]
I love this app, but recently I've been starting to have problems with it. Sometimes, the app will work just fine, but most of the time, songs fail to load or play, and every time i try and load a song, it does nothing, and when I try to skip forward in the song to see if that works, it gives me an error. I've tried cleaning local storage, redownloading, every thing. Nothing works. I'm not sure if it has to do with me or the API, or what, but it's quite frustrating. I made a github account just to write this, hoping I can get a solution.

P.S. also soundcloud go support would be heavily appreciated if possible.

**Comment by weblancaster** [comment]
@OfficialCloudee that's because Soundcloud give us a limit of 15 thousand plays per 24hs and we have been having a lot of users daily so for that reason we are reaching the limit and being blocked.

**Comment by dequeues** [comment]
@weblancaster is there a way you could find out whether SoundNode is being blocked and then notify us within the app?

**Comment by CenTdemeern1** [comment]
yeah, by doing CTRL + /

**Comment by weblancaster** [comment]
@dequeues yes, that was implemented in the current version but not released yet. Trying to fix a couple of things before releasing a new version.
