### ISSUE TITLE
Current version 0.6.5 isn't available via PackageCloud

### ISSUE THREAD

**Issue by easterwood** [Soundnode/soundnode-app#901]
You announced the release 0.6.5 and this version is available via the webpage but if you try to update via package manager in ubuntu there is no version 0.6.5 available. 

Please provide the deb package on the webpage.

**Comment by xbonio** [comment]
I confirm, an info about update available is shown, however there's no possible update in the package manager. Please spread the new version into Ubuntu repository.

**Comment by bryannsi** [comment]
It right, please provide the .deb  0.6.5  file on packagecloud. I want to try the new features.

**Comment by JonasGroeger** [comment]
Package updated.

Packaging is now done for

    ubuntu/trusty # 14.04 LTS
    ubuntu/xenial # 16.04 LTS
    ubuntu/yakkety # 16.10
    debian/jessie # 8
    elementaryos/jupiter # 0.1
    elementaryos/luna # 0.2
    elementaryos/freya # 0.3
    linuxmint/qiana # 17
    linuxmint/rebecca # 17.1
    linuxmint/rafaela # 17.2
    linuxmint/rosa # 17.3
    linuxmint/sarah # 18

via https://github.com/JonasGroeger/soundnode-app-debian/blob/master/push-deb / https://circleci.com/gh/JonasGroeger/soundnode-app-debian

**Comment by JonasGroeger** [comment]
This can be closed then.
