### ISSUE TITLE
Explanation about Soundcloud API limit in the Readme.md

### ISSUE THREAD

**Issue by MohanL** [Soundnode/soundnode-app#902]
It seems like hitting the limit of the Soundcloud api is a common thing, so I am thinking creating a common_question/future_fix section in the Read me to clarify these problems. 

I am not sure how the ongoing electron implementation is going to change the situation ?

**Comment by weblancaster** [comment]
Agree 100% @MohanL I'm going to add to README today.

**Comment by MohanL** [comment]
@weblancaster  Thank you ! 💯

**Comment by kemes** [comment]
Is there something that could be done about this limit? Soundnode has quite a few users and the API limit is reached often.

**Comment by weblancaster** [comment]
@kemes I have submitted a request to have another access token if granted I can swap them once the limit is reached.. it can take up to two weeks for Soundcloud reply.

closing this issue since I have added this to readme
