### ISSUE TITLE
How long until we get a refreshed API Limit?

### ISSUE THREAD

**Issue by simpleidiot** [Soundnode/soundnode-app#906]
Title. Loved this application and soundcloud essentially shutting it down to save money is a dick move

**Comment by kennywest** [comment]
although a bit tedious, setting my clientId solved this issue for me, please see:
https://github.com/Soundnode/soundnode-app/issues/802#issuecomment-244126882

**Comment by simpleidiot** [comment]
Thanks, anyway to do it on windows? Only saw examples for OSX

**Comment by simpleidiot** [comment]
nvm lol

**Comment by weblancaster** [comment]
@simpleidiot it depends what time of the day the limit was reached because it's 15 thousand tracks in 24hs therefore every new day is a fresh start.
