### ISSUE TITLE
Tracks won't load or play

### ISSUE THREAD

**Issue by Redix12x** [Soundnode/soundnode-app#907]
Soundnode worked fine this afternoon but after closing it and opening no tracks will play and I just get an error message saying "Oh no. Something went wrong. I can't play this track" if I try to skip ahead. I tried cleaning the local storage and redownloading/rebooting but nothing worked.

**Comment by weblancaster** [comment]
@Redix12x unfortunately Soundcloud impose a limit of 15k play tracks daily and since Soundnode has being used a lot we reached the limit and need to wait for the next day. more here #802

**Comment by czerwinski76** [comment]
It's not à 15K issue. Use Auryo !😀.
https://auryo.com/
