### ISSUE TITLE
no Login possible on 2 of 3 PCs

### ISSUE THREAD

**Issue by JPRuehmann** [Soundnode/soundnode-app#908]
Hello
I have three PCs with Ubuntu 16.04 LTS but soundnode only work with one of them
on the other two I can´t login
If I enter my credentials directly it says they´re wrong, if I push login via Faceboo I only get an empty Window and if I push login via Google nothing happens at all.
If I start soundnode on the Terminal they say the same on all three PCs but only one works.
How can I make them work?

**Comment by weblancaster** [comment]
@JPRuehmann we are having issues with the current build on Linux, Although it's fix on #894 but haven't been released yet.
