### ISSUE TITLE
Unable to play any track someimes

### ISSUE THREAD

**Issue by Alchemisto** [Soundnode/soundnode-app#909]
Ola,
I face this problem occasionally when I try to use the app and I don't know what causes it?
v 0.6.5
![image](https://cloud.githubusercontent.com/assets/3075860/20250196/07fd5c20-aa14-11e6-99fc-bcb97ef9c561.png)

**Comment by weblancaster** [comment]
@Alchemisto unfortunately we have been reaching the rate limit Soundcloud imposed third-party apps. you can find more here #802
