### ISSUE TITLE
Error "Something went wrong. I can't play this track :("

### ISSUE THREAD

**Issue by Akimixu** [Soundnode/soundnode-app#910]
Hello everyone. I've got this error since I downloaded the app. It is the first time I use it and my web SoundCloud still works. Can someone help me please?

![screenshot_1](https://cloud.githubusercontent.com/assets/23489778/20331554/130913f0-ab74-11e6-82af-a9e1ea9f392b.png)

**Comment by weblancaster** [comment]
@Akimixu what operating system are you using? if linux we are having some issues with the new version but the next version (pre-release) is fixed.

Now it may be that we reached the Soundcloud API rate limit. you can open the devtools and check on console what message you get to make sure.

**Comment by berickson21** [comment]
It's been doing this to me too for a couple weeks now. I have no idea what the problem is because it worked fine until one day it randomly just decided not to play :/ I try it every now and then and one time it played one song and then stopped working on the second so that makes it even more confusing. 
I'm on Windows 10 64-bit and I'm pretty sure the only thing I changed on my computer the day it stopped was install Titanfall 2 but I can't imagine that had any impact on it.

**Comment by berickson21** [comment]
I went to the twitter page and saw that the new build is on dropbox so I downloaded it and it's stuck on the "Authenticating" screen with two white popups. One says "This popup should automatically close in a few seconds" and the other is blank.

**Comment by weblancaster** [comment]
@berickson21 yeah that's the last thing I need to fix before releasing the next version.. that will work only for those logged in before. sorry.

**Comment by berickson21** [comment]
No worries! Thanks for all the work you're putting in! Does that mean that in the meantime if I sign in with the old app the new app will work?

**Comment by weblancaster** [comment]
@berickson21 yes the current version on the website is working fine.. but we still have rate limit imposed by Soundcloud API

**Comment by sadanand-garikapati** [comment]
This is observed on my mac as well.

**Comment by Legitgamer264** [comment]
I am getting this right now too

**Comment by ChristopherNeuwirth** [comment]
+1

**Comment by ChristopherNeuwirth** [comment]
Console logs: the server responded with a status of 429 (Too Many Requests)

**Comment by ChristopherNeuwirth** [comment]
It's working again. Thanks!

**Comment by Akimixu** [comment]
Yup, It is working! Thanks for your efforts!

**Comment by weblancaster** [comment]
We have a limit of 15 plays daily so when you see `status of 429 (Too Many Requests)` that's because we reached the limit and Soundcloud block the streaming to Soundnode.

**Comment by g0to** [comment]
Any workarounds to fix this issue would be appreciated. Thanks!

**Comment by Martan404** [comment]
Wouldn't this be bypassed if every user could manually input their own Client ID/API key?

**Comment by Legitgamer264** [comment]
Go here and look at @web9688 comment https://github.com/Soundnode/soundnode-app/issues/802
He made a version of soundnode that does the fix automatically. Give it a try. Just look through the comments in that thread until you see him and his fix

**Comment by weblancaster** [comment]
If there is a need for that I can make it easy to any user enter it's own token.

**Comment by Legitgamer264** [comment]
I think that's a good idea if you can do that. But finish migrating the core first

**Comment by Shehab-Muhammad** [comment]
I have the same issue for ubuntu 14.04
this the first to use the application !!!!

**Comment by weblancaster** [comment]
If you have problems playing and you are not on Linux please follow #802 

Otherwise be aware that the current version is broken for linux, we need to release the current master version which fixes the issue on linux.

**Comment by thomasbnt** [comment]
too bad, for me also it does not want to read.

**Comment by ahmadkhalifah** [comment]
I am having the same issue, no sound. 
I am running v0.6.5 under Windows 10.

**Comment by filipeguarino** [comment]
> This is observed on my mac as well.

+1
