### ISSUE TITLE
 I can not sign in at all

### ISSUE THREAD

**Issue by dsisconeto** [Soundnode/soundnode-app#911]
I'm using ubuntu 16.04, I installed it by apt, but it does not work, I try to log in and it just does not, I put my data righ

**Comment by JPRuehmann** [comment]
I am having thesame trouble with two of three of my Computers.

**Comment by weblancaster** [comment]
the latest version we release for Linux was broken because of a new feat we have added to help users control with media shortcuts and for some reason wasn't built correctly.

Please follow #894 for the next release which come with a bunch of fixes and improvements to the core framework. thanks.
