### ISSUE TITLE
Uninstallation

### ISSUE THREAD

**Issue by Babissimo** [Soundnode/soundnode-app#919]
Hello, I have recently lost purpose in keeping Soundnode. I went to uninstall it but there seemed to be no intuitive way. I tried deleting as many files as possible manually but I do not think I have covered them all. Does anyone know what the standard file directories are, or even better, if there is an "uninstall" button? In advance, thank you!

**Comment by wb9688** [comment]
Assuming you're using Windows, it should only leave data in
`%appdata%\..\Local\Soundnode` (or `%appdata%\..\Local\Soundnode-App` for
older versions of Soundnode)…
