### ISSUE TITLE
No Sound

### ISSUE THREAD

**Issue by JPRuehmann** [Soundnode/soundnode-app#922]
On the one Computer I have that Soundnode is working on I get no sound anymore the application want show at the Mixer to. Kubuntu 16.04

**Comment by HiTechRabbit** [comment]
got the same problem :/

**Comment by weblancaster** [comment]
To know more about this issue take a look here https://github.com/Soundnode/soundnode-app/issues/910

We have a daily limit of 15 thousand plays and when we hit this number Soundcloud block Soundnode from streaming songs. Sorry.
