### ISSUE TITLE
Display notification when too many requests (code 429)

### ISSUE THREAD

**Issue by weblancaster** [Soundnode/soundnode-app#923]
Display notification letting the user know when Soundnode hit the API limit we get a `too many requests` response (code 429).

**Comment by Kaizerus** [comment]
I have the same problem and need a fix _**

> `😢`

**_

**Comment by Kaizerus** [comment]
Is there a way to get rid of it and play the music? Cause i can't play any music

**Comment by weblancaster** [comment]
@Kaizerus there is no way to bypass the rate limit because Soundcloud blocks us from streaming any song.

**Comment by safiyat** [comment]
@weblancaster Could we not add a support for people to use their own client IDs and client secret? I am not sure how it'll work (or if at all it will work), but can't it be done?

**Comment by safiyat** [comment]
@weblancaster Please ignore. Just saw [#802](https://github.com/Soundnode/soundnode-app/issues/802). :)
