### ISSUE TITLE
No work, help pls

### ISSUE THREAD

**Issue by nearcbw** [Soundnode/soundnode-app#930]
I always get this message when I try to play any song "Oh, Something went wrong, I cant play this track" I'm using the Windows 10 PRO, downloaded from the site.

**Comment by Legitgamer264** [comment]
That is because we have reached the API limit of 15k tracks per day. You will have to wait until the API Resets. There is a way around that but you have to get the source of the app from github and follow [This Link](https://github.com/Soundnode/soundnode-app/issues/802#issuecomment-261705999)

**Comment by nearcbw** [comment]
ok, thanks
