### ISSUE TITLE
Can't play : a different error?

### ISSUE THREAD

**Issue by Julien81** [Soundnode/soundnode-app#936]
Hi, I can connect to my soundcloud account using either the login and password on the app or using the user id and token from the python code from wb9688.

In both ways I still can't play any music with the same error as I've read everywhere "something went wrong [...]" so maybe as Legitgamer264 say, there is a problem with the version of electron.
Note: I can't be sure that's a API limit error because I can't reach the devkit, ctrl+/ doesn't work on linux for electron.

edit : I managed to add dev tool manually by adding the line   "mainWindow.webContents.openDevTools()" in the main.js after the mainWindow assignation.
I don't get a loading issue like in [#897](https://github.com/Soundnode/soundnode-app/issues/897)
But this :
playerService.js:216
Uncaught (in promise) DOMException: The element has no supported sources.
player.playSong	@	playerService.js:216
$scope.playPause	@	playerCtrl.js:51
fn	@	VM420:4
e	@	angular.js:26744
$eval	@	angular.js:17972
$apply	@	angular.js:18072
(anonymous function)	@	angular.js:26749
dispatch	@	jquery.min.js:3
q.handle	@	jquery.min.js:3

A new one appear almost each time I try to start a song.

**Comment by weblancaster** [comment]
@Julien81 are you running from source code? can you get latest from master and run `rm -rf node_modules` then `npm i` then `npm run build` then you can start `npm start`.

**Comment by weblancaster** [comment]
try using Node version greater than 4, I use version 7.

**Comment by wb9688** [comment]
The devtools can be opened with Ctrl+Shift+I in the Electron version iirc.
Btw the Electron version stores the tokens on a different place.
