### ISSUE TITLE
[Feature Request] Use of Pause/Play, Skip and go back buttons on my Keyboard

### ISSUE THREAD

**Issue by JMccormick264** [Soundnode/soundnode-app#945]
On my keyboard (I am on Windows) I have Pause/Play, Skip and previous keys on the top. Is there any way that those buttons could work with the app? Like to pause I could just press the pause button on my keyboard and to play I just press it again. Same with the skip song and previous song buttons. I would like this feature

**Comment by weblancaster** [comment]
@Legitgamer264 You should be able to use the media keyboard buttons, but only if you don't have any other software open that uses the media keyboard.

you also need to check if the software you use for your keyboard is supported.

**Comment by Legitgamer264** [comment]
@weblancaster I do not have any other media playing apps open that use those keys. It isn't working for me

**Comment by 21stio** [comment]
Working fine for me too, I am on a Mac. Guess would be got to know what OS you are using^^

**Comment by themanjotsingh** [comment]
On Windows, for me at least, I can use the keyboard media buttons, while doing something else like browsing the web too.
Don't know if specific drivers or other apps you have might interfere. However, I don't think the Windows 8+ pop-up thing that comes up in the top left corner of the screen is built in. Maybe something to look into, in the future? Or while hovering over Soundnode in the taskbar.

**Comment by JMccormick264** [comment]
I could have sworn on a popsicle that it wasn't working before. Maybe i updated something and it is now working. Its working now @weblancaster can be closed

**Comment by weblancaster** [comment]
Haha grea @JMccormick264
