### ISSUE TITLE
Something went wrong cant play track :(

### ISSUE THREAD

**Issue by Reeftone** [Soundnode/soundnode-app#946]
I know that this issue has been covered in previous topics but I still can't figure out how to fix it. 

I have had this app for a year and about 3 or 4 months ago it started acting up with this error. I haven't been able to use it ever since. I am more of a computer user meaning, I don't understand the technicals on these types of issues. 

Im running Sierra 10.12.2 
Ive cleaned local storage, deleted and reinstalled both versions 0.6.5 and 0.6.4 with no luck. 

Is there something i've missed? I really like listening to my music through Soundnode. Please help me out.

**Comment by SzAmmi** [comment]
A lot of people are facing this problem. Me too. If you try to run SoundNode on another operating system, it won't work too :|

**Comment by SzAmmi** [comment]
In `about` you can find:
```
Be aware:
- Every Soundcloud third party has a limit of 15k streamable tracks.
```
maybe this is something realted to SoundNode? I don't know.

**Comment by weblancaster** [comment]
Unfortunately Yes, we have a limit of 15 thousand plays imposed by Soundcloud and people of heavy usage most of days we can't even get pass half of the day before Soundcloud block us.

**Comment by SzAmmi** [comment]
Anyway, this is a great program.

**Comment by weblancaster** [comment]
thank you
