### ISSUE TITLE
How to open developer tools?

### ISSUE THREAD

**Issue by SzAmmi** [Soundnode/soundnode-app#949]
`Ctrl + Shift + I` doesn't work. Any tips?

**Comment by wb9688** [comment]
It's Ctrl+/ in the nwjs version.

**Comment by SzAmmi** [comment]
@wb9688 Thanks very much!

**Comment by weblancaster** [comment]
just fyi @wb9688 it's not nwjs the current master version it's Electron.

**Comment by wb9688** [comment]
@weblancaster: I know we're using Electron in the current `master` branch,
but I told him what the shortcut was when we were still using nwjs…

**Comment by weblancaster** [comment]
got it. thanks.
