### ISSUE TITLE
Cant play anything

### ISSUE THREAD

**Issue by elishinsk** [Soundnode/soundnode-app#960]
Mac Book Pro Mid-2015 macOS Siera 10.12. I can open the app, go to songs but, and hit play. The song will show up in the play bar, but it will no play and I can not skip along. If I try to I get an continuous error messages. 
![screen shot 2017-02-21 at 4 28 23 pm copy](https://cloud.githubusercontent.com/assets/11395551/23185913/1fa01272-f853-11e6-86a4-603f18a52557.jpg)

**Comment by davetufts** [comment]
Same thing for me except on a Mid-2015 Air (with Sierra 10.12.3). Just downloaded and installed the app. Can log in but can't play anything. Same error messages as the screenshot above.

**Comment by asessa** [comment]
Opening the developer tools I see an error on soundcloud APIs, looks like this API key reached the limit.

**Comment by asessa** [comment]
Check #802 for a workaround

**Comment by elishinsk** [comment]
That solved it.
