### ISSUE TITLE
[Bug] Not open in Ubuntu 14.04.05

### ISSUE THREAD

**Issue by Schrammel** [Soundnode/soundnode-app#967]
Ubuntu info:
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

The application crash when i try authentication....

see image... 
![soundnode](https://cloud.githubusercontent.com/assets/5888609/23718628/fa64387e-0416-11e7-8dab-208bcf62e02e.png)

**Comment by weblancaster** [comment]
@Schrammel the last released version is broken on Linux, I need to release a new version which fix the issue. Sorry.

**Comment by Schrammel** [comment]
In Ubuntu 16 is working
