### ISSUE TITLE
Open dev console Windows?

### ISSUE THREAD

**Issue by JMccormick264** [Soundnode/soundnode-app#970]
I for the life of my can't figure out the button combo to get the dev console up for Windows. I tried Ctrl + /. That won't work. Any help?

**Comment by weblancaster** [comment]
are you building from master or the old version released? if the new version on master you need to use the same you use chrome on windows `F12, Ctrl + Shift + I`

If the old version released `ctrl + /` should work otherwise it's a bug/missing feat.

**Comment by JMccormick264** [comment]
thank you! ```Ctrl + Shift + I``` worked
