### ISSUE TITLE
[Bug] Ctrl + Click opens a new window on click. 

### ISSUE THREAD

**Issue by RedHope** [Soundnode/soundnode-app#976]
Version: Latest master (04/01/2017)
Downloaded from: Github.com
OS: Windows 7 64bits

How to reproduce:
 - Open Soundnode App
 - Hold Ctrl and click on any link.

Expected: 
 - The click event is  ignored.
Actual result:
 - A new window is opened. 
 - Closing the new window, closes all the open windows.

![ctrlbug](https://cloud.githubusercontent.com/assets/1368491/24579881/c063f438-16c3-11e7-883b-3f478774c3b3.gif)

**Comment by weblancaster** [comment]
this was fixed by #977
