### ISSUE TITLE
Can Play Any Song

### ISSUE THREAD

**Issue by oLDsPICEchmp** [Soundnode/soundnode-app#980]
Hello I recently found out , about sound node I download the app and I run it. Then I login and try to play any song but nothing comes out. I get the " Something went wrong. I can't play this track".
I looked at recent problems and did the developer thingy and I found this.
![5c7c0230d29ca1d4e3b0a152c6f33042](https://cloud.githubusercontent.com/assets/27571766/25065525/851de0ce-21df-11e7-910b-8adcf65f4b0b.png)
Please help I would love to use my soundcloud

**Comment by weblancaster** [comment]
@oLDsPICEchmp we have a 15k limit to play songs.. please follow #802 for more info.
