### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by pitylee** [Soundnode/soundnode-app#981]
Just an idea. Why won't you register multiple application's on Soundcloud and have an array of api keys?
Like 5 applications, if 1st api key reaches limit, than uses the second?
I know it's not nice, but this may be a workaround :1st_place_medal:

**Comment by pitylee** [comment]
Or maybe add the ability to define our own api key in the settings, and we request api key, save on our profile, not locally, and we can use that on every device where Own API is enabled?

**Comment by weblancaster** [comment]
Hey @pitylee thank you for sharing your ideas.. we have discussed both option in #802 

1. I tried applying for more API keys but Soundcloud denied.
2. I have released the [soundnode backend](https://github.com/Soundnode/sc-oauth) where anyone can add it's own API key.

**Comment by pitylee** [comment]
Okay, I see, well I cloned the repo, and tried it but cant npm run. Where do I clone, and how do I run?

**Comment by weblancaster** [comment]
@pitylee take a look in the `package.json` file and you will see the available tasks. For more info take a look here https://github.com/Soundnode/soundnode-app/wiki/Development#running-and-debugging.
