### ISSUE TITLE
Tracks often not shown when navigating to a channel

### ISSUE THREAD

**Issue by ramonsmits** [Soundnode/soundnode-app#985]
![image](https://cloud.githubusercontent.com/assets/152998/25958001/de22ef26-366f-11e7-8a1e-3b81bbf98bf4.png)

**Comment by wb9688** [comment]
That's most likely because they aren't streamable.

**Comment by weblancaster** [comment]
Correct @wb9688, a lot of tracks are "hidden" because Soundcloud don't allow them to be streamed.
