### ISSUE TITLE
CSS Broken

### ISSUE THREAD

**Issue by felixfong227** [Soundnode/soundnode-app#992]
Once I sign in with my email and password, the app redirect me to the homepage, but then the CSS look very broken

OS: OSX 10.11.6 (15G31)
App version: 0.6.5

![image](https://user-images.githubusercontent.com/13918481/26871706-ac4b8336-4ba6-11e7-90ce-ffcc36f8b696.png)

**Comment by Pitros** [comment]
Since you're running from repo, you need to compile sass first. Run:
```
npm run sass:dev
```

**Comment by felixfong227** [comment]
Oh ya, silly me :P
Thanks @Pitros
