### ISSUE TITLE
Mac app doesn't play

### ISSUE THREAD

**Issue by swiftty** [Soundnode/soundnode-app#996]
I tested it on 2 different mac computers. None of them was able to play anything. Not sure why. There's no error, no notification. It just doesn't start

**Comment by wb9688** [comment]
If you open the Console (Ctrl+/ in the old nw.js app), does it tell you
something about the rate limit? If so, this is a duplicate of #802, where
I've also posted a temporarily solution.

**Comment by swiftty** [comment]
It says : 

https://api.soundcloud.com/tracks/321408456/stream?client_id=342b8a7af638944906dcdb46f9d56d98 
Failed to load resource: the server responded with a status of 429 (Unknown)

**Comment by wb9688** [comment]
OK, then this issue is a duplicate of #802, where I've posted a temporarily
solution. Btw you shouldn't share that client ID, since it'd allow anyone
to access your SoundCloud account.
