### ISSUE TITLE
Proposed fix for removing 15k daily play limit

### ISSUE THREAD

**Issue by ryanckulp** [Soundnode/soundnode-app#998]
why not allow users to provide their own Soundcloud API keys, to bypass your master keys' 15,000 play limit?

i have several soundcloud API credentials that aren't being used.

for that matter, why not let users contribute to a shared 'pool' of keys so that the net effective daily limit is higher?

**Comment by weblancaster** [comment]
@ryanckulp I have made the Soundnode authentication service open for anyone with API keys to be able to use. https://github.com/Soundnode/sc-oauth

**Comment by Ronsku** [comment]
@weblancaster really nice! I was actually planning to do something like this myself, but then I realised that they don't give out API keys anymore.. https://soundcloud.com/you/apps/new
